// Generated from space_data.proto
package Next.pojo;

import com.roco.sniffer.codec.Pojos;
import com.roco.sniffer.codec.ProtoParser.ProtoField;
import com.roco.sniffer.codec.ProtoParser;
import java.util.List;

@SuppressWarnings("unused")
public record ActorCompData_AvatarMisc(
    boolean posSyncFlag,
    AvatarPetInfo petInfo,
    int envMask,
    int owlSanctuaryNpcRefreshContentId,
    List<Integer> owlSanctuaryLevelUp,
    int cardLabelFirstSelected,
    int cardLabelLastSelected,
    int cardSkinSelected,
    int cardIconSelected,
    byte[] openid,
    byte[] clientVersion,
    List<HandbookRecord> handbookRecords,
    String clientIp,
    String clientIpv6,
    int quality,
    PlatInfo platInfo,
    ClientInfo clientInfo,
    SnsAuthInfo snsAuthInfo,
    long test1,
    long test2,
    long test3,
    boolean enterStrongStorm,
    int lastSubHpTime,
    long lastUnstuckTime,
    List<AvatarBehaviorStatusInfo> avatarBehaviorStatusInfos,
    long endTransformTime,
    int transformAreaFuncId,
    boolean checkTransformTime,
    List<NpcGuideInfo> guideInfo,
    long pvpMatchNpcId,
    int pvpMatchPvpId,
    int pvpMatchStartUt,
    long pvpMatchDstInstId,
    List<StorageItemInfo> storageItems,
    int cardMusicId,
    List<MagicCreateNpcInfo> magicCreateNpcs,
    long cameraNpcId,
    int caveAreaFuncId,
    List<SpecBattleDifficultyInfo> difficultyInfos,
    List<ContinuousCatchShinyNightmareRecord> nightmareRecords
) {
    public static ActorCompData_AvatarMisc parseFrom(byte[] data) {
        java.util.List<ProtoField> fields = ProtoParser.parse(data);
        return new ActorCompData_AvatarMisc(
            Pojos.readBool(fields, 1),
            Pojos.readMessage(fields, 2) != null ? Next.pojo.AvatarPetInfo.parseFrom(Pojos.readMessage(fields, 2)) : null,
            Pojos.readInt(fields, 5),
            Pojos.readInt(fields, 6),
            Pojos.readIntList(fields, 7),
            Pojos.readInt(fields, 8),
            Pojos.readInt(fields, 9),
            Pojos.readInt(fields, 10),
            Pojos.readInt(fields, 11),
            Pojos.readBytes(fields, 12),
            Pojos.readBytes(fields, 13),
            Pojos.readMessageList(fields, 14).stream().map(Next.pojo.HandbookRecord::parseFrom).toList(),
            Pojos.readString(fields, 15),
            Pojos.readString(fields, 16),
            Pojos.readInt(fields, 17),
            Pojos.readMessage(fields, 18) != null ? Next.pojo.PlatInfo.parseFrom(Pojos.readMessage(fields, 18)) : null,
            Pojos.readMessage(fields, 19) != null ? Next.pojo.ClientInfo.parseFrom(Pojos.readMessage(fields, 19)) : null,
            Pojos.readMessage(fields, 20) != null ? Next.pojo.SnsAuthInfo.parseFrom(Pojos.readMessage(fields, 20)) : null,
            Pojos.readLong(fields, 80),
            Pojos.readLong(fields, 81),
            Pojos.readLong(fields, 82),
            Pojos.readBool(fields, 201),
            Pojos.readInt(fields, 202),
            Pojos.readLong(fields, 210),
            Pojos.readMessageList(fields, 300).stream().map(Next.pojo.AvatarBehaviorStatusInfo::parseFrom).toList(),
            Pojos.readLong(fields, 301),
            Pojos.readInt(fields, 302),
            Pojos.readBool(fields, 303),
            Pojos.readMessageList(fields, 400).stream().map(Next.pojo.NpcGuideInfo::parseFrom).toList(),
            Pojos.readLong(fields, 500),
            Pojos.readInt(fields, 501),
            Pojos.readInt(fields, 502),
            Pojos.readLong(fields, 503),
            Pojos.readMessageList(fields, 510).stream().map(Next.pojo.StorageItemInfo::parseFrom).toList(),
            Pojos.readInt(fields, 600),
            Pojos.readMessageList(fields, 610).stream().map(Next.pojo.MagicCreateNpcInfo::parseFrom).toList(),
            Pojos.readLong(fields, 620),
            Pojos.readInt(fields, 630),
            Pojos.readMessageList(fields, 640).stream().map(Next.pojo.SpecBattleDifficultyInfo::parseFrom).toList(),
            Pojos.readMessageList(fields, 650).stream().map(Next.pojo.ContinuousCatchShinyNightmareRecord::parseFrom).toList()
        );
    }
    public static ActorCompData_AvatarMisc parseFrom(java.util.List<ProtoField> fields) {
        return new ActorCompData_AvatarMisc(
            Pojos.readBool(fields, 1),
            Pojos.readMessage(fields, 2) != null ? Next.pojo.AvatarPetInfo.parseFrom(Pojos.readMessage(fields, 2)) : null,
            Pojos.readInt(fields, 5),
            Pojos.readInt(fields, 6),
            Pojos.readIntList(fields, 7),
            Pojos.readInt(fields, 8),
            Pojos.readInt(fields, 9),
            Pojos.readInt(fields, 10),
            Pojos.readInt(fields, 11),
            Pojos.readBytes(fields, 12),
            Pojos.readBytes(fields, 13),
            Pojos.readMessageList(fields, 14).stream().map(Next.pojo.HandbookRecord::parseFrom).toList(),
            Pojos.readString(fields, 15),
            Pojos.readString(fields, 16),
            Pojos.readInt(fields, 17),
            Pojos.readMessage(fields, 18) != null ? Next.pojo.PlatInfo.parseFrom(Pojos.readMessage(fields, 18)) : null,
            Pojos.readMessage(fields, 19) != null ? Next.pojo.ClientInfo.parseFrom(Pojos.readMessage(fields, 19)) : null,
            Pojos.readMessage(fields, 20) != null ? Next.pojo.SnsAuthInfo.parseFrom(Pojos.readMessage(fields, 20)) : null,
            Pojos.readLong(fields, 80),
            Pojos.readLong(fields, 81),
            Pojos.readLong(fields, 82),
            Pojos.readBool(fields, 201),
            Pojos.readInt(fields, 202),
            Pojos.readLong(fields, 210),
            Pojos.readMessageList(fields, 300).stream().map(Next.pojo.AvatarBehaviorStatusInfo::parseFrom).toList(),
            Pojos.readLong(fields, 301),
            Pojos.readInt(fields, 302),
            Pojos.readBool(fields, 303),
            Pojos.readMessageList(fields, 400).stream().map(Next.pojo.NpcGuideInfo::parseFrom).toList(),
            Pojos.readLong(fields, 500),
            Pojos.readInt(fields, 501),
            Pojos.readInt(fields, 502),
            Pojos.readLong(fields, 503),
            Pojos.readMessageList(fields, 510).stream().map(Next.pojo.StorageItemInfo::parseFrom).toList(),
            Pojos.readInt(fields, 600),
            Pojos.readMessageList(fields, 610).stream().map(Next.pojo.MagicCreateNpcInfo::parseFrom).toList(),
            Pojos.readLong(fields, 620),
            Pojos.readInt(fields, 630),
            Pojos.readMessageList(fields, 640).stream().map(Next.pojo.SpecBattleDifficultyInfo::parseFrom).toList(),
            Pojos.readMessageList(fields, 650).stream().map(Next.pojo.ContinuousCatchShinyNightmareRecord::parseFrom).toList()
        );
    }
}
