// Generated from space_data.proto
package Next.pojo;

import com.roco.sniffer.codec.Pojos;
import com.roco.sniffer.codec.ProtoParser.ProtoField;
import com.roco.sniffer.codec.ProtoParser;
import java.util.List;

@SuppressWarnings("unused")
public record ActorPartData_NpcBase(
    int npcCfgId,
    int traverseDataType,
    int height,
    int weight,
    int nature,
    int npcContentCfgId,
    int mutationType,
    int npcRefreshSource,
    int npcOwlContentId,
    int rand,
    long srcNpcLogicId,
    long srcNpcId,
    int srcNpcCfgId,
    int srcNpcRefCfgId,
    Position srcNpcPos,
    boolean posNeedAdjust,
    int worldNature,
    int worldHide,
    Position relatedNpcPos,
    int refreshPoint,
    long createAvatarId,
    int bloodMixSkillDamType,
    int firstCreateTime,
    String loopAction,
    int catchGuaranteeRate,
    long lastCatchTime,
    List<Long> childrenNpcList,
    int refreshTime,
    int deepDeleteReason,
    boolean canBeTeleport,
    float heightScale,
    long ownerId,
    int lastAttrResetTime,
    int bloodNormalSkillDamType,
    long blockId,
    int homePlantLandId,
    boolean autoRefresh,
    GlassInfo glassInfo,
    int attachItemType,
    long attachItemId,
    int voice,
    List<Long> createVisitingUins,
    String createAvatarName
) {
    public static ActorPartData_NpcBase parseFrom(byte[] data) {
        java.util.List<ProtoField> fields = ProtoParser.parse(data);
        return new ActorPartData_NpcBase(
            Pojos.readInt(fields, 1),
            Pojos.readInt(fields, 9),
            Pojos.readInt(fields, 2),
            Pojos.readInt(fields, 3),
            Pojos.readInt(fields, 4),
            Pojos.readInt(fields, 5),
            Pojos.readInt(fields, 6),
            Pojos.readInt(fields, 7),
            Pojos.readInt(fields, 8),
            Pojos.readInt(fields, 10),
            Pojos.readLong(fields, 12),
            Pojos.readLong(fields, 13),
            Pojos.readInt(fields, 14),
            Pojos.readInt(fields, 15),
            Pojos.readMessage(fields, 16) != null ? Next.pojo.Position.parseFrom(Pojos.readMessage(fields, 16)) : null,
            Pojos.readBool(fields, 17),
            Pojos.readInt(fields, 18),
            Pojos.readInt(fields, 19),
            Pojos.readMessage(fields, 20) != null ? Next.pojo.Position.parseFrom(Pojos.readMessage(fields, 20)) : null,
            Pojos.readInt(fields, 21),
            Pojos.readLong(fields, 22),
            Pojos.readInt(fields, 23),
            Pojos.readInt(fields, 24),
            Pojos.readString(fields, 27),
            Pojos.readInt(fields, 25),
            Pojos.readLong(fields, 26),
            Pojos.readLongList(fields, 28),
            Pojos.readInt(fields, 29),
            Pojos.readInt(fields, 30),
            Pojos.readBool(fields, 31),
            Pojos.readFloat(fields, 32),
            Pojos.readLong(fields, 33),
            Pojos.readInt(fields, 35),
            Pojos.readInt(fields, 36),
            Pojos.readLong(fields, 37),
            Pojos.readInt(fields, 38),
            Pojos.readBool(fields, 39),
            Pojos.readMessage(fields, 40) != null ? Next.pojo.GlassInfo.parseFrom(Pojos.readMessage(fields, 40)) : null,
            Pojos.readInt(fields, 41),
            Pojos.readLong(fields, 42),
            Pojos.readInt(fields, 43),
            Pojos.readLongList(fields, 44),
            Pojos.readString(fields, 45)
        );
    }
    public static ActorPartData_NpcBase parseFrom(java.util.List<ProtoField> fields) {
        return new ActorPartData_NpcBase(
            Pojos.readInt(fields, 1),
            Pojos.readInt(fields, 9),
            Pojos.readInt(fields, 2),
            Pojos.readInt(fields, 3),
            Pojos.readInt(fields, 4),
            Pojos.readInt(fields, 5),
            Pojos.readInt(fields, 6),
            Pojos.readInt(fields, 7),
            Pojos.readInt(fields, 8),
            Pojos.readInt(fields, 10),
            Pojos.readLong(fields, 12),
            Pojos.readLong(fields, 13),
            Pojos.readInt(fields, 14),
            Pojos.readInt(fields, 15),
            Pojos.readMessage(fields, 16) != null ? Next.pojo.Position.parseFrom(Pojos.readMessage(fields, 16)) : null,
            Pojos.readBool(fields, 17),
            Pojos.readInt(fields, 18),
            Pojos.readInt(fields, 19),
            Pojos.readMessage(fields, 20) != null ? Next.pojo.Position.parseFrom(Pojos.readMessage(fields, 20)) : null,
            Pojos.readInt(fields, 21),
            Pojos.readLong(fields, 22),
            Pojos.readInt(fields, 23),
            Pojos.readInt(fields, 24),
            Pojos.readString(fields, 27),
            Pojos.readInt(fields, 25),
            Pojos.readLong(fields, 26),
            Pojos.readLongList(fields, 28),
            Pojos.readInt(fields, 29),
            Pojos.readInt(fields, 30),
            Pojos.readBool(fields, 31),
            Pojos.readFloat(fields, 32),
            Pojos.readLong(fields, 33),
            Pojos.readInt(fields, 35),
            Pojos.readInt(fields, 36),
            Pojos.readLong(fields, 37),
            Pojos.readInt(fields, 38),
            Pojos.readBool(fields, 39),
            Pojos.readMessage(fields, 40) != null ? Next.pojo.GlassInfo.parseFrom(Pojos.readMessage(fields, 40)) : null,
            Pojos.readInt(fields, 41),
            Pojos.readLong(fields, 42),
            Pojos.readInt(fields, 43),
            Pojos.readLongList(fields, 44),
            Pojos.readString(fields, 45)
        );
    }
}
