// Generated from space_data.proto
package Next.pojo;

import com.roco.sniffer.codec.Pojos;
import com.roco.sniffer.codec.ProtoParser.ProtoField;
import com.roco.sniffer.codec.ProtoParser;

@SuppressWarnings("unused")
public record ActorData_Avatar(
    ActorPartData_Base base,
    ActorPartData_AvatarBase avatarBase,
    SpaceObjPartData_InstalledComp installedComps,
    ActorCompData_Test compDataTest,
    ActorCompData_Broadcaster compDataBroadcaster,
    ActorCompData_ClientMover compDataMover,
    ActorCompData_Owner compDataOwner,
    ActorCompData_Transform compDataTransform,
    ActorCompData_StatusGuarder compDataStatusGuarder,
    ActorCompData_AttrMgr compDataAttrMgr,
    ActorCompData_AnimSkillPlayer compDataAnimSkillPlayer,
    ActorCompData_NpxCapsuleCCT compDataCapsuleCct,
    ActorCompData_Heartbeat compDataHeartbeat,
    ActorCompData_Skill compDataSkill,
    ActorCompData_Battle compDataBattle,
    ActorCompData_Minigame compDataMinigame,
    ActorCompData_MsgSender compDataMsgSender,
    ActorCompData_AreaMgr compDataAreaMgr,
    ActorCompData_NpcRefresher compDataNpcRefresher,
    ActorCompData_StoryFlag compDataStoryFlag,
    ActorCompData_Task compDataTask,
    ActorCompData_AvatarMisc compDataAvatarMisc,
    ActorCompData_AI compDataAi,
    ActorCompData_AI_LOD compDataAiLod,
    ActorCompData_CombineNpc compDataCombineNpc,
    ActorCompData_Rider compDataRider,
    ActorCompData_Navigator compDataNavigator,
    ActorCompData_AuraMgr compDataAuraMgr,
    ActorCompData_AvatarInteractor compDataAvatarInteractor,
    ActorCompData_NonAvatarIdGen compDataIdGenner,
    ActorCompData_NpcInstantiator npcInstantiator,
    ActorCompData_Thrower compDataThrower,
    ActorCompData_WorldMap compDataWorldMap,
    ActorCompData_Temperature compDataTemperature,
    ActorCompData_AvatarAI compAvatarAi,
    ActorCompData_ActionTag compActionTag,
    ActorCompData_BornDieCtrler compBornDieCtrler,
    ActorCompData_Revive compRevive,
    ActorCompData_LogicStatus compLogicStatus,
    ActorCompData_GameTime compDataGameTime,
    ActorCompData_AvatarCamp compDataAvatarCamp,
    ActorCompData_Weather compDataWeather,
    ActorCompData_Exchange compDataExchange,
    ActorCompData_ActionBonus compDataActionBonus,
    ActorCompData_ObjectAward compDataObjectAward,
    ActorCompData_AreaDetector compDataAreaDetector,
    ActorCompData_Appearance compDataAppearance,
    ActorCompData_Dungeon compDataDungeon,
    ActorCompData_Visit compDataVisit,
    ActorCompData_Pet compDataPet,
    ActorCompData_PetInteract compDataPetInteract,
    ActorCompData_Buff compDataBuff,
    ActorCompData_WorldCombat compDataWorldCombat,
    ActorCompData_WorldCombatSkill compDataWorldCombatSkill,
    ActorCompData_InitAOIWaiter compDataInitAoiWaiter,
    ActorCompData_VoicePlayer compDataVoicePlayer,
    ActorCompData_ClientEvent compDataClientEvent,
    ActorCompData_SceneRpcRetryMgr compDataRpcRetryMgr,
    ActorCompData_PetPerception compDataPetPreception,
    ActorCompData_NpcTaskProcessor compDataNpcTaskProcessor,
    ActorCompData_Activity compDataActivity,
    ActorCompData_Trigger compDataTrigger,
    ActorCompData_DotsLabel compDataDotsLabel,
    ActorCompData_AOwlSanctuary compDataAvatarOwlSanctuary,
    ActorCompData_Follower compDataAvatarFollower,
    ActorCompData_MsgRecover compDataAvatarRecover,
    ActorCompData_Stamina compDataStamina,
    ActorCompData_TaskState compDataAvatarTaskState,
    ActorCompData_AreaTrigger compDataAvatarAreaTrigger,
    ActorCompData_CccChecker compDataCccChecker,
    ActorCompData_DotsSkill compDataDotsSkill,
    ActorCompData_NpxCollision compDataCollision,
    ActorCompData_Db compDataDb,
    ActorCompData_NpcTrace compDataNpcTrace,
    ActorCompData_AirWall comDataAirWall,
    ActorCompData_HomeBasic compDataHomeBasic,
    ActorCompData_HomePlant compDataHomePlant,
    ActorCompData_TeamBattle compDataTeamBattle,
    ActorCompData_Feed compDataFeed,
    ActorCompData_VisibleArea compDataVisibleArea,
    ActorCompData_HomeInteract compDataHomeInteract,
    ActorCompData_RelationInteract compDataRelationInteract,
    ActorCompData_AvatarMultiChat compDataAvatarMultiChat,
    ActorCompData_TravelingMerchant compDataTravelingMerchant,
    ActorCompData_Season compDataSeason,
    ActorCompData_FusionOwlSanctuary compDataFusionOwlSanctuary,
    ActorCompData_BagItem compDataBagItem,
    ActorCompData_BossFlowerSeed compDataFlowerSeed,
    ActorCompData_AvatarFriendProxy compDataAvatarFriendProxy,
    ActorCompData_VisibleCircle compDataVisibleCircle,
    ActorCompData_TeleportInfoHolder compDataTeleportInfoHolder,
    ActorCompData_CatchRefreshRecord compDataCatchRefreshRecord,
    ActorCompData_SocialInfoReporter compDataSocialInfoReporter,
    ActorCompData_NpcGuard compDataNpcGuard,
    ActorCompData_NightMode compDataNightMode
) {
    public static ActorData_Avatar parseFrom(byte[] data) {
        java.util.List<ProtoField> fields = ProtoParser.parse(data);
        return new ActorData_Avatar(
            Pojos.readMessage(fields, 1) != null ? Next.pojo.ActorPartData_Base.parseFrom(Pojos.readMessage(fields, 1)) : null,
            Pojos.readMessage(fields, 2) != null ? Next.pojo.ActorPartData_AvatarBase.parseFrom(Pojos.readMessage(fields, 2)) : null,
            Pojos.readMessage(fields, 10) != null ? Next.pojo.SpaceObjPartData_InstalledComp.parseFrom(Pojos.readMessage(fields, 10)) : null,
            Pojos.readMessage(fields, 11) != null ? Next.pojo.ActorCompData_Test.parseFrom(Pojos.readMessage(fields, 11)) : null,
            Pojos.readMessage(fields, 12) != null ? Next.pojo.ActorCompData_Broadcaster.parseFrom(Pojos.readMessage(fields, 12)) : null,
            Pojos.readMessage(fields, 13) != null ? Next.pojo.ActorCompData_ClientMover.parseFrom(Pojos.readMessage(fields, 13)) : null,
            Pojos.readMessage(fields, 14) != null ? Next.pojo.ActorCompData_Owner.parseFrom(Pojos.readMessage(fields, 14)) : null,
            Pojos.readMessage(fields, 15) != null ? Next.pojo.ActorCompData_Transform.parseFrom(Pojos.readMessage(fields, 15)) : null,
            Pojos.readMessage(fields, 16) != null ? Next.pojo.ActorCompData_StatusGuarder.parseFrom(Pojos.readMessage(fields, 16)) : null,
            Pojos.readMessage(fields, 17) != null ? Next.pojo.ActorCompData_AttrMgr.parseFrom(Pojos.readMessage(fields, 17)) : null,
            Pojos.readMessage(fields, 19) != null ? Next.pojo.ActorCompData_AnimSkillPlayer.parseFrom(Pojos.readMessage(fields, 19)) : null,
            Pojos.readMessage(fields, 22) != null ? Next.pojo.ActorCompData_NpxCapsuleCCT.parseFrom(Pojos.readMessage(fields, 22)) : null,
            Pojos.readMessage(fields, 23) != null ? Next.pojo.ActorCompData_Heartbeat.parseFrom(Pojos.readMessage(fields, 23)) : null,
            Pojos.readMessage(fields, 24) != null ? Next.pojo.ActorCompData_Skill.parseFrom(Pojos.readMessage(fields, 24)) : null,
            Pojos.readMessage(fields, 25) != null ? Next.pojo.ActorCompData_Battle.parseFrom(Pojos.readMessage(fields, 25)) : null,
            Pojos.readMessage(fields, 26) != null ? Next.pojo.ActorCompData_Minigame.parseFrom(Pojos.readMessage(fields, 26)) : null,
            Pojos.readMessage(fields, 27) != null ? Next.pojo.ActorCompData_MsgSender.parseFrom(Pojos.readMessage(fields, 27)) : null,
            Pojos.readMessage(fields, 28) != null ? Next.pojo.ActorCompData_AreaMgr.parseFrom(Pojos.readMessage(fields, 28)) : null,
            Pojos.readMessage(fields, 29) != null ? Next.pojo.ActorCompData_NpcRefresher.parseFrom(Pojos.readMessage(fields, 29)) : null,
            Pojos.readMessage(fields, 30) != null ? Next.pojo.ActorCompData_StoryFlag.parseFrom(Pojos.readMessage(fields, 30)) : null,
            Pojos.readMessage(fields, 31) != null ? Next.pojo.ActorCompData_Task.parseFrom(Pojos.readMessage(fields, 31)) : null,
            Pojos.readMessage(fields, 32) != null ? Next.pojo.ActorCompData_AvatarMisc.parseFrom(Pojos.readMessage(fields, 32)) : null,
            Pojos.readMessage(fields, 33) != null ? Next.pojo.ActorCompData_AI.parseFrom(Pojos.readMessage(fields, 33)) : null,
            Pojos.readMessage(fields, 34) != null ? Next.pojo.ActorCompData_AI_LOD.parseFrom(Pojos.readMessage(fields, 34)) : null,
            Pojos.readMessage(fields, 35) != null ? Next.pojo.ActorCompData_CombineNpc.parseFrom(Pojos.readMessage(fields, 35)) : null,
            Pojos.readMessage(fields, 36) != null ? Next.pojo.ActorCompData_Rider.parseFrom(Pojos.readMessage(fields, 36)) : null,
            Pojos.readMessage(fields, 18) != null ? Next.pojo.ActorCompData_Navigator.parseFrom(Pojos.readMessage(fields, 18)) : null,
            Pojos.readMessage(fields, 37) != null ? Next.pojo.ActorCompData_AuraMgr.parseFrom(Pojos.readMessage(fields, 37)) : null,
            Pojos.readMessage(fields, 38) != null ? Next.pojo.ActorCompData_AvatarInteractor.parseFrom(Pojos.readMessage(fields, 38)) : null,
            Pojos.readMessage(fields, 39) != null ? Next.pojo.ActorCompData_NonAvatarIdGen.parseFrom(Pojos.readMessage(fields, 39)) : null,
            Pojos.readMessage(fields, 40) != null ? Next.pojo.ActorCompData_NpcInstantiator.parseFrom(Pojos.readMessage(fields, 40)) : null,
            Pojos.readMessage(fields, 42) != null ? Next.pojo.ActorCompData_Thrower.parseFrom(Pojos.readMessage(fields, 42)) : null,
            Pojos.readMessage(fields, 43) != null ? Next.pojo.ActorCompData_WorldMap.parseFrom(Pojos.readMessage(fields, 43)) : null,
            Pojos.readMessage(fields, 44) != null ? Next.pojo.ActorCompData_Temperature.parseFrom(Pojos.readMessage(fields, 44)) : null,
            Pojos.readMessage(fields, 46) != null ? Next.pojo.ActorCompData_AvatarAI.parseFrom(Pojos.readMessage(fields, 46)) : null,
            Pojos.readMessage(fields, 47) != null ? Next.pojo.ActorCompData_ActionTag.parseFrom(Pojos.readMessage(fields, 47)) : null,
            Pojos.readMessage(fields, 48) != null ? Next.pojo.ActorCompData_BornDieCtrler.parseFrom(Pojos.readMessage(fields, 48)) : null,
            Pojos.readMessage(fields, 49) != null ? Next.pojo.ActorCompData_Revive.parseFrom(Pojos.readMessage(fields, 49)) : null,
            Pojos.readMessage(fields, 50) != null ? Next.pojo.ActorCompData_LogicStatus.parseFrom(Pojos.readMessage(fields, 50)) : null,
            Pojos.readMessage(fields, 51) != null ? Next.pojo.ActorCompData_GameTime.parseFrom(Pojos.readMessage(fields, 51)) : null,
            Pojos.readMessage(fields, 52) != null ? Next.pojo.ActorCompData_AvatarCamp.parseFrom(Pojos.readMessage(fields, 52)) : null,
            Pojos.readMessage(fields, 53) != null ? Next.pojo.ActorCompData_Weather.parseFrom(Pojos.readMessage(fields, 53)) : null,
            Pojos.readMessage(fields, 54) != null ? Next.pojo.ActorCompData_Exchange.parseFrom(Pojos.readMessage(fields, 54)) : null,
            Pojos.readMessage(fields, 57) != null ? Next.pojo.ActorCompData_ActionBonus.parseFrom(Pojos.readMessage(fields, 57)) : null,
            Pojos.readMessage(fields, 59) != null ? Next.pojo.ActorCompData_ObjectAward.parseFrom(Pojos.readMessage(fields, 59)) : null,
            Pojos.readMessage(fields, 61) != null ? Next.pojo.ActorCompData_AreaDetector.parseFrom(Pojos.readMessage(fields, 61)) : null,
            Pojos.readMessage(fields, 62) != null ? Next.pojo.ActorCompData_Appearance.parseFrom(Pojos.readMessage(fields, 62)) : null,
            Pojos.readMessage(fields, 63) != null ? Next.pojo.ActorCompData_Dungeon.parseFrom(Pojos.readMessage(fields, 63)) : null,
            Pojos.readMessage(fields, 64) != null ? Next.pojo.ActorCompData_Visit.parseFrom(Pojos.readMessage(fields, 64)) : null,
            Pojos.readMessage(fields, 65) != null ? Next.pojo.ActorCompData_Pet.parseFrom(Pojos.readMessage(fields, 65)) : null,
            Pojos.readMessage(fields, 66) != null ? Next.pojo.ActorCompData_PetInteract.parseFrom(Pojos.readMessage(fields, 66)) : null,
            Pojos.readMessage(fields, 67) != null ? Next.pojo.ActorCompData_Buff.parseFrom(Pojos.readMessage(fields, 67)) : null,
            Pojos.readMessage(fields, 69) != null ? Next.pojo.ActorCompData_WorldCombat.parseFrom(Pojos.readMessage(fields, 69)) : null,
            Pojos.readMessage(fields, 70) != null ? Next.pojo.ActorCompData_WorldCombatSkill.parseFrom(Pojos.readMessage(fields, 70)) : null,
            Pojos.readMessage(fields, 71) != null ? Next.pojo.ActorCompData_InitAOIWaiter.parseFrom(Pojos.readMessage(fields, 71)) : null,
            Pojos.readMessage(fields, 72) != null ? Next.pojo.ActorCompData_VoicePlayer.parseFrom(Pojos.readMessage(fields, 72)) : null,
            Pojos.readMessage(fields, 99) != null ? Next.pojo.ActorCompData_ClientEvent.parseFrom(Pojos.readMessage(fields, 99)) : null,
            Pojos.readMessage(fields, 74) != null ? Next.pojo.ActorCompData_SceneRpcRetryMgr.parseFrom(Pojos.readMessage(fields, 74)) : null,
            Pojos.readMessage(fields, 75) != null ? Next.pojo.ActorCompData_PetPerception.parseFrom(Pojos.readMessage(fields, 75)) : null,
            Pojos.readMessage(fields, 76) != null ? Next.pojo.ActorCompData_NpcTaskProcessor.parseFrom(Pojos.readMessage(fields, 76)) : null,
            Pojos.readMessage(fields, 77) != null ? Next.pojo.ActorCompData_Activity.parseFrom(Pojos.readMessage(fields, 77)) : null,
            Pojos.readMessage(fields, 78) != null ? Next.pojo.ActorCompData_Trigger.parseFrom(Pojos.readMessage(fields, 78)) : null,
            Pojos.readMessage(fields, 79) != null ? Next.pojo.ActorCompData_DotsLabel.parseFrom(Pojos.readMessage(fields, 79)) : null,
            Pojos.readMessage(fields, 80) != null ? Next.pojo.ActorCompData_AOwlSanctuary.parseFrom(Pojos.readMessage(fields, 80)) : null,
            Pojos.readMessage(fields, 81) != null ? Next.pojo.ActorCompData_Follower.parseFrom(Pojos.readMessage(fields, 81)) : null,
            Pojos.readMessage(fields, 82) != null ? Next.pojo.ActorCompData_MsgRecover.parseFrom(Pojos.readMessage(fields, 82)) : null,
            Pojos.readMessage(fields, 83) != null ? Next.pojo.ActorCompData_Stamina.parseFrom(Pojos.readMessage(fields, 83)) : null,
            Pojos.readMessage(fields, 84) != null ? Next.pojo.ActorCompData_TaskState.parseFrom(Pojos.readMessage(fields, 84)) : null,
            Pojos.readMessage(fields, 85) != null ? Next.pojo.ActorCompData_AreaTrigger.parseFrom(Pojos.readMessage(fields, 85)) : null,
            Pojos.readMessage(fields, 86) != null ? Next.pojo.ActorCompData_CccChecker.parseFrom(Pojos.readMessage(fields, 86)) : null,
            Pojos.readMessage(fields, 87) != null ? Next.pojo.ActorCompData_DotsSkill.parseFrom(Pojos.readMessage(fields, 87)) : null,
            Pojos.readMessage(fields, 88) != null ? Next.pojo.ActorCompData_NpxCollision.parseFrom(Pojos.readMessage(fields, 88)) : null,
            Pojos.readMessage(fields, 89) != null ? Next.pojo.ActorCompData_Db.parseFrom(Pojos.readMessage(fields, 89)) : null,
            Pojos.readMessage(fields, 90) != null ? Next.pojo.ActorCompData_NpcTrace.parseFrom(Pojos.readMessage(fields, 90)) : null,
            Pojos.readMessage(fields, 91) != null ? Next.pojo.ActorCompData_AirWall.parseFrom(Pojos.readMessage(fields, 91)) : null,
            Pojos.readMessage(fields, 92) != null ? Next.pojo.ActorCompData_HomeBasic.parseFrom(Pojos.readMessage(fields, 92)) : null,
            Pojos.readMessage(fields, 93) != null ? Next.pojo.ActorCompData_HomePlant.parseFrom(Pojos.readMessage(fields, 93)) : null,
            Pojos.readMessage(fields, 94) != null ? Next.pojo.ActorCompData_TeamBattle.parseFrom(Pojos.readMessage(fields, 94)) : null,
            Pojos.readMessage(fields, 95) != null ? Next.pojo.ActorCompData_Feed.parseFrom(Pojos.readMessage(fields, 95)) : null,
            Pojos.readMessage(fields, 96) != null ? Next.pojo.ActorCompData_VisibleArea.parseFrom(Pojos.readMessage(fields, 96)) : null,
            Pojos.readMessage(fields, 97) != null ? Next.pojo.ActorCompData_HomeInteract.parseFrom(Pojos.readMessage(fields, 97)) : null,
            Pojos.readMessage(fields, 98) != null ? Next.pojo.ActorCompData_RelationInteract.parseFrom(Pojos.readMessage(fields, 98)) : null,
            Pojos.readMessage(fields, 100) != null ? Next.pojo.ActorCompData_AvatarMultiChat.parseFrom(Pojos.readMessage(fields, 100)) : null,
            Pojos.readMessage(fields, 101) != null ? Next.pojo.ActorCompData_TravelingMerchant.parseFrom(Pojos.readMessage(fields, 101)) : null,
            Pojos.readMessage(fields, 102) != null ? Next.pojo.ActorCompData_Season.parseFrom(Pojos.readMessage(fields, 102)) : null,
            Pojos.readMessage(fields, 103) != null ? Next.pojo.ActorCompData_FusionOwlSanctuary.parseFrom(Pojos.readMessage(fields, 103)) : null,
            Pojos.readMessage(fields, 104) != null ? Next.pojo.ActorCompData_BagItem.parseFrom(Pojos.readMessage(fields, 104)) : null,
            Pojos.readMessage(fields, 105) != null ? Next.pojo.ActorCompData_BossFlowerSeed.parseFrom(Pojos.readMessage(fields, 105)) : null,
            Pojos.readMessage(fields, 106) != null ? Next.pojo.ActorCompData_AvatarFriendProxy.parseFrom(Pojos.readMessage(fields, 106)) : null,
            Pojos.readMessage(fields, 107) != null ? Next.pojo.ActorCompData_VisibleCircle.parseFrom(Pojos.readMessage(fields, 107)) : null,
            Pojos.readMessage(fields, 108) != null ? Next.pojo.ActorCompData_TeleportInfoHolder.parseFrom(Pojos.readMessage(fields, 108)) : null,
            Pojos.readMessage(fields, 109) != null ? Next.pojo.ActorCompData_CatchRefreshRecord.parseFrom(Pojos.readMessage(fields, 109)) : null,
            Pojos.readMessage(fields, 110) != null ? Next.pojo.ActorCompData_SocialInfoReporter.parseFrom(Pojos.readMessage(fields, 110)) : null,
            Pojos.readMessage(fields, 111) != null ? Next.pojo.ActorCompData_NpcGuard.parseFrom(Pojos.readMessage(fields, 111)) : null,
            Pojos.readMessage(fields, 112) != null ? Next.pojo.ActorCompData_NightMode.parseFrom(Pojos.readMessage(fields, 112)) : null
        );
    }
    public static ActorData_Avatar parseFrom(java.util.List<ProtoField> fields) {
        return new ActorData_Avatar(
            Pojos.readMessage(fields, 1) != null ? Next.pojo.ActorPartData_Base.parseFrom(Pojos.readMessage(fields, 1)) : null,
            Pojos.readMessage(fields, 2) != null ? Next.pojo.ActorPartData_AvatarBase.parseFrom(Pojos.readMessage(fields, 2)) : null,
            Pojos.readMessage(fields, 10) != null ? Next.pojo.SpaceObjPartData_InstalledComp.parseFrom(Pojos.readMessage(fields, 10)) : null,
            Pojos.readMessage(fields, 11) != null ? Next.pojo.ActorCompData_Test.parseFrom(Pojos.readMessage(fields, 11)) : null,
            Pojos.readMessage(fields, 12) != null ? Next.pojo.ActorCompData_Broadcaster.parseFrom(Pojos.readMessage(fields, 12)) : null,
            Pojos.readMessage(fields, 13) != null ? Next.pojo.ActorCompData_ClientMover.parseFrom(Pojos.readMessage(fields, 13)) : null,
            Pojos.readMessage(fields, 14) != null ? Next.pojo.ActorCompData_Owner.parseFrom(Pojos.readMessage(fields, 14)) : null,
            Pojos.readMessage(fields, 15) != null ? Next.pojo.ActorCompData_Transform.parseFrom(Pojos.readMessage(fields, 15)) : null,
            Pojos.readMessage(fields, 16) != null ? Next.pojo.ActorCompData_StatusGuarder.parseFrom(Pojos.readMessage(fields, 16)) : null,
            Pojos.readMessage(fields, 17) != null ? Next.pojo.ActorCompData_AttrMgr.parseFrom(Pojos.readMessage(fields, 17)) : null,
            Pojos.readMessage(fields, 19) != null ? Next.pojo.ActorCompData_AnimSkillPlayer.parseFrom(Pojos.readMessage(fields, 19)) : null,
            Pojos.readMessage(fields, 22) != null ? Next.pojo.ActorCompData_NpxCapsuleCCT.parseFrom(Pojos.readMessage(fields, 22)) : null,
            Pojos.readMessage(fields, 23) != null ? Next.pojo.ActorCompData_Heartbeat.parseFrom(Pojos.readMessage(fields, 23)) : null,
            Pojos.readMessage(fields, 24) != null ? Next.pojo.ActorCompData_Skill.parseFrom(Pojos.readMessage(fields, 24)) : null,
            Pojos.readMessage(fields, 25) != null ? Next.pojo.ActorCompData_Battle.parseFrom(Pojos.readMessage(fields, 25)) : null,
            Pojos.readMessage(fields, 26) != null ? Next.pojo.ActorCompData_Minigame.parseFrom(Pojos.readMessage(fields, 26)) : null,
            Pojos.readMessage(fields, 27) != null ? Next.pojo.ActorCompData_MsgSender.parseFrom(Pojos.readMessage(fields, 27)) : null,
            Pojos.readMessage(fields, 28) != null ? Next.pojo.ActorCompData_AreaMgr.parseFrom(Pojos.readMessage(fields, 28)) : null,
            Pojos.readMessage(fields, 29) != null ? Next.pojo.ActorCompData_NpcRefresher.parseFrom(Pojos.readMessage(fields, 29)) : null,
            Pojos.readMessage(fields, 30) != null ? Next.pojo.ActorCompData_StoryFlag.parseFrom(Pojos.readMessage(fields, 30)) : null,
            Pojos.readMessage(fields, 31) != null ? Next.pojo.ActorCompData_Task.parseFrom(Pojos.readMessage(fields, 31)) : null,
            Pojos.readMessage(fields, 32) != null ? Next.pojo.ActorCompData_AvatarMisc.parseFrom(Pojos.readMessage(fields, 32)) : null,
            Pojos.readMessage(fields, 33) != null ? Next.pojo.ActorCompData_AI.parseFrom(Pojos.readMessage(fields, 33)) : null,
            Pojos.readMessage(fields, 34) != null ? Next.pojo.ActorCompData_AI_LOD.parseFrom(Pojos.readMessage(fields, 34)) : null,
            Pojos.readMessage(fields, 35) != null ? Next.pojo.ActorCompData_CombineNpc.parseFrom(Pojos.readMessage(fields, 35)) : null,
            Pojos.readMessage(fields, 36) != null ? Next.pojo.ActorCompData_Rider.parseFrom(Pojos.readMessage(fields, 36)) : null,
            Pojos.readMessage(fields, 18) != null ? Next.pojo.ActorCompData_Navigator.parseFrom(Pojos.readMessage(fields, 18)) : null,
            Pojos.readMessage(fields, 37) != null ? Next.pojo.ActorCompData_AuraMgr.parseFrom(Pojos.readMessage(fields, 37)) : null,
            Pojos.readMessage(fields, 38) != null ? Next.pojo.ActorCompData_AvatarInteractor.parseFrom(Pojos.readMessage(fields, 38)) : null,
            Pojos.readMessage(fields, 39) != null ? Next.pojo.ActorCompData_NonAvatarIdGen.parseFrom(Pojos.readMessage(fields, 39)) : null,
            Pojos.readMessage(fields, 40) != null ? Next.pojo.ActorCompData_NpcInstantiator.parseFrom(Pojos.readMessage(fields, 40)) : null,
            Pojos.readMessage(fields, 42) != null ? Next.pojo.ActorCompData_Thrower.parseFrom(Pojos.readMessage(fields, 42)) : null,
            Pojos.readMessage(fields, 43) != null ? Next.pojo.ActorCompData_WorldMap.parseFrom(Pojos.readMessage(fields, 43)) : null,
            Pojos.readMessage(fields, 44) != null ? Next.pojo.ActorCompData_Temperature.parseFrom(Pojos.readMessage(fields, 44)) : null,
            Pojos.readMessage(fields, 46) != null ? Next.pojo.ActorCompData_AvatarAI.parseFrom(Pojos.readMessage(fields, 46)) : null,
            Pojos.readMessage(fields, 47) != null ? Next.pojo.ActorCompData_ActionTag.parseFrom(Pojos.readMessage(fields, 47)) : null,
            Pojos.readMessage(fields, 48) != null ? Next.pojo.ActorCompData_BornDieCtrler.parseFrom(Pojos.readMessage(fields, 48)) : null,
            Pojos.readMessage(fields, 49) != null ? Next.pojo.ActorCompData_Revive.parseFrom(Pojos.readMessage(fields, 49)) : null,
            Pojos.readMessage(fields, 50) != null ? Next.pojo.ActorCompData_LogicStatus.parseFrom(Pojos.readMessage(fields, 50)) : null,
            Pojos.readMessage(fields, 51) != null ? Next.pojo.ActorCompData_GameTime.parseFrom(Pojos.readMessage(fields, 51)) : null,
            Pojos.readMessage(fields, 52) != null ? Next.pojo.ActorCompData_AvatarCamp.parseFrom(Pojos.readMessage(fields, 52)) : null,
            Pojos.readMessage(fields, 53) != null ? Next.pojo.ActorCompData_Weather.parseFrom(Pojos.readMessage(fields, 53)) : null,
            Pojos.readMessage(fields, 54) != null ? Next.pojo.ActorCompData_Exchange.parseFrom(Pojos.readMessage(fields, 54)) : null,
            Pojos.readMessage(fields, 57) != null ? Next.pojo.ActorCompData_ActionBonus.parseFrom(Pojos.readMessage(fields, 57)) : null,
            Pojos.readMessage(fields, 59) != null ? Next.pojo.ActorCompData_ObjectAward.parseFrom(Pojos.readMessage(fields, 59)) : null,
            Pojos.readMessage(fields, 61) != null ? Next.pojo.ActorCompData_AreaDetector.parseFrom(Pojos.readMessage(fields, 61)) : null,
            Pojos.readMessage(fields, 62) != null ? Next.pojo.ActorCompData_Appearance.parseFrom(Pojos.readMessage(fields, 62)) : null,
            Pojos.readMessage(fields, 63) != null ? Next.pojo.ActorCompData_Dungeon.parseFrom(Pojos.readMessage(fields, 63)) : null,
            Pojos.readMessage(fields, 64) != null ? Next.pojo.ActorCompData_Visit.parseFrom(Pojos.readMessage(fields, 64)) : null,
            Pojos.readMessage(fields, 65) != null ? Next.pojo.ActorCompData_Pet.parseFrom(Pojos.readMessage(fields, 65)) : null,
            Pojos.readMessage(fields, 66) != null ? Next.pojo.ActorCompData_PetInteract.parseFrom(Pojos.readMessage(fields, 66)) : null,
            Pojos.readMessage(fields, 67) != null ? Next.pojo.ActorCompData_Buff.parseFrom(Pojos.readMessage(fields, 67)) : null,
            Pojos.readMessage(fields, 69) != null ? Next.pojo.ActorCompData_WorldCombat.parseFrom(Pojos.readMessage(fields, 69)) : null,
            Pojos.readMessage(fields, 70) != null ? Next.pojo.ActorCompData_WorldCombatSkill.parseFrom(Pojos.readMessage(fields, 70)) : null,
            Pojos.readMessage(fields, 71) != null ? Next.pojo.ActorCompData_InitAOIWaiter.parseFrom(Pojos.readMessage(fields, 71)) : null,
            Pojos.readMessage(fields, 72) != null ? Next.pojo.ActorCompData_VoicePlayer.parseFrom(Pojos.readMessage(fields, 72)) : null,
            Pojos.readMessage(fields, 99) != null ? Next.pojo.ActorCompData_ClientEvent.parseFrom(Pojos.readMessage(fields, 99)) : null,
            Pojos.readMessage(fields, 74) != null ? Next.pojo.ActorCompData_SceneRpcRetryMgr.parseFrom(Pojos.readMessage(fields, 74)) : null,
            Pojos.readMessage(fields, 75) != null ? Next.pojo.ActorCompData_PetPerception.parseFrom(Pojos.readMessage(fields, 75)) : null,
            Pojos.readMessage(fields, 76) != null ? Next.pojo.ActorCompData_NpcTaskProcessor.parseFrom(Pojos.readMessage(fields, 76)) : null,
            Pojos.readMessage(fields, 77) != null ? Next.pojo.ActorCompData_Activity.parseFrom(Pojos.readMessage(fields, 77)) : null,
            Pojos.readMessage(fields, 78) != null ? Next.pojo.ActorCompData_Trigger.parseFrom(Pojos.readMessage(fields, 78)) : null,
            Pojos.readMessage(fields, 79) != null ? Next.pojo.ActorCompData_DotsLabel.parseFrom(Pojos.readMessage(fields, 79)) : null,
            Pojos.readMessage(fields, 80) != null ? Next.pojo.ActorCompData_AOwlSanctuary.parseFrom(Pojos.readMessage(fields, 80)) : null,
            Pojos.readMessage(fields, 81) != null ? Next.pojo.ActorCompData_Follower.parseFrom(Pojos.readMessage(fields, 81)) : null,
            Pojos.readMessage(fields, 82) != null ? Next.pojo.ActorCompData_MsgRecover.parseFrom(Pojos.readMessage(fields, 82)) : null,
            Pojos.readMessage(fields, 83) != null ? Next.pojo.ActorCompData_Stamina.parseFrom(Pojos.readMessage(fields, 83)) : null,
            Pojos.readMessage(fields, 84) != null ? Next.pojo.ActorCompData_TaskState.parseFrom(Pojos.readMessage(fields, 84)) : null,
            Pojos.readMessage(fields, 85) != null ? Next.pojo.ActorCompData_AreaTrigger.parseFrom(Pojos.readMessage(fields, 85)) : null,
            Pojos.readMessage(fields, 86) != null ? Next.pojo.ActorCompData_CccChecker.parseFrom(Pojos.readMessage(fields, 86)) : null,
            Pojos.readMessage(fields, 87) != null ? Next.pojo.ActorCompData_DotsSkill.parseFrom(Pojos.readMessage(fields, 87)) : null,
            Pojos.readMessage(fields, 88) != null ? Next.pojo.ActorCompData_NpxCollision.parseFrom(Pojos.readMessage(fields, 88)) : null,
            Pojos.readMessage(fields, 89) != null ? Next.pojo.ActorCompData_Db.parseFrom(Pojos.readMessage(fields, 89)) : null,
            Pojos.readMessage(fields, 90) != null ? Next.pojo.ActorCompData_NpcTrace.parseFrom(Pojos.readMessage(fields, 90)) : null,
            Pojos.readMessage(fields, 91) != null ? Next.pojo.ActorCompData_AirWall.parseFrom(Pojos.readMessage(fields, 91)) : null,
            Pojos.readMessage(fields, 92) != null ? Next.pojo.ActorCompData_HomeBasic.parseFrom(Pojos.readMessage(fields, 92)) : null,
            Pojos.readMessage(fields, 93) != null ? Next.pojo.ActorCompData_HomePlant.parseFrom(Pojos.readMessage(fields, 93)) : null,
            Pojos.readMessage(fields, 94) != null ? Next.pojo.ActorCompData_TeamBattle.parseFrom(Pojos.readMessage(fields, 94)) : null,
            Pojos.readMessage(fields, 95) != null ? Next.pojo.ActorCompData_Feed.parseFrom(Pojos.readMessage(fields, 95)) : null,
            Pojos.readMessage(fields, 96) != null ? Next.pojo.ActorCompData_VisibleArea.parseFrom(Pojos.readMessage(fields, 96)) : null,
            Pojos.readMessage(fields, 97) != null ? Next.pojo.ActorCompData_HomeInteract.parseFrom(Pojos.readMessage(fields, 97)) : null,
            Pojos.readMessage(fields, 98) != null ? Next.pojo.ActorCompData_RelationInteract.parseFrom(Pojos.readMessage(fields, 98)) : null,
            Pojos.readMessage(fields, 100) != null ? Next.pojo.ActorCompData_AvatarMultiChat.parseFrom(Pojos.readMessage(fields, 100)) : null,
            Pojos.readMessage(fields, 101) != null ? Next.pojo.ActorCompData_TravelingMerchant.parseFrom(Pojos.readMessage(fields, 101)) : null,
            Pojos.readMessage(fields, 102) != null ? Next.pojo.ActorCompData_Season.parseFrom(Pojos.readMessage(fields, 102)) : null,
            Pojos.readMessage(fields, 103) != null ? Next.pojo.ActorCompData_FusionOwlSanctuary.parseFrom(Pojos.readMessage(fields, 103)) : null,
            Pojos.readMessage(fields, 104) != null ? Next.pojo.ActorCompData_BagItem.parseFrom(Pojos.readMessage(fields, 104)) : null,
            Pojos.readMessage(fields, 105) != null ? Next.pojo.ActorCompData_BossFlowerSeed.parseFrom(Pojos.readMessage(fields, 105)) : null,
            Pojos.readMessage(fields, 106) != null ? Next.pojo.ActorCompData_AvatarFriendProxy.parseFrom(Pojos.readMessage(fields, 106)) : null,
            Pojos.readMessage(fields, 107) != null ? Next.pojo.ActorCompData_VisibleCircle.parseFrom(Pojos.readMessage(fields, 107)) : null,
            Pojos.readMessage(fields, 108) != null ? Next.pojo.ActorCompData_TeleportInfoHolder.parseFrom(Pojos.readMessage(fields, 108)) : null,
            Pojos.readMessage(fields, 109) != null ? Next.pojo.ActorCompData_CatchRefreshRecord.parseFrom(Pojos.readMessage(fields, 109)) : null,
            Pojos.readMessage(fields, 110) != null ? Next.pojo.ActorCompData_SocialInfoReporter.parseFrom(Pojos.readMessage(fields, 110)) : null,
            Pojos.readMessage(fields, 111) != null ? Next.pojo.ActorCompData_NpcGuard.parseFrom(Pojos.readMessage(fields, 111)) : null,
            Pojos.readMessage(fields, 112) != null ? Next.pojo.ActorCompData_NightMode.parseFrom(Pojos.readMessage(fields, 112)) : null
        );
    }
}
