// Generated from space_data.proto
package Next.pojo;

import com.roco.sniffer.codec.Pojos;
import com.roco.sniffer.codec.ProtoParser.ProtoField;
import com.roco.sniffer.codec.ProtoParser;

@SuppressWarnings("unused")
public record ActorData_Npc(
    ActorPartData_Base base,
    ActorPartData_NpcBase npcBase,
    ActorPartData_DropItem dropItemData,
    ActorPartData_Trigger triggerData,
    SpaceObjPartData_InstalledComp installedComps,
    ActorCompData_Test compDataTest,
    ActorCompData_Broadcaster compDataBroadcaster,
    ActorCompData_Owner compDataOwner,
    ActorCompData_Transform compDataTransform,
    ActorCompData_StatusGuarder compDataStatusGuarder,
    ActorCompData_AttrMgr compDataAttrMgr,
    ActorCompData_Navigator compDataNavigator,
    ActorCompData_AnimSkillPlayer compDataAnimSkillPlayer,
    ActorCompData_NpxCapsuleCCT compDataCapsuleCct,
    ActorCompData_Skill compDataSkill,
    ActorCompData_ActionTag compActionTag,
    ActorCompData_NpcInteractor compDataNpcInteractor,
    ActorCompData_NpcMisc compDataNpcMisc,
    ActorCompData_AI compDataAi,
    ActorCompData_PotentialEnergy compDataPotentialEnergy,
    ActorCompData_NpcCamp compDataNpcCamp,
    ActorCompData_ServerMover compDataMover,
    ActorCompData_BornDieCtrler compBornDieCtrler,
    ActorCompData_LogicStatus compLogicStatus,
    ActorCompData_NpcPendantMgr compDataNpcPendantMgr,
    ActorCompData_Hidden compHidden,
    ActorCompData_WorldAttack compWorldAttack,
    ActorCompData_Buff compDataBuff,
    ActorCompData_WorldCombat compDataWorldCombat,
    ActorCompData_VoicePlayer compDataVoicePlayer,
    ActorCompData_OwlSanctuary compDataOwlSanctuary,
    ActorCompData_DotsLabel compDataDotsLabel,
    ActorCompData_DotsSkill compDataDotsSkill,
    ActorCompData_WorldCombatSkill compDataWorldCombatSkill,
    ActorCompData_NpxCollision compDataCollision,
    ActorCompData_DotsSkillBullet compDataBullet,
    ActorCompData_HomePet compDataHomePet,
    ActorCompData_HomePlantNpc compDataHomePlantNpc,
    ActorCompData_HomePetEgg compDataHomePetEgg,
    ActorCompData_NpcBattle compDataNpcBattle
) {
    public static ActorData_Npc parseFrom(byte[] data) {
        java.util.List<ProtoField> fields = ProtoParser.parse(data);
        return new ActorData_Npc(
            Pojos.readMessage(fields, 1) != null ? Next.pojo.ActorPartData_Base.parseFrom(Pojos.readMessage(fields, 1)) : null,
            Pojos.readMessage(fields, 2) != null ? Next.pojo.ActorPartData_NpcBase.parseFrom(Pojos.readMessage(fields, 2)) : null,
            Pojos.readMessage(fields, 6) != null ? Next.pojo.ActorPartData_DropItem.parseFrom(Pojos.readMessage(fields, 6)) : null,
            Pojos.readMessage(fields, 7) != null ? Next.pojo.ActorPartData_Trigger.parseFrom(Pojos.readMessage(fields, 7)) : null,
            Pojos.readMessage(fields, 10) != null ? Next.pojo.SpaceObjPartData_InstalledComp.parseFrom(Pojos.readMessage(fields, 10)) : null,
            Pojos.readMessage(fields, 11) != null ? Next.pojo.ActorCompData_Test.parseFrom(Pojos.readMessage(fields, 11)) : null,
            Pojos.readMessage(fields, 12) != null ? Next.pojo.ActorCompData_Broadcaster.parseFrom(Pojos.readMessage(fields, 12)) : null,
            Pojos.readMessage(fields, 14) != null ? Next.pojo.ActorCompData_Owner.parseFrom(Pojos.readMessage(fields, 14)) : null,
            Pojos.readMessage(fields, 15) != null ? Next.pojo.ActorCompData_Transform.parseFrom(Pojos.readMessage(fields, 15)) : null,
            Pojos.readMessage(fields, 16) != null ? Next.pojo.ActorCompData_StatusGuarder.parseFrom(Pojos.readMessage(fields, 16)) : null,
            Pojos.readMessage(fields, 17) != null ? Next.pojo.ActorCompData_AttrMgr.parseFrom(Pojos.readMessage(fields, 17)) : null,
            Pojos.readMessage(fields, 18) != null ? Next.pojo.ActorCompData_Navigator.parseFrom(Pojos.readMessage(fields, 18)) : null,
            Pojos.readMessage(fields, 19) != null ? Next.pojo.ActorCompData_AnimSkillPlayer.parseFrom(Pojos.readMessage(fields, 19)) : null,
            Pojos.readMessage(fields, 21) != null ? Next.pojo.ActorCompData_NpxCapsuleCCT.parseFrom(Pojos.readMessage(fields, 21)) : null,
            Pojos.readMessage(fields, 22) != null ? Next.pojo.ActorCompData_Skill.parseFrom(Pojos.readMessage(fields, 22)) : null,
            Pojos.readMessage(fields, 23) != null ? Next.pojo.ActorCompData_ActionTag.parseFrom(Pojos.readMessage(fields, 23)) : null,
            Pojos.readMessage(fields, 24) != null ? Next.pojo.ActorCompData_NpcInteractor.parseFrom(Pojos.readMessage(fields, 24)) : null,
            Pojos.readMessage(fields, 25) != null ? Next.pojo.ActorCompData_NpcMisc.parseFrom(Pojos.readMessage(fields, 25)) : null,
            Pojos.readMessage(fields, 26) != null ? Next.pojo.ActorCompData_AI.parseFrom(Pojos.readMessage(fields, 26)) : null,
            Pojos.readMessage(fields, 27) != null ? Next.pojo.ActorCompData_PotentialEnergy.parseFrom(Pojos.readMessage(fields, 27)) : null,
            Pojos.readMessage(fields, 28) != null ? Next.pojo.ActorCompData_NpcCamp.parseFrom(Pojos.readMessage(fields, 28)) : null,
            Pojos.readMessage(fields, 29) != null ? Next.pojo.ActorCompData_ServerMover.parseFrom(Pojos.readMessage(fields, 29)) : null,
            Pojos.readMessage(fields, 30) != null ? Next.pojo.ActorCompData_BornDieCtrler.parseFrom(Pojos.readMessage(fields, 30)) : null,
            Pojos.readMessage(fields, 31) != null ? Next.pojo.ActorCompData_LogicStatus.parseFrom(Pojos.readMessage(fields, 31)) : null,
            Pojos.readMessage(fields, 32) != null ? Next.pojo.ActorCompData_NpcPendantMgr.parseFrom(Pojos.readMessage(fields, 32)) : null,
            Pojos.readMessage(fields, 34) != null ? Next.pojo.ActorCompData_Hidden.parseFrom(Pojos.readMessage(fields, 34)) : null,
            Pojos.readMessage(fields, 35) != null ? Next.pojo.ActorCompData_WorldAttack.parseFrom(Pojos.readMessage(fields, 35)) : null,
            Pojos.readMessage(fields, 36) != null ? Next.pojo.ActorCompData_Buff.parseFrom(Pojos.readMessage(fields, 36)) : null,
            Pojos.readMessage(fields, 37) != null ? Next.pojo.ActorCompData_WorldCombat.parseFrom(Pojos.readMessage(fields, 37)) : null,
            Pojos.readMessage(fields, 38) != null ? Next.pojo.ActorCompData_VoicePlayer.parseFrom(Pojos.readMessage(fields, 38)) : null,
            Pojos.readMessage(fields, 39) != null ? Next.pojo.ActorCompData_OwlSanctuary.parseFrom(Pojos.readMessage(fields, 39)) : null,
            Pojos.readMessage(fields, 41) != null ? Next.pojo.ActorCompData_DotsLabel.parseFrom(Pojos.readMessage(fields, 41)) : null,
            Pojos.readMessage(fields, 42) != null ? Next.pojo.ActorCompData_DotsSkill.parseFrom(Pojos.readMessage(fields, 42)) : null,
            Pojos.readMessage(fields, 43) != null ? Next.pojo.ActorCompData_WorldCombatSkill.parseFrom(Pojos.readMessage(fields, 43)) : null,
            Pojos.readMessage(fields, 44) != null ? Next.pojo.ActorCompData_NpxCollision.parseFrom(Pojos.readMessage(fields, 44)) : null,
            Pojos.readMessage(fields, 45) != null ? Next.pojo.ActorCompData_DotsSkillBullet.parseFrom(Pojos.readMessage(fields, 45)) : null,
            Pojos.readMessage(fields, 46) != null ? Next.pojo.ActorCompData_HomePet.parseFrom(Pojos.readMessage(fields, 46)) : null,
            Pojos.readMessage(fields, 47) != null ? Next.pojo.ActorCompData_HomePlantNpc.parseFrom(Pojos.readMessage(fields, 47)) : null,
            Pojos.readMessage(fields, 48) != null ? Next.pojo.ActorCompData_HomePetEgg.parseFrom(Pojos.readMessage(fields, 48)) : null,
            Pojos.readMessage(fields, 49) != null ? Next.pojo.ActorCompData_NpcBattle.parseFrom(Pojos.readMessage(fields, 49)) : null
        );
    }
    public static ActorData_Npc parseFrom(java.util.List<ProtoField> fields) {
        return new ActorData_Npc(
            Pojos.readMessage(fields, 1) != null ? Next.pojo.ActorPartData_Base.parseFrom(Pojos.readMessage(fields, 1)) : null,
            Pojos.readMessage(fields, 2) != null ? Next.pojo.ActorPartData_NpcBase.parseFrom(Pojos.readMessage(fields, 2)) : null,
            Pojos.readMessage(fields, 6) != null ? Next.pojo.ActorPartData_DropItem.parseFrom(Pojos.readMessage(fields, 6)) : null,
            Pojos.readMessage(fields, 7) != null ? Next.pojo.ActorPartData_Trigger.parseFrom(Pojos.readMessage(fields, 7)) : null,
            Pojos.readMessage(fields, 10) != null ? Next.pojo.SpaceObjPartData_InstalledComp.parseFrom(Pojos.readMessage(fields, 10)) : null,
            Pojos.readMessage(fields, 11) != null ? Next.pojo.ActorCompData_Test.parseFrom(Pojos.readMessage(fields, 11)) : null,
            Pojos.readMessage(fields, 12) != null ? Next.pojo.ActorCompData_Broadcaster.parseFrom(Pojos.readMessage(fields, 12)) : null,
            Pojos.readMessage(fields, 14) != null ? Next.pojo.ActorCompData_Owner.parseFrom(Pojos.readMessage(fields, 14)) : null,
            Pojos.readMessage(fields, 15) != null ? Next.pojo.ActorCompData_Transform.parseFrom(Pojos.readMessage(fields, 15)) : null,
            Pojos.readMessage(fields, 16) != null ? Next.pojo.ActorCompData_StatusGuarder.parseFrom(Pojos.readMessage(fields, 16)) : null,
            Pojos.readMessage(fields, 17) != null ? Next.pojo.ActorCompData_AttrMgr.parseFrom(Pojos.readMessage(fields, 17)) : null,
            Pojos.readMessage(fields, 18) != null ? Next.pojo.ActorCompData_Navigator.parseFrom(Pojos.readMessage(fields, 18)) : null,
            Pojos.readMessage(fields, 19) != null ? Next.pojo.ActorCompData_AnimSkillPlayer.parseFrom(Pojos.readMessage(fields, 19)) : null,
            Pojos.readMessage(fields, 21) != null ? Next.pojo.ActorCompData_NpxCapsuleCCT.parseFrom(Pojos.readMessage(fields, 21)) : null,
            Pojos.readMessage(fields, 22) != null ? Next.pojo.ActorCompData_Skill.parseFrom(Pojos.readMessage(fields, 22)) : null,
            Pojos.readMessage(fields, 23) != null ? Next.pojo.ActorCompData_ActionTag.parseFrom(Pojos.readMessage(fields, 23)) : null,
            Pojos.readMessage(fields, 24) != null ? Next.pojo.ActorCompData_NpcInteractor.parseFrom(Pojos.readMessage(fields, 24)) : null,
            Pojos.readMessage(fields, 25) != null ? Next.pojo.ActorCompData_NpcMisc.parseFrom(Pojos.readMessage(fields, 25)) : null,
            Pojos.readMessage(fields, 26) != null ? Next.pojo.ActorCompData_AI.parseFrom(Pojos.readMessage(fields, 26)) : null,
            Pojos.readMessage(fields, 27) != null ? Next.pojo.ActorCompData_PotentialEnergy.parseFrom(Pojos.readMessage(fields, 27)) : null,
            Pojos.readMessage(fields, 28) != null ? Next.pojo.ActorCompData_NpcCamp.parseFrom(Pojos.readMessage(fields, 28)) : null,
            Pojos.readMessage(fields, 29) != null ? Next.pojo.ActorCompData_ServerMover.parseFrom(Pojos.readMessage(fields, 29)) : null,
            Pojos.readMessage(fields, 30) != null ? Next.pojo.ActorCompData_BornDieCtrler.parseFrom(Pojos.readMessage(fields, 30)) : null,
            Pojos.readMessage(fields, 31) != null ? Next.pojo.ActorCompData_LogicStatus.parseFrom(Pojos.readMessage(fields, 31)) : null,
            Pojos.readMessage(fields, 32) != null ? Next.pojo.ActorCompData_NpcPendantMgr.parseFrom(Pojos.readMessage(fields, 32)) : null,
            Pojos.readMessage(fields, 34) != null ? Next.pojo.ActorCompData_Hidden.parseFrom(Pojos.readMessage(fields, 34)) : null,
            Pojos.readMessage(fields, 35) != null ? Next.pojo.ActorCompData_WorldAttack.parseFrom(Pojos.readMessage(fields, 35)) : null,
            Pojos.readMessage(fields, 36) != null ? Next.pojo.ActorCompData_Buff.parseFrom(Pojos.readMessage(fields, 36)) : null,
            Pojos.readMessage(fields, 37) != null ? Next.pojo.ActorCompData_WorldCombat.parseFrom(Pojos.readMessage(fields, 37)) : null,
            Pojos.readMessage(fields, 38) != null ? Next.pojo.ActorCompData_VoicePlayer.parseFrom(Pojos.readMessage(fields, 38)) : null,
            Pojos.readMessage(fields, 39) != null ? Next.pojo.ActorCompData_OwlSanctuary.parseFrom(Pojos.readMessage(fields, 39)) : null,
            Pojos.readMessage(fields, 41) != null ? Next.pojo.ActorCompData_DotsLabel.parseFrom(Pojos.readMessage(fields, 41)) : null,
            Pojos.readMessage(fields, 42) != null ? Next.pojo.ActorCompData_DotsSkill.parseFrom(Pojos.readMessage(fields, 42)) : null,
            Pojos.readMessage(fields, 43) != null ? Next.pojo.ActorCompData_WorldCombatSkill.parseFrom(Pojos.readMessage(fields, 43)) : null,
            Pojos.readMessage(fields, 44) != null ? Next.pojo.ActorCompData_NpxCollision.parseFrom(Pojos.readMessage(fields, 44)) : null,
            Pojos.readMessage(fields, 45) != null ? Next.pojo.ActorCompData_DotsSkillBullet.parseFrom(Pojos.readMessage(fields, 45)) : null,
            Pojos.readMessage(fields, 46) != null ? Next.pojo.ActorCompData_HomePet.parseFrom(Pojos.readMessage(fields, 46)) : null,
            Pojos.readMessage(fields, 47) != null ? Next.pojo.ActorCompData_HomePlantNpc.parseFrom(Pojos.readMessage(fields, 47)) : null,
            Pojos.readMessage(fields, 48) != null ? Next.pojo.ActorCompData_HomePetEgg.parseFrom(Pojos.readMessage(fields, 48)) : null,
            Pojos.readMessage(fields, 49) != null ? Next.pojo.ActorCompData_NpcBattle.parseFrom(Pojos.readMessage(fields, 49)) : null
        );
    }
}
