// Generated from battle_data.proto
package Next.pojo;

import io.github.kedaya0209.roco.sniffer.codec.Pojos;
import io.github.kedaya0209.roco.sniffer.codec.ProtoParser.ProtoField;
import io.github.kedaya0209.roco.sniffer.codec.ProtoParser;
import java.util.List;

@SuppressWarnings("unused")
public record BattleInsidePetInfo(
    int petId,
    int pos,
    List<BattleBuffInfo> buffs,
    List<Integer> battleAttr,
    List<Integer> stateBits,
    List<PetSkillRoundData> skillRoundData,
    BattleMonsterEscapeInfo escapeInfo,
    BattleMonsterCatchInfo catchInfo,
    BattleAIInitInfo aiInfo,
    Position position,
    List<EnvEnergyInfo> spEnergy,
    int envEnjoyHate,
    List<Integer> enjoyHateBuffEx,
    List<Integer> enjoyHateBuffExStack,
    List<Integer> envEnjoyHateBuff,
    List<BattleAISelectSkillInfo> aiSkillInfo,
    int confId,
    int baseConfId,
    byte[] name,
    int cheersTag,
    int enterIndex,
    BattlePetHabitInfo habitInfo,
    BattleInstantKillInfo killInfo,
    List<Integer> extraResistType,
    int inBattleRound,
    int counterRound,
    int reviveRound,
    int reviveRounds,
    int chargingSkillId,
    long lastCatchTime,
    int catchGuaranteeRate,
    long npcObjId,
    List<BattleBuffBrefInfo> remainBuffInfos,
    int nightmareEliteId,
    List<ExtraSdtInfo> extraSdt,
    int blowPos,
    boolean isPlayerEnemy,
    int replacePetId,
    int medalConfId,
    int medalCompleteCnt,
    int petChangeStatus,
    SkillBuffInfo skillBuff,
    List<Integer> dotSuckEffect,
    int lastHurtRound,
    int skillNum,
    int maxEnergy,
    List<Integer> changedAttr,
    int deadRound,
    int deadCnt,
    int refreshContentId,
    int lastPos,
    int bossBloodOldId,
    List<Integer> usingBuffs,
    int bossBloodId,
    boolean isProtected,
    List<PetSkillRoundData> swapSkillsBak,
    int curPassiveSkill,
    List<BuffData_93_Skill> triggeredBuffs,
    boolean isB93Active,
    List<Integer> hasFastSkillPets,
    int aiEvPetbaseId,
    PetAdditionalNewAttrList battleFinalAttr,
    boolean isEntered,
    int speedMin,
    int speedMax,
    List<PetSkillRoundData> usedOriginalSkill,
    Position lastPosition,
    TerritoryTrialPetInfo trialPetInfo,
    int ownerUin,
    int lastUpRound,
    int lastDownRound,
    FeatureResonance featureResonance,
    int chargingSkillEnergy,
    int height,
    int weight
) {
    public static BattleInsidePetInfo parseFrom(byte[] data) {
        java.util.List<ProtoField> fields = ProtoParser.parse(data);
        return new BattleInsidePetInfo(
            Pojos.readInt(fields, 1),
            Pojos.readInt(fields, 2),
            Pojos.readMessageList(fields, 5).stream().map(Next.pojo.BattleBuffInfo::parseFrom).toList(),
            Pojos.readIntList(fields, 6),
            Pojos.readIntList(fields, 24),
            Pojos.readMessageList(fields, 8).stream().map(Next.pojo.PetSkillRoundData::parseFrom).toList(),
            Pojos.readMessage(fields, 9) != null ? Next.pojo.BattleMonsterEscapeInfo.parseFrom(Pojos.readMessage(fields, 9)) : null,
            Pojos.readMessage(fields, 10) != null ? Next.pojo.BattleMonsterCatchInfo.parseFrom(Pojos.readMessage(fields, 10)) : null,
            Pojos.readMessage(fields, 13) != null ? Next.pojo.BattleAIInitInfo.parseFrom(Pojos.readMessage(fields, 13)) : null,
            Pojos.readMessage(fields, 14) != null ? Next.pojo.Position.parseFrom(Pojos.readMessage(fields, 14)) : null,
            Pojos.readMessageList(fields, 15).stream().map(Next.pojo.EnvEnergyInfo::parseFrom).toList(),
            Pojos.readInt(fields, 16),
            Pojos.readIntList(fields, 17),
            Pojos.readIntList(fields, 18),
            Pojos.readIntList(fields, 19),
            Pojos.readMessageList(fields, 20).stream().map(Next.pojo.BattleAISelectSkillInfo::parseFrom).toList(),
            Pojos.readInt(fields, 21),
            Pojos.readInt(fields, 22),
            Pojos.readBytes(fields, 23),
            Pojos.readInt(fields, 25),
            Pojos.readInt(fields, 27),
            Pojos.readMessage(fields, 28) != null ? Next.pojo.BattlePetHabitInfo.parseFrom(Pojos.readMessage(fields, 28)) : null,
            Pojos.readMessage(fields, 29) != null ? Next.pojo.BattleInstantKillInfo.parseFrom(Pojos.readMessage(fields, 29)) : null,
            Pojos.readIntList(fields, 30),
            Pojos.readInt(fields, 31),
            Pojos.readInt(fields, 32),
            Pojos.readInt(fields, 33),
            Pojos.readInt(fields, 34),
            Pojos.readInt(fields, 35),
            Pojos.readLong(fields, 36),
            Pojos.readInt(fields, 37),
            Pojos.readLong(fields, 38),
            Pojos.readMessageList(fields, 39).stream().map(Next.pojo.BattleBuffBrefInfo::parseFrom).toList(),
            Pojos.readInt(fields, 40),
            Pojos.readMessageList(fields, 41).stream().map(Next.pojo.ExtraSdtInfo::parseFrom).toList(),
            Pojos.readInt(fields, 42),
            Pojos.readBool(fields, 43),
            Pojos.readInt(fields, 44),
            Pojos.readInt(fields, 45),
            Pojos.readInt(fields, 46),
            Pojos.readInt(fields, 47, 0),
            Pojos.readMessage(fields, 48) != null ? Next.pojo.SkillBuffInfo.parseFrom(Pojos.readMessage(fields, 48)) : null,
            Pojos.readIntList(fields, 49),
            Pojos.readInt(fields, 51),
            Pojos.readInt(fields, 52),
            Pojos.readInt(fields, 53),
            Pojos.readIntList(fields, 54),
            Pojos.readInt(fields, 55),
            Pojos.readInt(fields, 56),
            Pojos.readInt(fields, 57),
            Pojos.readInt(fields, 58),
            Pojos.readInt(fields, 59),
            Pojos.readIntList(fields, 60),
            Pojos.readInt(fields, 61),
            Pojos.readBool(fields, 62),
            Pojos.readMessageList(fields, 63).stream().map(Next.pojo.PetSkillRoundData::parseFrom).toList(),
            Pojos.readInt(fields, 64),
            Pojos.readMessageList(fields, 65).stream().map(Next.pojo.BuffData_93_Skill::parseFrom).toList(),
            Pojos.readBool(fields, 66),
            Pojos.readIntList(fields, 67),
            Pojos.readInt(fields, 68),
            Pojos.readMessage(fields, 69) != null ? Next.pojo.PetAdditionalNewAttrList.parseFrom(Pojos.readMessage(fields, 69)) : null,
            Pojos.readBool(fields, 70),
            Pojos.readInt(fields, 71),
            Pojos.readInt(fields, 72),
            Pojos.readMessageList(fields, 73).stream().map(Next.pojo.PetSkillRoundData::parseFrom).toList(),
            Pojos.readMessage(fields, 74) != null ? Next.pojo.Position.parseFrom(Pojos.readMessage(fields, 74)) : null,
            Pojos.readMessage(fields, 75) != null ? Next.pojo.TerritoryTrialPetInfo.parseFrom(Pojos.readMessage(fields, 75)) : null,
            Pojos.readInt(fields, 77),
            Pojos.readInt(fields, 78),
            Pojos.readInt(fields, 79),
            Pojos.readMessage(fields, 80) != null ? Next.pojo.FeatureResonance.parseFrom(Pojos.readMessage(fields, 80)) : null,
            Pojos.readInt(fields, 82),
            Pojos.readInt(fields, 83),
            Pojos.readInt(fields, 84)
        );
    }
    public static BattleInsidePetInfo parseFrom(java.util.List<ProtoField> fields) {
        return new BattleInsidePetInfo(
            Pojos.readInt(fields, 1),
            Pojos.readInt(fields, 2),
            Pojos.readMessageList(fields, 5).stream().map(Next.pojo.BattleBuffInfo::parseFrom).toList(),
            Pojos.readIntList(fields, 6),
            Pojos.readIntList(fields, 24),
            Pojos.readMessageList(fields, 8).stream().map(Next.pojo.PetSkillRoundData::parseFrom).toList(),
            Pojos.readMessage(fields, 9) != null ? Next.pojo.BattleMonsterEscapeInfo.parseFrom(Pojos.readMessage(fields, 9)) : null,
            Pojos.readMessage(fields, 10) != null ? Next.pojo.BattleMonsterCatchInfo.parseFrom(Pojos.readMessage(fields, 10)) : null,
            Pojos.readMessage(fields, 13) != null ? Next.pojo.BattleAIInitInfo.parseFrom(Pojos.readMessage(fields, 13)) : null,
            Pojos.readMessage(fields, 14) != null ? Next.pojo.Position.parseFrom(Pojos.readMessage(fields, 14)) : null,
            Pojos.readMessageList(fields, 15).stream().map(Next.pojo.EnvEnergyInfo::parseFrom).toList(),
            Pojos.readInt(fields, 16),
            Pojos.readIntList(fields, 17),
            Pojos.readIntList(fields, 18),
            Pojos.readIntList(fields, 19),
            Pojos.readMessageList(fields, 20).stream().map(Next.pojo.BattleAISelectSkillInfo::parseFrom).toList(),
            Pojos.readInt(fields, 21),
            Pojos.readInt(fields, 22),
            Pojos.readBytes(fields, 23),
            Pojos.readInt(fields, 25),
            Pojos.readInt(fields, 27),
            Pojos.readMessage(fields, 28) != null ? Next.pojo.BattlePetHabitInfo.parseFrom(Pojos.readMessage(fields, 28)) : null,
            Pojos.readMessage(fields, 29) != null ? Next.pojo.BattleInstantKillInfo.parseFrom(Pojos.readMessage(fields, 29)) : null,
            Pojos.readIntList(fields, 30),
            Pojos.readInt(fields, 31),
            Pojos.readInt(fields, 32),
            Pojos.readInt(fields, 33),
            Pojos.readInt(fields, 34),
            Pojos.readInt(fields, 35),
            Pojos.readLong(fields, 36),
            Pojos.readInt(fields, 37),
            Pojos.readLong(fields, 38),
            Pojos.readMessageList(fields, 39).stream().map(Next.pojo.BattleBuffBrefInfo::parseFrom).toList(),
            Pojos.readInt(fields, 40),
            Pojos.readMessageList(fields, 41).stream().map(Next.pojo.ExtraSdtInfo::parseFrom).toList(),
            Pojos.readInt(fields, 42),
            Pojos.readBool(fields, 43),
            Pojos.readInt(fields, 44),
            Pojos.readInt(fields, 45),
            Pojos.readInt(fields, 46),
            Pojos.readInt(fields, 47, 0),
            Pojos.readMessage(fields, 48) != null ? Next.pojo.SkillBuffInfo.parseFrom(Pojos.readMessage(fields, 48)) : null,
            Pojos.readIntList(fields, 49),
            Pojos.readInt(fields, 51),
            Pojos.readInt(fields, 52),
            Pojos.readInt(fields, 53),
            Pojos.readIntList(fields, 54),
            Pojos.readInt(fields, 55),
            Pojos.readInt(fields, 56),
            Pojos.readInt(fields, 57),
            Pojos.readInt(fields, 58),
            Pojos.readInt(fields, 59),
            Pojos.readIntList(fields, 60),
            Pojos.readInt(fields, 61),
            Pojos.readBool(fields, 62),
            Pojos.readMessageList(fields, 63).stream().map(Next.pojo.PetSkillRoundData::parseFrom).toList(),
            Pojos.readInt(fields, 64),
            Pojos.readMessageList(fields, 65).stream().map(Next.pojo.BuffData_93_Skill::parseFrom).toList(),
            Pojos.readBool(fields, 66),
            Pojos.readIntList(fields, 67),
            Pojos.readInt(fields, 68),
            Pojos.readMessage(fields, 69) != null ? Next.pojo.PetAdditionalNewAttrList.parseFrom(Pojos.readMessage(fields, 69)) : null,
            Pojos.readBool(fields, 70),
            Pojos.readInt(fields, 71),
            Pojos.readInt(fields, 72),
            Pojos.readMessageList(fields, 73).stream().map(Next.pojo.PetSkillRoundData::parseFrom).toList(),
            Pojos.readMessage(fields, 74) != null ? Next.pojo.Position.parseFrom(Pojos.readMessage(fields, 74)) : null,
            Pojos.readMessage(fields, 75) != null ? Next.pojo.TerritoryTrialPetInfo.parseFrom(Pojos.readMessage(fields, 75)) : null,
            Pojos.readInt(fields, 77),
            Pojos.readInt(fields, 78),
            Pojos.readInt(fields, 79),
            Pojos.readMessage(fields, 80) != null ? Next.pojo.FeatureResonance.parseFrom(Pojos.readMessage(fields, 80)) : null,
            Pojos.readInt(fields, 82),
            Pojos.readInt(fields, 83),
            Pojos.readInt(fields, 84)
        );
    }
}
