// Generated from battle_data.proto
package Next.pojo;

import com.roco.sniffer.codec.Pojos;
import com.roco.sniffer.codec.ProtoParser.ProtoField;
import com.roco.sniffer.codec.ProtoParser;
import java.util.List;

@SuppressWarnings("unused")
public record BattleRoleBaseInfo(
    int roleUin,
    byte[] name,
    int pos,
    int catchCounts,
    byte[] seenMonsterBits,
    List<Integer> npcLevel,
    int roleLevel,
    int rawHp,
    int hp,
    int cfgLimitHp,
    int modHp,
    int rawHpMax,
    int stateBit,
    int pvpScore,
    int worldLevel,
    List<Integer> firstSeenPets,
    int npcId,
    int legendSkillCastNum,
    int blackHp,
    int battleHpMax,
    boolean needSupplyPet,
    int side,
    int sex,
    int mateFriNum,
    int enemyFriNum,
    List<Integer> validShinyCatchUins,
    List<Integer> friUinList,
    boolean isVisiting,
    int visitOwnerUin,
    String visitOwnerName,
    Position scenePos,
    long sceneObjId,
    int doubleInteract,
    int rideId,
    int seasonAdvProbAdd,
    List<Inner_FriendTypeInfo> friTypeList,
    long roleAvatarId,
    boolean freeCatch
) {
    public static BattleRoleBaseInfo parseFrom(byte[] data) {
        java.util.List<ProtoField> fields = ProtoParser.parse(data);
        return new BattleRoleBaseInfo(
            Pojos.readInt(fields, 1),
            Pojos.readBytes(fields, 2),
            Pojos.readInt(fields, 6),
            Pojos.readInt(fields, 7),
            Pojos.readBytes(fields, 11),
            Pojos.readIntList(fields, 12),
            Pojos.readInt(fields, 14),
            Pojos.readInt(fields, 17),
            Pojos.readInt(fields, 18),
            Pojos.readInt(fields, 19),
            Pojos.readInt(fields, 20),
            Pojos.readInt(fields, 21),
            Pojos.readInt(fields, 22),
            Pojos.readInt(fields, 23),
            Pojos.readInt(fields, 24),
            Pojos.readIntList(fields, 5),
            Pojos.readInt(fields, 25),
            Pojos.readInt(fields, 26),
            Pojos.readInt(fields, 28),
            Pojos.readInt(fields, 29),
            Pojos.readBool(fields, 30),
            Pojos.readInt(fields, 31),
            Pojos.readInt(fields, 32),
            Pojos.readInt(fields, 33),
            Pojos.readInt(fields, 34),
            Pojos.readIntList(fields, 35),
            Pojos.readIntList(fields, 36),
            Pojos.readBool(fields, 37),
            Pojos.readInt(fields, 38),
            Pojos.readString(fields, 39),
            Pojos.readMessage(fields, 40) != null ? Next.pojo.Position.parseFrom(Pojos.readMessage(fields, 40)) : null,
            Pojos.readLong(fields, 41),
            Pojos.readInt(fields, 42),
            Pojos.readInt(fields, 43),
            Pojos.readInt(fields, 44),
            Pojos.readMessageList(fields, 45).stream().map(Next.pojo.Inner_FriendTypeInfo::parseFrom).toList(),
            Pojos.readLong(fields, 46),
            Pojos.readBool(fields, 47)
        );
    }
    public static BattleRoleBaseInfo parseFrom(java.util.List<ProtoField> fields) {
        return new BattleRoleBaseInfo(
            Pojos.readInt(fields, 1),
            Pojos.readBytes(fields, 2),
            Pojos.readInt(fields, 6),
            Pojos.readInt(fields, 7),
            Pojos.readBytes(fields, 11),
            Pojos.readIntList(fields, 12),
            Pojos.readInt(fields, 14),
            Pojos.readInt(fields, 17),
            Pojos.readInt(fields, 18),
            Pojos.readInt(fields, 19),
            Pojos.readInt(fields, 20),
            Pojos.readInt(fields, 21),
            Pojos.readInt(fields, 22),
            Pojos.readInt(fields, 23),
            Pojos.readInt(fields, 24),
            Pojos.readIntList(fields, 5),
            Pojos.readInt(fields, 25),
            Pojos.readInt(fields, 26),
            Pojos.readInt(fields, 28),
            Pojos.readInt(fields, 29),
            Pojos.readBool(fields, 30),
            Pojos.readInt(fields, 31),
            Pojos.readInt(fields, 32),
            Pojos.readInt(fields, 33),
            Pojos.readInt(fields, 34),
            Pojos.readIntList(fields, 35),
            Pojos.readIntList(fields, 36),
            Pojos.readBool(fields, 37),
            Pojos.readInt(fields, 38),
            Pojos.readString(fields, 39),
            Pojos.readMessage(fields, 40) != null ? Next.pojo.Position.parseFrom(Pojos.readMessage(fields, 40)) : null,
            Pojos.readLong(fields, 41),
            Pojos.readInt(fields, 42),
            Pojos.readInt(fields, 43),
            Pojos.readInt(fields, 44),
            Pojos.readMessageList(fields, 45).stream().map(Next.pojo.Inner_FriendTypeInfo::parseFrom).toList(),
            Pojos.readLong(fields, 46),
            Pojos.readBool(fields, 47)
        );
    }
}
