// Generated from com_battle.proto
package Next.pojo;

import com.roco.sniffer.codec.Pojos;
import com.roco.sniffer.codec.ProtoParser.ProtoField;
import com.roco.sniffer.codec.ProtoParser;
import java.util.List;

@SuppressWarnings("unused")
public record BattleSettleInfo(
    int battleConfType,
    int battleOppositeType,
    int realPve,
    int realPvp,
    PvpModeCtl pvpMode,
    int flowerNpcLevel,
    int result,
    int battleConfId,
    List<BattleMonsterInfo> monsterInfo,
    long interactNpcId,
    int escapeStyle,
    List<SkillRecord> skillRecords,
    List<EffectRecord> effectRecords,
    int modHp,
    boolean isSurrender,
    long battleId,
    List<BattlerSettleInfo> battlerInfo,
    BattlerUinBrief uinBrief,
    int battleRefreshContent,
    int guideType,
    int killPetNum,
    BattleAiStats aiStatsInfo,
    List<CostlyReward> costlyReward,
    boolean isReward,
    byte[] visitOwnerName,
    boolean isInDungeon,
    BattlePveInfo pveAddInfo,
    int interactNpcContentId,
    boolean pkAgain,
    boolean isBadgeChallenge,
    boolean isFirstSettle,
    int retreatPetCnt,
    List<MagicUsedInfo> magicUsed,
    int side,
    int rounds,
    int seconds,
    int rideId,
    List<PetCatchInfo> catchInfo,
    BattleSettleInfo_DoubleInteract doubleInteract,
    boolean dailyPvpFirstWin,
    List<InnerBattleTask> battleTasks,
    int battleDifficultId,
    TerritoryTrialSettleInfo trialSettleInfo,
    int enterBattleTime
) {
    public static BattleSettleInfo parseFrom(byte[] data) {
        java.util.List<ProtoField> fields = ProtoParser.parse(data);
        return new BattleSettleInfo(
            Pojos.readInt(fields, 1),
            Pojos.readInt(fields, 2),
            Pojos.readInt(fields, 3),
            Pojos.readInt(fields, 4),
            Pojos.readMessage(fields, 5) != null ? Next.pojo.PvpModeCtl.parseFrom(Pojos.readMessage(fields, 5)) : null,
            Pojos.readInt(fields, 17),
            Pojos.readInt(fields, 6, 0),
            Pojos.readInt(fields, 7),
            Pojos.readMessageList(fields, 8).stream().map(Next.pojo.BattleMonsterInfo::parseFrom).toList(),
            Pojos.readLong(fields, 9),
            Pojos.readInt(fields, 10),
            Pojos.readMessageList(fields, 11).stream().map(Next.pojo.SkillRecord::parseFrom).toList(),
            Pojos.readMessageList(fields, 12).stream().map(Next.pojo.EffectRecord::parseFrom).toList(),
            Pojos.readInt(fields, 13),
            Pojos.readBool(fields, 14),
            Pojos.readLong(fields, 19),
            Pojos.readMessageList(fields, 16).stream().map(Next.pojo.BattlerSettleInfo::parseFrom).toList(),
            Pojos.readMessage(fields, 30) != null ? Next.pojo.BattlerUinBrief.parseFrom(Pojos.readMessage(fields, 30)) : null,
            Pojos.readInt(fields, 20),
            Pojos.readInt(fields, 21),
            Pojos.readInt(fields, 22),
            Pojos.readMessage(fields, 23) != null ? Next.pojo.BattleAiStats.parseFrom(Pojos.readMessage(fields, 23)) : null,
            Pojos.readMessageList(fields, 24).stream().map(Next.pojo.CostlyReward::parseFrom).toList(),
            Pojos.readBool(fields, 25),
            Pojos.readBytes(fields, 26),
            Pojos.readBool(fields, 27),
            Pojos.readMessage(fields, 28) != null ? Next.pojo.BattlePveInfo.parseFrom(Pojos.readMessage(fields, 28)) : null,
            Pojos.readInt(fields, 29),
            Pojos.readBool(fields, 31),
            Pojos.readBool(fields, 32),
            Pojos.readBool(fields, 33),
            Pojos.readInt(fields, 34),
            Pojos.readMessageList(fields, 35).stream().map(Next.pojo.MagicUsedInfo::parseFrom).toList(),
            Pojos.readInt(fields, 36),
            Pojos.readInt(fields, 37),
            Pojos.readInt(fields, 38),
            Pojos.readInt(fields, 40),
            Pojos.readMessageList(fields, 41).stream().map(Next.pojo.PetCatchInfo::parseFrom).toList(),
            Pojos.readMessage(fields, 42) != null ? Next.pojo.BattleSettleInfo_DoubleInteract.parseFrom(Pojos.readMessage(fields, 42)) : null,
            Pojos.readBool(fields, 43),
            Pojos.readMessageList(fields, 44).stream().map(Next.pojo.InnerBattleTask::parseFrom).toList(),
            Pojos.readInt(fields, 45),
            Pojos.readMessage(fields, 46) != null ? Next.pojo.TerritoryTrialSettleInfo.parseFrom(Pojos.readMessage(fields, 46)) : null,
            Pojos.readInt(fields, 47)
        );
    }
    public static BattleSettleInfo parseFrom(java.util.List<ProtoField> fields) {
        return new BattleSettleInfo(
            Pojos.readInt(fields, 1),
            Pojos.readInt(fields, 2),
            Pojos.readInt(fields, 3),
            Pojos.readInt(fields, 4),
            Pojos.readMessage(fields, 5) != null ? Next.pojo.PvpModeCtl.parseFrom(Pojos.readMessage(fields, 5)) : null,
            Pojos.readInt(fields, 17),
            Pojos.readInt(fields, 6, 0),
            Pojos.readInt(fields, 7),
            Pojos.readMessageList(fields, 8).stream().map(Next.pojo.BattleMonsterInfo::parseFrom).toList(),
            Pojos.readLong(fields, 9),
            Pojos.readInt(fields, 10),
            Pojos.readMessageList(fields, 11).stream().map(Next.pojo.SkillRecord::parseFrom).toList(),
            Pojos.readMessageList(fields, 12).stream().map(Next.pojo.EffectRecord::parseFrom).toList(),
            Pojos.readInt(fields, 13),
            Pojos.readBool(fields, 14),
            Pojos.readLong(fields, 19),
            Pojos.readMessageList(fields, 16).stream().map(Next.pojo.BattlerSettleInfo::parseFrom).toList(),
            Pojos.readMessage(fields, 30) != null ? Next.pojo.BattlerUinBrief.parseFrom(Pojos.readMessage(fields, 30)) : null,
            Pojos.readInt(fields, 20),
            Pojos.readInt(fields, 21),
            Pojos.readInt(fields, 22),
            Pojos.readMessage(fields, 23) != null ? Next.pojo.BattleAiStats.parseFrom(Pojos.readMessage(fields, 23)) : null,
            Pojos.readMessageList(fields, 24).stream().map(Next.pojo.CostlyReward::parseFrom).toList(),
            Pojos.readBool(fields, 25),
            Pojos.readBytes(fields, 26),
            Pojos.readBool(fields, 27),
            Pojos.readMessage(fields, 28) != null ? Next.pojo.BattlePveInfo.parseFrom(Pojos.readMessage(fields, 28)) : null,
            Pojos.readInt(fields, 29),
            Pojos.readBool(fields, 31),
            Pojos.readBool(fields, 32),
            Pojos.readBool(fields, 33),
            Pojos.readInt(fields, 34),
            Pojos.readMessageList(fields, 35).stream().map(Next.pojo.MagicUsedInfo::parseFrom).toList(),
            Pojos.readInt(fields, 36),
            Pojos.readInt(fields, 37),
            Pojos.readInt(fields, 38),
            Pojos.readInt(fields, 40),
            Pojos.readMessageList(fields, 41).stream().map(Next.pojo.PetCatchInfo::parseFrom).toList(),
            Pojos.readMessage(fields, 42) != null ? Next.pojo.BattleSettleInfo_DoubleInteract.parseFrom(Pojos.readMessage(fields, 42)) : null,
            Pojos.readBool(fields, 43),
            Pojos.readMessageList(fields, 44).stream().map(Next.pojo.InnerBattleTask::parseFrom).toList(),
            Pojos.readInt(fields, 45),
            Pojos.readMessage(fields, 46) != null ? Next.pojo.TerritoryTrialSettleInfo.parseFrom(Pojos.readMessage(fields, 46)) : null,
            Pojos.readInt(fields, 47)
        );
    }
}
