// Generated from com_battle.proto
package Next.pojo;

import io.github.kedaya0209.roco.sniffer.codec.Pojos;
import io.github.kedaya0209.roco.sniffer.codec.ProtoParser.ProtoField;
import io.github.kedaya0209.roco.sniffer.codec.ProtoParser;
import java.util.List;

@SuppressWarnings("unused")
public record BattleMonsterInfo(
    int state,
    int level,
    int petGid,
    int catchedUin,
    PetData caughtMonster,
    int killedUin,
    boolean sleep,
    boolean worldHide,
    boolean battled,
    int confId,
    int petbaseId,
    int uin,
    boolean oriBackOfHead,
    long oriAiStatus,
    long npcObjId,
    int killedPetGid,
    List<Integer> killedPetType,
    int remainHp,
    int maxHp,
    long lastCatchTime,
    int catchGuaranteeRate,
    List<BattleBuffBrefInfo> remainBuffInfos,
    int damageOut,
    int rawSkillDamageTaken,
    byte[] petOwnerName,
    byte[] petName,
    int mutationType,
    int lowestHp,
    List<PetSkillRecord> skillRecords,
    int killedSeq,
    int side,
    List<Integer> caughtWithUins,
    List<BattleMedalInfo> medalCondComplete,
    List<Integer> killNewEvoChain,
    boolean inBattleWhenFinish,
    PetMedalConditionData petMedalCondData,
    GlassInfo glassInfo,
    int petId
) {
    public static BattleMonsterInfo parseFrom(byte[] data) {
        java.util.List<ProtoField> fields = ProtoParser.parse(data);
        return new BattleMonsterInfo(
            Pojos.readInt(fields, 2, 0),
            Pojos.readInt(fields, 3),
            Pojos.readInt(fields, 4),
            Pojos.readInt(fields, 5),
            Pojos.readMessage(fields, 6) != null ? Next.pojo.PetData.parseFrom(Pojos.readMessage(fields, 6)) : null,
            Pojos.readInt(fields, 7),
            Pojos.readBool(fields, 8),
            Pojos.readBool(fields, 9),
            Pojos.readBool(fields, 10),
            Pojos.readInt(fields, 11),
            Pojos.readInt(fields, 12),
            Pojos.readInt(fields, 13),
            Pojos.readBool(fields, 14),
            Pojos.readLong(fields, 15),
            Pojos.readLong(fields, 16),
            Pojos.readInt(fields, 17),
            Pojos.readIntList(fields, 18),
            Pojos.readInt(fields, 19),
            Pojos.readInt(fields, 20),
            Pojos.readLong(fields, 21),
            Pojos.readInt(fields, 22),
            Pojos.readMessageList(fields, 23).stream().map(Next.pojo.BattleBuffBrefInfo::parseFrom).toList(),
            Pojos.readInt(fields, 24),
            Pojos.readInt(fields, 25),
            Pojos.readBytes(fields, 26),
            Pojos.readBytes(fields, 27),
            Pojos.readInt(fields, 28),
            Pojos.readInt(fields, 29),
            Pojos.readMessageList(fields, 30).stream().map(Next.pojo.PetSkillRecord::parseFrom).toList(),
            Pojos.readInt(fields, 31),
            Pojos.readInt(fields, 32),
            Pojos.readIntList(fields, 33),
            Pojos.readMessageList(fields, 34).stream().map(Next.pojo.BattleMedalInfo::parseFrom).toList(),
            Pojos.readIntList(fields, 35),
            Pojos.readBool(fields, 36),
            Pojos.readMessage(fields, 37) != null ? Next.pojo.PetMedalConditionData.parseFrom(Pojos.readMessage(fields, 37)) : null,
            Pojos.readMessage(fields, 38) != null ? Next.pojo.GlassInfo.parseFrom(Pojos.readMessage(fields, 38)) : null,
            Pojos.readInt(fields, 39)
        );
    }
    public static BattleMonsterInfo parseFrom(java.util.List<ProtoField> fields) {
        return new BattleMonsterInfo(
            Pojos.readInt(fields, 2, 0),
            Pojos.readInt(fields, 3),
            Pojos.readInt(fields, 4),
            Pojos.readInt(fields, 5),
            Pojos.readMessage(fields, 6) != null ? Next.pojo.PetData.parseFrom(Pojos.readMessage(fields, 6)) : null,
            Pojos.readInt(fields, 7),
            Pojos.readBool(fields, 8),
            Pojos.readBool(fields, 9),
            Pojos.readBool(fields, 10),
            Pojos.readInt(fields, 11),
            Pojos.readInt(fields, 12),
            Pojos.readInt(fields, 13),
            Pojos.readBool(fields, 14),
            Pojos.readLong(fields, 15),
            Pojos.readLong(fields, 16),
            Pojos.readInt(fields, 17),
            Pojos.readIntList(fields, 18),
            Pojos.readInt(fields, 19),
            Pojos.readInt(fields, 20),
            Pojos.readLong(fields, 21),
            Pojos.readInt(fields, 22),
            Pojos.readMessageList(fields, 23).stream().map(Next.pojo.BattleBuffBrefInfo::parseFrom).toList(),
            Pojos.readInt(fields, 24),
            Pojos.readInt(fields, 25),
            Pojos.readBytes(fields, 26),
            Pojos.readBytes(fields, 27),
            Pojos.readInt(fields, 28),
            Pojos.readInt(fields, 29),
            Pojos.readMessageList(fields, 30).stream().map(Next.pojo.PetSkillRecord::parseFrom).toList(),
            Pojos.readInt(fields, 31),
            Pojos.readInt(fields, 32),
            Pojos.readIntList(fields, 33),
            Pojos.readMessageList(fields, 34).stream().map(Next.pojo.BattleMedalInfo::parseFrom).toList(),
            Pojos.readIntList(fields, 35),
            Pojos.readBool(fields, 36),
            Pojos.readMessage(fields, 37) != null ? Next.pojo.PetMedalConditionData.parseFrom(Pojos.readMessage(fields, 37)) : null,
            Pojos.readMessage(fields, 38) != null ? Next.pojo.GlassInfo.parseFrom(Pojos.readMessage(fields, 38)) : null,
            Pojos.readInt(fields, 39)
        );
    }
}
