// Generated from battle_data.proto
package Next.pojo;

import com.roco.sniffer.codec.Pojos;
import com.roco.sniffer.codec.ProtoParser.ProtoField;
import com.roco.sniffer.codec.ProtoParser;

@SuppressWarnings("unused")
public record BattlePerformInfo(
    int type,
    int groupId,
    BattleSkillCast skillCast,
    BattleBuffChange buffChange,
    BattleBuffTrigger buffTrigger,
    BattleDamageInfo damageInfo,
    BattleHealInfo healInfo,
    BattleEnergyInfo energyInfo,
    BattleDeadInfo deadInfo,
    BattleReviveInfo reviveInfo,
    boolean isGroupHead,
    BattleSyncData syncData,
    BattleEffectTrigger effectTrigger,
    int castMoment,
    BattleShowLetters showLetters,
    BattleSpEnergyTrigger spEnergyTrigger,
    BattleSpEnergyChange spEnergyChange,
    BattleChangePet changePet,
    BattleUseItem useItem,
    BattleIdleInfo idleInfo,
    BattleMonsterCatchChange monsterCatchChange,
    BattleMonsterEscapeChange monsterEscapeChange,
    BattleCatchPetInfo catchPetInfo,
    BattleSkillStateInfo skillState,
    BattlePetEvolution petEvolution,
    int groupRef,
    boolean isLastHit,
    BattleSkillAura skillAura,
    BattleWeatherChange weatherChange,
    BattleNotifyPerform notifyPerform,
    BattleSpecialPerform specialPerform,
    BattleChangeModel changeModel,
    BattleAIPerform aiPerform,
    BattleCheersSwitch cheersSwitch,
    BattlePetEscape petEscape,
    BattleRoleSkillCast roleSkillCast,
    BattleComboSkillCast comboSkillCast,
    int execIndex,
    BattleCmdFailed cmdFailed,
    BattlerEscape battlerEscape,
    BattlerHealInfo battlerHealInfo,
    BattlerPvpPerform pvpPerform,
    BattleDataUpdate dataUpdate,
    BattleSupplyPetPlayerInfo supplyPet,
    BattleSkillPosChange skillPosChange,
    BattleSpecialMoveInfo specialMove,
    BattleRunawayInfo runaway,
    BattlePrepareToBattle prepareToBattle,
    BattleBagToPrepare bagToPrepare,
    BattleFeatureResonance featureResonance
) {
    public static BattlePerformInfo parseFrom(byte[] data) {
        java.util.List<ProtoField> fields = ProtoParser.parse(data);
        return new BattlePerformInfo(
            Pojos.readInt(fields, 1, 0),
            Pojos.readInt(fields, 2),
            Pojos.readMessage(fields, 3) != null ? Next.pojo.BattleSkillCast.parseFrom(Pojos.readMessage(fields, 3)) : null,
            Pojos.readMessage(fields, 4) != null ? Next.pojo.BattleBuffChange.parseFrom(Pojos.readMessage(fields, 4)) : null,
            Pojos.readMessage(fields, 5) != null ? Next.pojo.BattleBuffTrigger.parseFrom(Pojos.readMessage(fields, 5)) : null,
            Pojos.readMessage(fields, 6) != null ? Next.pojo.BattleDamageInfo.parseFrom(Pojos.readMessage(fields, 6)) : null,
            Pojos.readMessage(fields, 7) != null ? Next.pojo.BattleHealInfo.parseFrom(Pojos.readMessage(fields, 7)) : null,
            Pojos.readMessage(fields, 8) != null ? Next.pojo.BattleEnergyInfo.parseFrom(Pojos.readMessage(fields, 8)) : null,
            Pojos.readMessage(fields, 9) != null ? Next.pojo.BattleDeadInfo.parseFrom(Pojos.readMessage(fields, 9)) : null,
            Pojos.readMessage(fields, 10) != null ? Next.pojo.BattleReviveInfo.parseFrom(Pojos.readMessage(fields, 10)) : null,
            Pojos.readBool(fields, 11),
            Pojos.readMessage(fields, 12) != null ? Next.pojo.BattleSyncData.parseFrom(Pojos.readMessage(fields, 12)) : null,
            Pojos.readMessage(fields, 13) != null ? Next.pojo.BattleEffectTrigger.parseFrom(Pojos.readMessage(fields, 13)) : null,
            Pojos.readInt(fields, 14),
            Pojos.readMessage(fields, 15) != null ? Next.pojo.BattleShowLetters.parseFrom(Pojos.readMessage(fields, 15)) : null,
            Pojos.readMessage(fields, 16) != null ? Next.pojo.BattleSpEnergyTrigger.parseFrom(Pojos.readMessage(fields, 16)) : null,
            Pojos.readMessage(fields, 17) != null ? Next.pojo.BattleSpEnergyChange.parseFrom(Pojos.readMessage(fields, 17)) : null,
            Pojos.readMessage(fields, 18) != null ? Next.pojo.BattleChangePet.parseFrom(Pojos.readMessage(fields, 18)) : null,
            Pojos.readMessage(fields, 19) != null ? Next.pojo.BattleUseItem.parseFrom(Pojos.readMessage(fields, 19)) : null,
            Pojos.readMessage(fields, 20) != null ? Next.pojo.BattleIdleInfo.parseFrom(Pojos.readMessage(fields, 20)) : null,
            Pojos.readMessage(fields, 21) != null ? Next.pojo.BattleMonsterCatchChange.parseFrom(Pojos.readMessage(fields, 21)) : null,
            Pojos.readMessage(fields, 22) != null ? Next.pojo.BattleMonsterEscapeChange.parseFrom(Pojos.readMessage(fields, 22)) : null,
            Pojos.readMessage(fields, 23) != null ? Next.pojo.BattleCatchPetInfo.parseFrom(Pojos.readMessage(fields, 23)) : null,
            Pojos.readMessage(fields, 24) != null ? Next.pojo.BattleSkillStateInfo.parseFrom(Pojos.readMessage(fields, 24)) : null,
            Pojos.readMessage(fields, 25) != null ? Next.pojo.BattlePetEvolution.parseFrom(Pojos.readMessage(fields, 25)) : null,
            Pojos.readInt(fields, 26),
            Pojos.readBool(fields, 27),
            Pojos.readMessage(fields, 28) != null ? Next.pojo.BattleSkillAura.parseFrom(Pojos.readMessage(fields, 28)) : null,
            Pojos.readMessage(fields, 29) != null ? Next.pojo.BattleWeatherChange.parseFrom(Pojos.readMessage(fields, 29)) : null,
            Pojos.readMessage(fields, 30) != null ? Next.pojo.BattleNotifyPerform.parseFrom(Pojos.readMessage(fields, 30)) : null,
            Pojos.readMessage(fields, 31) != null ? Next.pojo.BattleSpecialPerform.parseFrom(Pojos.readMessage(fields, 31)) : null,
            Pojos.readMessage(fields, 32) != null ? Next.pojo.BattleChangeModel.parseFrom(Pojos.readMessage(fields, 32)) : null,
            Pojos.readMessage(fields, 33) != null ? Next.pojo.BattleAIPerform.parseFrom(Pojos.readMessage(fields, 33)) : null,
            Pojos.readMessage(fields, 35) != null ? Next.pojo.BattleCheersSwitch.parseFrom(Pojos.readMessage(fields, 35)) : null,
            Pojos.readMessage(fields, 36) != null ? Next.pojo.BattlePetEscape.parseFrom(Pojos.readMessage(fields, 36)) : null,
            Pojos.readMessage(fields, 37) != null ? Next.pojo.BattleRoleSkillCast.parseFrom(Pojos.readMessage(fields, 37)) : null,
            Pojos.readMessage(fields, 38) != null ? Next.pojo.BattleComboSkillCast.parseFrom(Pojos.readMessage(fields, 38)) : null,
            Pojos.readInt(fields, 39),
            Pojos.readMessage(fields, 40) != null ? Next.pojo.BattleCmdFailed.parseFrom(Pojos.readMessage(fields, 40)) : null,
            Pojos.readMessage(fields, 41) != null ? Next.pojo.BattlerEscape.parseFrom(Pojos.readMessage(fields, 41)) : null,
            Pojos.readMessage(fields, 42) != null ? Next.pojo.BattlerHealInfo.parseFrom(Pojos.readMessage(fields, 42)) : null,
            Pojos.readMessage(fields, 43) != null ? Next.pojo.BattlerPvpPerform.parseFrom(Pojos.readMessage(fields, 43)) : null,
            Pojos.readMessage(fields, 44) != null ? Next.pojo.BattleDataUpdate.parseFrom(Pojos.readMessage(fields, 44)) : null,
            Pojos.readMessage(fields, 45) != null ? Next.pojo.BattleSupplyPetPlayerInfo.parseFrom(Pojos.readMessage(fields, 45)) : null,
            Pojos.readMessage(fields, 46) != null ? Next.pojo.BattleSkillPosChange.parseFrom(Pojos.readMessage(fields, 46)) : null,
            Pojos.readMessage(fields, 47) != null ? Next.pojo.BattleSpecialMoveInfo.parseFrom(Pojos.readMessage(fields, 47)) : null,
            Pojos.readMessage(fields, 48) != null ? Next.pojo.BattleRunawayInfo.parseFrom(Pojos.readMessage(fields, 48)) : null,
            Pojos.readMessage(fields, 49) != null ? Next.pojo.BattlePrepareToBattle.parseFrom(Pojos.readMessage(fields, 49)) : null,
            Pojos.readMessage(fields, 50) != null ? Next.pojo.BattleBagToPrepare.parseFrom(Pojos.readMessage(fields, 50)) : null,
            Pojos.readMessage(fields, 51) != null ? Next.pojo.BattleFeatureResonance.parseFrom(Pojos.readMessage(fields, 51)) : null
        );
    }
    public static BattlePerformInfo parseFrom(java.util.List<ProtoField> fields) {
        return new BattlePerformInfo(
            Pojos.readInt(fields, 1, 0),
            Pojos.readInt(fields, 2),
            Pojos.readMessage(fields, 3) != null ? Next.pojo.BattleSkillCast.parseFrom(Pojos.readMessage(fields, 3)) : null,
            Pojos.readMessage(fields, 4) != null ? Next.pojo.BattleBuffChange.parseFrom(Pojos.readMessage(fields, 4)) : null,
            Pojos.readMessage(fields, 5) != null ? Next.pojo.BattleBuffTrigger.parseFrom(Pojos.readMessage(fields, 5)) : null,
            Pojos.readMessage(fields, 6) != null ? Next.pojo.BattleDamageInfo.parseFrom(Pojos.readMessage(fields, 6)) : null,
            Pojos.readMessage(fields, 7) != null ? Next.pojo.BattleHealInfo.parseFrom(Pojos.readMessage(fields, 7)) : null,
            Pojos.readMessage(fields, 8) != null ? Next.pojo.BattleEnergyInfo.parseFrom(Pojos.readMessage(fields, 8)) : null,
            Pojos.readMessage(fields, 9) != null ? Next.pojo.BattleDeadInfo.parseFrom(Pojos.readMessage(fields, 9)) : null,
            Pojos.readMessage(fields, 10) != null ? Next.pojo.BattleReviveInfo.parseFrom(Pojos.readMessage(fields, 10)) : null,
            Pojos.readBool(fields, 11),
            Pojos.readMessage(fields, 12) != null ? Next.pojo.BattleSyncData.parseFrom(Pojos.readMessage(fields, 12)) : null,
            Pojos.readMessage(fields, 13) != null ? Next.pojo.BattleEffectTrigger.parseFrom(Pojos.readMessage(fields, 13)) : null,
            Pojos.readInt(fields, 14),
            Pojos.readMessage(fields, 15) != null ? Next.pojo.BattleShowLetters.parseFrom(Pojos.readMessage(fields, 15)) : null,
            Pojos.readMessage(fields, 16) != null ? Next.pojo.BattleSpEnergyTrigger.parseFrom(Pojos.readMessage(fields, 16)) : null,
            Pojos.readMessage(fields, 17) != null ? Next.pojo.BattleSpEnergyChange.parseFrom(Pojos.readMessage(fields, 17)) : null,
            Pojos.readMessage(fields, 18) != null ? Next.pojo.BattleChangePet.parseFrom(Pojos.readMessage(fields, 18)) : null,
            Pojos.readMessage(fields, 19) != null ? Next.pojo.BattleUseItem.parseFrom(Pojos.readMessage(fields, 19)) : null,
            Pojos.readMessage(fields, 20) != null ? Next.pojo.BattleIdleInfo.parseFrom(Pojos.readMessage(fields, 20)) : null,
            Pojos.readMessage(fields, 21) != null ? Next.pojo.BattleMonsterCatchChange.parseFrom(Pojos.readMessage(fields, 21)) : null,
            Pojos.readMessage(fields, 22) != null ? Next.pojo.BattleMonsterEscapeChange.parseFrom(Pojos.readMessage(fields, 22)) : null,
            Pojos.readMessage(fields, 23) != null ? Next.pojo.BattleCatchPetInfo.parseFrom(Pojos.readMessage(fields, 23)) : null,
            Pojos.readMessage(fields, 24) != null ? Next.pojo.BattleSkillStateInfo.parseFrom(Pojos.readMessage(fields, 24)) : null,
            Pojos.readMessage(fields, 25) != null ? Next.pojo.BattlePetEvolution.parseFrom(Pojos.readMessage(fields, 25)) : null,
            Pojos.readInt(fields, 26),
            Pojos.readBool(fields, 27),
            Pojos.readMessage(fields, 28) != null ? Next.pojo.BattleSkillAura.parseFrom(Pojos.readMessage(fields, 28)) : null,
            Pojos.readMessage(fields, 29) != null ? Next.pojo.BattleWeatherChange.parseFrom(Pojos.readMessage(fields, 29)) : null,
            Pojos.readMessage(fields, 30) != null ? Next.pojo.BattleNotifyPerform.parseFrom(Pojos.readMessage(fields, 30)) : null,
            Pojos.readMessage(fields, 31) != null ? Next.pojo.BattleSpecialPerform.parseFrom(Pojos.readMessage(fields, 31)) : null,
            Pojos.readMessage(fields, 32) != null ? Next.pojo.BattleChangeModel.parseFrom(Pojos.readMessage(fields, 32)) : null,
            Pojos.readMessage(fields, 33) != null ? Next.pojo.BattleAIPerform.parseFrom(Pojos.readMessage(fields, 33)) : null,
            Pojos.readMessage(fields, 35) != null ? Next.pojo.BattleCheersSwitch.parseFrom(Pojos.readMessage(fields, 35)) : null,
            Pojos.readMessage(fields, 36) != null ? Next.pojo.BattlePetEscape.parseFrom(Pojos.readMessage(fields, 36)) : null,
            Pojos.readMessage(fields, 37) != null ? Next.pojo.BattleRoleSkillCast.parseFrom(Pojos.readMessage(fields, 37)) : null,
            Pojos.readMessage(fields, 38) != null ? Next.pojo.BattleComboSkillCast.parseFrom(Pojos.readMessage(fields, 38)) : null,
            Pojos.readInt(fields, 39),
            Pojos.readMessage(fields, 40) != null ? Next.pojo.BattleCmdFailed.parseFrom(Pojos.readMessage(fields, 40)) : null,
            Pojos.readMessage(fields, 41) != null ? Next.pojo.BattlerEscape.parseFrom(Pojos.readMessage(fields, 41)) : null,
            Pojos.readMessage(fields, 42) != null ? Next.pojo.BattlerHealInfo.parseFrom(Pojos.readMessage(fields, 42)) : null,
            Pojos.readMessage(fields, 43) != null ? Next.pojo.BattlerPvpPerform.parseFrom(Pojos.readMessage(fields, 43)) : null,
            Pojos.readMessage(fields, 44) != null ? Next.pojo.BattleDataUpdate.parseFrom(Pojos.readMessage(fields, 44)) : null,
            Pojos.readMessage(fields, 45) != null ? Next.pojo.BattleSupplyPetPlayerInfo.parseFrom(Pojos.readMessage(fields, 45)) : null,
            Pojos.readMessage(fields, 46) != null ? Next.pojo.BattleSkillPosChange.parseFrom(Pojos.readMessage(fields, 46)) : null,
            Pojos.readMessage(fields, 47) != null ? Next.pojo.BattleSpecialMoveInfo.parseFrom(Pojos.readMessage(fields, 47)) : null,
            Pojos.readMessage(fields, 48) != null ? Next.pojo.BattleRunawayInfo.parseFrom(Pojos.readMessage(fields, 48)) : null,
            Pojos.readMessage(fields, 49) != null ? Next.pojo.BattlePrepareToBattle.parseFrom(Pojos.readMessage(fields, 49)) : null,
            Pojos.readMessage(fields, 50) != null ? Next.pojo.BattleBagToPrepare.parseFrom(Pojos.readMessage(fields, 50)) : null,
            Pojos.readMessage(fields, 51) != null ? Next.pojo.BattleFeatureResonance.parseFrom(Pojos.readMessage(fields, 51)) : null
        );
    }
}
