// Generated from com_battle.proto
package Next.pojo;

import io.github.kedaya0209.roco.sniffer.codec.Pojos;
import io.github.kedaya0209.roco.sniffer.codec.ProtoParser.ProtoField;
import io.github.kedaya0209.roco.sniffer.codec.ProtoParser;
import java.util.List;

@SuppressWarnings("unused")
public record CreateBattleInfo(
    int battleConfId,
    int optionId,
    int battleType,
    List<PlayerZoneId> attackers,
    List<PlayerZoneId> defenders,
    Point avatarPt,
    Point npcPt,
    List<Long> npcObjId,
    int npcConfId,
    long npcLogicId,
    int npcRefreshConfId,
    int npcLevel,
    Position npcPos,
    Position npcBornPos,
    long aiStatus,
    int sleeping,
    boolean backOfHead,
    int newSkill,
    int preActTag,
    int preActParam,
    int randNum,
    int waterBattleType,
    PvpModeCtl pvpMode,
    Position battleCenter,
    int enterBattleType,
    int tod,
    List<BattleNpcInfo> npcInfos,
    MonsterDiffInfo monsterDiffInfo,
    List<OnlookerNpcInfo> onlookerNpcs,
    List<CheerMonsterInitInfo> cheerNpcInfo,
    List<Integer> monsterLeaderConfId,
    BloodPetFight bloodPetFight,
    BeastPetFight beastPetFight,
    WorldLeaderFight worldLeaderFight,
    BattlePveInfo pveAddInfo,
    List<WorldCombatExtraReward> worldCombatExtraRewardTypes,
    boolean isInDungeon,
    CreateBattleInfo_DoubleInteract doubleInteract,
    boolean delNpcAftWin,
    int battleRadius,
    int battleDifficultId,
    int uin,
    long bfid,
    long replayBfid,
    int roleLevel,
    List<MonsterCreateInfo> monsterInfo,
    int createrWorldLv,
    int rotate,
    List<PvpNpcInfo> pvpNpcs,
    int teamType,
    BadgeChallengeInfo badgeChallenge,
    List<GmBattleNpc> dynamicPveNpcs,
    PveSeasonInfo pveSeasonInfo,
    int battleGameTime,
    int startTime,
    int finalBattleSummonTime,
    boolean disableHpDec,
    boolean disableAntiCheat,
    boolean aiTraining,
    boolean guideBattle,
    List<Integer> monsterPetBaseIdList
) {
    public static CreateBattleInfo parseFrom(byte[] data) {
        java.util.List<ProtoField> fields = ProtoParser.parse(data);
        return new CreateBattleInfo(
            Pojos.readInt(fields, 1),
            Pojos.readInt(fields, 2),
            Pojos.readInt(fields, 3),
            Pojos.readMessageList(fields, 4).stream().map(Next.pojo.PlayerZoneId::parseFrom).toList(),
            Pojos.readMessageList(fields, 5).stream().map(Next.pojo.PlayerZoneId::parseFrom).toList(),
            Pojos.readMessage(fields, 6) != null ? Next.pojo.Point.parseFrom(Pojos.readMessage(fields, 6)) : null,
            Pojos.readMessage(fields, 7) != null ? Next.pojo.Point.parseFrom(Pojos.readMessage(fields, 7)) : null,
            Pojos.readLongList(fields, 8),
            Pojos.readInt(fields, 9),
            Pojos.readLong(fields, 10),
            Pojos.readInt(fields, 11),
            Pojos.readInt(fields, 12),
            Pojos.readMessage(fields, 13) != null ? Next.pojo.Position.parseFrom(Pojos.readMessage(fields, 13)) : null,
            Pojos.readMessage(fields, 14) != null ? Next.pojo.Position.parseFrom(Pojos.readMessage(fields, 14)) : null,
            Pojos.readLong(fields, 15),
            Pojos.readInt(fields, 16),
            Pojos.readBool(fields, 17),
            Pojos.readInt(fields, 18),
            Pojos.readInt(fields, 19),
            Pojos.readInt(fields, 20),
            Pojos.readInt(fields, 21),
            Pojos.readInt(fields, 22),
            Pojos.readMessage(fields, 23) != null ? Next.pojo.PvpModeCtl.parseFrom(Pojos.readMessage(fields, 23)) : null,
            Pojos.readMessage(fields, 24) != null ? Next.pojo.Position.parseFrom(Pojos.readMessage(fields, 24)) : null,
            Pojos.readInt(fields, 25),
            Pojos.readInt(fields, 26),
            Pojos.readMessageList(fields, 27).stream().map(Next.pojo.BattleNpcInfo::parseFrom).toList(),
            Pojos.readMessage(fields, 28) != null ? Next.pojo.MonsterDiffInfo.parseFrom(Pojos.readMessage(fields, 28)) : null,
            Pojos.readMessageList(fields, 29).stream().map(Next.pojo.OnlookerNpcInfo::parseFrom).toList(),
            Pojos.readMessageList(fields, 30).stream().map(Next.pojo.CheerMonsterInitInfo::parseFrom).toList(),
            Pojos.readIntList(fields, 31),
            Pojos.readMessage(fields, 32) != null ? Next.pojo.BloodPetFight.parseFrom(Pojos.readMessage(fields, 32)) : null,
            Pojos.readMessage(fields, 33) != null ? Next.pojo.BeastPetFight.parseFrom(Pojos.readMessage(fields, 33)) : null,
            Pojos.readMessage(fields, 34) != null ? Next.pojo.WorldLeaderFight.parseFrom(Pojos.readMessage(fields, 34)) : null,
            Pojos.readMessage(fields, 35) != null ? Next.pojo.BattlePveInfo.parseFrom(Pojos.readMessage(fields, 35)) : null,
            Pojos.readMessageList(fields, 36).stream().map(Next.pojo.WorldCombatExtraReward::parseFrom).toList(),
            Pojos.readBool(fields, 38),
            Pojos.readMessage(fields, 39) != null ? Next.pojo.CreateBattleInfo_DoubleInteract.parseFrom(Pojos.readMessage(fields, 39)) : null,
            Pojos.readBool(fields, 40),
            Pojos.readInt(fields, 41),
            Pojos.readInt(fields, 42),
            Pojos.readInt(fields, 100),
            Pojos.readLong(fields, 101),
            Pojos.readLong(fields, 102),
            Pojos.readInt(fields, 103),
            Pojos.readMessageList(fields, 104).stream().map(Next.pojo.MonsterCreateInfo::parseFrom).toList(),
            Pojos.readInt(fields, 105),
            Pojos.readInt(fields, 106),
            Pojos.readMessageList(fields, 107).stream().map(Next.pojo.PvpNpcInfo::parseFrom).toList(),
            Pojos.readInt(fields, 109, 0),
            Pojos.readMessage(fields, 110) != null ? Next.pojo.BadgeChallengeInfo.parseFrom(Pojos.readMessage(fields, 110)) : null,
            Pojos.readMessageList(fields, 111).stream().map(Next.pojo.GmBattleNpc::parseFrom).toList(),
            Pojos.readMessage(fields, 112) != null ? Next.pojo.PveSeasonInfo.parseFrom(Pojos.readMessage(fields, 112)) : null,
            Pojos.readInt(fields, 113),
            Pojos.readInt(fields, 114),
            Pojos.readInt(fields, 115),
            Pojos.readBool(fields, 116),
            Pojos.readBool(fields, 117),
            Pojos.readBool(fields, 118),
            Pojos.readBool(fields, 119),
            Pojos.readIntList(fields, 200)
        );
    }
    public static CreateBattleInfo parseFrom(java.util.List<ProtoField> fields) {
        return new CreateBattleInfo(
            Pojos.readInt(fields, 1),
            Pojos.readInt(fields, 2),
            Pojos.readInt(fields, 3),
            Pojos.readMessageList(fields, 4).stream().map(Next.pojo.PlayerZoneId::parseFrom).toList(),
            Pojos.readMessageList(fields, 5).stream().map(Next.pojo.PlayerZoneId::parseFrom).toList(),
            Pojos.readMessage(fields, 6) != null ? Next.pojo.Point.parseFrom(Pojos.readMessage(fields, 6)) : null,
            Pojos.readMessage(fields, 7) != null ? Next.pojo.Point.parseFrom(Pojos.readMessage(fields, 7)) : null,
            Pojos.readLongList(fields, 8),
            Pojos.readInt(fields, 9),
            Pojos.readLong(fields, 10),
            Pojos.readInt(fields, 11),
            Pojos.readInt(fields, 12),
            Pojos.readMessage(fields, 13) != null ? Next.pojo.Position.parseFrom(Pojos.readMessage(fields, 13)) : null,
            Pojos.readMessage(fields, 14) != null ? Next.pojo.Position.parseFrom(Pojos.readMessage(fields, 14)) : null,
            Pojos.readLong(fields, 15),
            Pojos.readInt(fields, 16),
            Pojos.readBool(fields, 17),
            Pojos.readInt(fields, 18),
            Pojos.readInt(fields, 19),
            Pojos.readInt(fields, 20),
            Pojos.readInt(fields, 21),
            Pojos.readInt(fields, 22),
            Pojos.readMessage(fields, 23) != null ? Next.pojo.PvpModeCtl.parseFrom(Pojos.readMessage(fields, 23)) : null,
            Pojos.readMessage(fields, 24) != null ? Next.pojo.Position.parseFrom(Pojos.readMessage(fields, 24)) : null,
            Pojos.readInt(fields, 25),
            Pojos.readInt(fields, 26),
            Pojos.readMessageList(fields, 27).stream().map(Next.pojo.BattleNpcInfo::parseFrom).toList(),
            Pojos.readMessage(fields, 28) != null ? Next.pojo.MonsterDiffInfo.parseFrom(Pojos.readMessage(fields, 28)) : null,
            Pojos.readMessageList(fields, 29).stream().map(Next.pojo.OnlookerNpcInfo::parseFrom).toList(),
            Pojos.readMessageList(fields, 30).stream().map(Next.pojo.CheerMonsterInitInfo::parseFrom).toList(),
            Pojos.readIntList(fields, 31),
            Pojos.readMessage(fields, 32) != null ? Next.pojo.BloodPetFight.parseFrom(Pojos.readMessage(fields, 32)) : null,
            Pojos.readMessage(fields, 33) != null ? Next.pojo.BeastPetFight.parseFrom(Pojos.readMessage(fields, 33)) : null,
            Pojos.readMessage(fields, 34) != null ? Next.pojo.WorldLeaderFight.parseFrom(Pojos.readMessage(fields, 34)) : null,
            Pojos.readMessage(fields, 35) != null ? Next.pojo.BattlePveInfo.parseFrom(Pojos.readMessage(fields, 35)) : null,
            Pojos.readMessageList(fields, 36).stream().map(Next.pojo.WorldCombatExtraReward::parseFrom).toList(),
            Pojos.readBool(fields, 38),
            Pojos.readMessage(fields, 39) != null ? Next.pojo.CreateBattleInfo_DoubleInteract.parseFrom(Pojos.readMessage(fields, 39)) : null,
            Pojos.readBool(fields, 40),
            Pojos.readInt(fields, 41),
            Pojos.readInt(fields, 42),
            Pojos.readInt(fields, 100),
            Pojos.readLong(fields, 101),
            Pojos.readLong(fields, 102),
            Pojos.readInt(fields, 103),
            Pojos.readMessageList(fields, 104).stream().map(Next.pojo.MonsterCreateInfo::parseFrom).toList(),
            Pojos.readInt(fields, 105),
            Pojos.readInt(fields, 106),
            Pojos.readMessageList(fields, 107).stream().map(Next.pojo.PvpNpcInfo::parseFrom).toList(),
            Pojos.readInt(fields, 109, 0),
            Pojos.readMessage(fields, 110) != null ? Next.pojo.BadgeChallengeInfo.parseFrom(Pojos.readMessage(fields, 110)) : null,
            Pojos.readMessageList(fields, 111).stream().map(Next.pojo.GmBattleNpc::parseFrom).toList(),
            Pojos.readMessage(fields, 112) != null ? Next.pojo.PveSeasonInfo.parseFrom(Pojos.readMessage(fields, 112)) : null,
            Pojos.readInt(fields, 113),
            Pojos.readInt(fields, 114),
            Pojos.readInt(fields, 115),
            Pojos.readBool(fields, 116),
            Pojos.readBool(fields, 117),
            Pojos.readBool(fields, 118),
            Pojos.readBool(fields, 119),
            Pojos.readIntList(fields, 200)
        );
    }
}
