// Generated from com_pet.proto
package Next.pojo;

import com.roco.sniffer.codec.Pojos;
import com.roco.sniffer.codec.ProtoParser.ProtoField;
import com.roco.sniffer.codec.ProtoParser;
import java.util.List;

@SuppressWarnings("unused")
public record PetData(
    int gid,
    int confId,
    byte[] name,
    int infoId,
    int nameSrc,
    List<Integer> skillDamType,
    int nature,
    int gender,
    int exp,
    int level,
    int ballId,
    PetSkillInfo skill,
    PetAbilityInfo ability,
    PetAttributeInfo attributeInfo,
    PetAdditionalNewAttrList attributeNewInfo,
    int baseConfId,
    boolean unlockedUltimateSkill,
    int evolutionChosenIdx,
    int evolutionStage,
    int seed,
    BattleAIInitInfo aiInfo,
    int petStatusFlags,
    int successCatchCnt,
    int height,
    int weight,
    int classis,
    int lastBreakthroughLv,
    PossessionInfo possession,
    int addTime,
    int energy,
    int handbookThreshold,
    List<Integer> synchronNum,
    boolean isFirstCatch,
    int catchStatus,
    int catchLv,
    int catchBaseId,
    int mutationType,
    int catchAiStatus,
    int bloodId,
    CheerMonsterInitInfo cheerInfo,
    int habitGroupId,
    int habitLevel,
    PetStatistics stat,
    int rideStartTime,
    int hbProbAdd,
    int talentRank,
    int changedNaturePosAttrType,
    int changedNatureNegAttrType,
    int caughtCamp,
    PetSkillInfo allSkill,
    int attrVersion,
    int skillVersion,
    int randEvoluId,
    int specialityVersion,
    int rawLevel,
    int growTimes,
    int catchWay,
    byte[] catchVisitOwnerName,
    byte[] natureDesc,
    PetKeyExperience keyExperience,
    int nightmareEliteId,
    int wearMedalConfId,
    int medalCompleteCnt,
    PetClosenessInfo closenessInfo,
    int partnerMark,
    PetEvolutionNeedInfo evlutionNeedInfo,
    List<Integer> customMedalConfId,
    boolean isTrialPet,
    int specialityId,
    List<Integer> realSpecialityIds,
    boolean isInBadgechallenge,
    GlassInfo glassInfo,
    List<PetCheerPointInfo> cheerPointInfo,
    int bitflag,
    int businessIdentity,
    TogetherCatchInfo togetherCatchInfo,
    List<Integer> freeMedalConfIds,
    PetTypeInfo type,
    int voice,
    ActivityPartnerPetData activityPartnerPetData,
    int natureAttrChangeWay,
    int inspireLv,
    int natureDescId,
    boolean hideShine,
    int patchVersion,
    PetSceneInfo sceneInfo
) {
    public static PetData parseFrom(byte[] data) {
        java.util.List<ProtoField> fields = ProtoParser.parse(data);
        return new PetData(
            Pojos.readInt(fields, 1),
            Pojos.readInt(fields, 2),
            Pojos.readBytes(fields, 3),
            Pojos.readInt(fields, 4),
            Pojos.readInt(fields, 5, 0),
            Pojos.readIntList(fields, 6),
            Pojos.readInt(fields, 7),
            Pojos.readInt(fields, 8),
            Pojos.readInt(fields, 9),
            Pojos.readInt(fields, 10),
            Pojos.readInt(fields, 11),
            Pojos.readMessage(fields, 12) != null ? Next.pojo.PetSkillInfo.parseFrom(Pojos.readMessage(fields, 12)) : null,
            Pojos.readMessage(fields, 13) != null ? Next.pojo.PetAbilityInfo.parseFrom(Pojos.readMessage(fields, 13)) : null,
            Pojos.readMessage(fields, 14) != null ? Next.pojo.PetAttributeInfo.parseFrom(Pojos.readMessage(fields, 14)) : null,
            Pojos.readMessage(fields, 75) != null ? Next.pojo.PetAdditionalNewAttrList.parseFrom(Pojos.readMessage(fields, 75)) : null,
            Pojos.readInt(fields, 15),
            Pojos.readBool(fields, 17),
            Pojos.readInt(fields, 19),
            Pojos.readInt(fields, 20, 0),
            Pojos.readInt(fields, 22),
            Pojos.readMessage(fields, 23) != null ? Next.pojo.BattleAIInitInfo.parseFrom(Pojos.readMessage(fields, 23)) : null,
            Pojos.readInt(fields, 24),
            Pojos.readInt(fields, 25),
            Pojos.readInt(fields, 26),
            Pojos.readInt(fields, 27),
            Pojos.readInt(fields, 28),
            Pojos.readInt(fields, 30),
            Pojos.readMessage(fields, 31) != null ? Next.pojo.PossessionInfo.parseFrom(Pojos.readMessage(fields, 31)) : null,
            Pojos.readInt(fields, 32),
            Pojos.readInt(fields, 33),
            Pojos.readInt(fields, 35),
            Pojos.readIntList(fields, 37),
            Pojos.readBool(fields, 39),
            Pojos.readInt(fields, 40),
            Pojos.readInt(fields, 41),
            Pojos.readInt(fields, 42),
            Pojos.readInt(fields, 45),
            Pojos.readInt(fields, 46),
            Pojos.readInt(fields, 47),
            Pojos.readMessage(fields, 48) != null ? Next.pojo.CheerMonsterInitInfo.parseFrom(Pojos.readMessage(fields, 48)) : null,
            Pojos.readInt(fields, 49),
            Pojos.readInt(fields, 50),
            Pojos.readMessage(fields, 51) != null ? Next.pojo.PetStatistics.parseFrom(Pojos.readMessage(fields, 51)) : null,
            Pojos.readInt(fields, 52),
            Pojos.readInt(fields, 54),
            Pojos.readInt(fields, 55),
            Pojos.readInt(fields, 56),
            Pojos.readInt(fields, 57),
            Pojos.readInt(fields, 58),
            Pojos.readMessage(fields, 59) != null ? Next.pojo.PetSkillInfo.parseFrom(Pojos.readMessage(fields, 59)) : null,
            Pojos.readInt(fields, 60),
            Pojos.readInt(fields, 61),
            Pojos.readInt(fields, 62),
            Pojos.readInt(fields, 63),
            Pojos.readInt(fields, 65),
            Pojos.readInt(fields, 66),
            Pojos.readInt(fields, 67),
            Pojos.readBytes(fields, 68),
            Pojos.readBytes(fields, 69),
            Pojos.readMessage(fields, 70) != null ? Next.pojo.PetKeyExperience.parseFrom(Pojos.readMessage(fields, 70)) : null,
            Pojos.readInt(fields, 72),
            Pojos.readInt(fields, 73),
            Pojos.readInt(fields, 74),
            Pojos.readMessage(fields, 77) != null ? Next.pojo.PetClosenessInfo.parseFrom(Pojos.readMessage(fields, 77)) : null,
            Pojos.readInt(fields, 78, 0),
            Pojos.readMessage(fields, 79) != null ? Next.pojo.PetEvolutionNeedInfo.parseFrom(Pojos.readMessage(fields, 79)) : null,
            Pojos.readIntList(fields, 80),
            Pojos.readBool(fields, 81),
            Pojos.readInt(fields, 82),
            Pojos.readIntList(fields, 83),
            Pojos.readBool(fields, 84),
            Pojos.readMessage(fields, 86) != null ? Next.pojo.GlassInfo.parseFrom(Pojos.readMessage(fields, 86)) : null,
            Pojos.readMessageList(fields, 87).stream().map(Next.pojo.PetCheerPointInfo::parseFrom).toList(),
            Pojos.readInt(fields, 88),
            Pojos.readInt(fields, 89),
            Pojos.readMessage(fields, 90) != null ? Next.pojo.TogetherCatchInfo.parseFrom(Pojos.readMessage(fields, 90)) : null,
            Pojos.readIntList(fields, 91),
            Pojos.readMessage(fields, 92) != null ? Next.pojo.PetTypeInfo.parseFrom(Pojos.readMessage(fields, 92)) : null,
            Pojos.readInt(fields, 93),
            Pojos.readMessage(fields, 94) != null ? Next.pojo.ActivityPartnerPetData.parseFrom(Pojos.readMessage(fields, 94)) : null,
            Pojos.readInt(fields, 95, 0),
            Pojos.readInt(fields, 96),
            Pojos.readInt(fields, 97),
            Pojos.readBool(fields, 98),
            Pojos.readInt(fields, 99),
            Pojos.readMessage(fields, 100) != null ? Next.pojo.PetSceneInfo.parseFrom(Pojos.readMessage(fields, 100)) : null
        );
    }
    public static PetData parseFrom(java.util.List<ProtoField> fields) {
        return new PetData(
            Pojos.readInt(fields, 1),
            Pojos.readInt(fields, 2),
            Pojos.readBytes(fields, 3),
            Pojos.readInt(fields, 4),
            Pojos.readInt(fields, 5, 0),
            Pojos.readIntList(fields, 6),
            Pojos.readInt(fields, 7),
            Pojos.readInt(fields, 8),
            Pojos.readInt(fields, 9),
            Pojos.readInt(fields, 10),
            Pojos.readInt(fields, 11),
            Pojos.readMessage(fields, 12) != null ? Next.pojo.PetSkillInfo.parseFrom(Pojos.readMessage(fields, 12)) : null,
            Pojos.readMessage(fields, 13) != null ? Next.pojo.PetAbilityInfo.parseFrom(Pojos.readMessage(fields, 13)) : null,
            Pojos.readMessage(fields, 14) != null ? Next.pojo.PetAttributeInfo.parseFrom(Pojos.readMessage(fields, 14)) : null,
            Pojos.readMessage(fields, 75) != null ? Next.pojo.PetAdditionalNewAttrList.parseFrom(Pojos.readMessage(fields, 75)) : null,
            Pojos.readInt(fields, 15),
            Pojos.readBool(fields, 17),
            Pojos.readInt(fields, 19),
            Pojos.readInt(fields, 20, 0),
            Pojos.readInt(fields, 22),
            Pojos.readMessage(fields, 23) != null ? Next.pojo.BattleAIInitInfo.parseFrom(Pojos.readMessage(fields, 23)) : null,
            Pojos.readInt(fields, 24),
            Pojos.readInt(fields, 25),
            Pojos.readInt(fields, 26),
            Pojos.readInt(fields, 27),
            Pojos.readInt(fields, 28),
            Pojos.readInt(fields, 30),
            Pojos.readMessage(fields, 31) != null ? Next.pojo.PossessionInfo.parseFrom(Pojos.readMessage(fields, 31)) : null,
            Pojos.readInt(fields, 32),
            Pojos.readInt(fields, 33),
            Pojos.readInt(fields, 35),
            Pojos.readIntList(fields, 37),
            Pojos.readBool(fields, 39),
            Pojos.readInt(fields, 40),
            Pojos.readInt(fields, 41),
            Pojos.readInt(fields, 42),
            Pojos.readInt(fields, 45),
            Pojos.readInt(fields, 46),
            Pojos.readInt(fields, 47),
            Pojos.readMessage(fields, 48) != null ? Next.pojo.CheerMonsterInitInfo.parseFrom(Pojos.readMessage(fields, 48)) : null,
            Pojos.readInt(fields, 49),
            Pojos.readInt(fields, 50),
            Pojos.readMessage(fields, 51) != null ? Next.pojo.PetStatistics.parseFrom(Pojos.readMessage(fields, 51)) : null,
            Pojos.readInt(fields, 52),
            Pojos.readInt(fields, 54),
            Pojos.readInt(fields, 55),
            Pojos.readInt(fields, 56),
            Pojos.readInt(fields, 57),
            Pojos.readInt(fields, 58),
            Pojos.readMessage(fields, 59) != null ? Next.pojo.PetSkillInfo.parseFrom(Pojos.readMessage(fields, 59)) : null,
            Pojos.readInt(fields, 60),
            Pojos.readInt(fields, 61),
            Pojos.readInt(fields, 62),
            Pojos.readInt(fields, 63),
            Pojos.readInt(fields, 65),
            Pojos.readInt(fields, 66),
            Pojos.readInt(fields, 67),
            Pojos.readBytes(fields, 68),
            Pojos.readBytes(fields, 69),
            Pojos.readMessage(fields, 70) != null ? Next.pojo.PetKeyExperience.parseFrom(Pojos.readMessage(fields, 70)) : null,
            Pojos.readInt(fields, 72),
            Pojos.readInt(fields, 73),
            Pojos.readInt(fields, 74),
            Pojos.readMessage(fields, 77) != null ? Next.pojo.PetClosenessInfo.parseFrom(Pojos.readMessage(fields, 77)) : null,
            Pojos.readInt(fields, 78, 0),
            Pojos.readMessage(fields, 79) != null ? Next.pojo.PetEvolutionNeedInfo.parseFrom(Pojos.readMessage(fields, 79)) : null,
            Pojos.readIntList(fields, 80),
            Pojos.readBool(fields, 81),
            Pojos.readInt(fields, 82),
            Pojos.readIntList(fields, 83),
            Pojos.readBool(fields, 84),
            Pojos.readMessage(fields, 86) != null ? Next.pojo.GlassInfo.parseFrom(Pojos.readMessage(fields, 86)) : null,
            Pojos.readMessageList(fields, 87).stream().map(Next.pojo.PetCheerPointInfo::parseFrom).toList(),
            Pojos.readInt(fields, 88),
            Pojos.readInt(fields, 89),
            Pojos.readMessage(fields, 90) != null ? Next.pojo.TogetherCatchInfo.parseFrom(Pojos.readMessage(fields, 90)) : null,
            Pojos.readIntList(fields, 91),
            Pojos.readMessage(fields, 92) != null ? Next.pojo.PetTypeInfo.parseFrom(Pojos.readMessage(fields, 92)) : null,
            Pojos.readInt(fields, 93),
            Pojos.readMessage(fields, 94) != null ? Next.pojo.ActivityPartnerPetData.parseFrom(Pojos.readMessage(fields, 94)) : null,
            Pojos.readInt(fields, 95, 0),
            Pojos.readInt(fields, 96),
            Pojos.readInt(fields, 97),
            Pojos.readBool(fields, 98),
            Pojos.readInt(fields, 99),
            Pojos.readMessage(fields, 100) != null ? Next.pojo.PetSceneInfo.parseFrom(Pojos.readMessage(fields, 100)) : null
        );
    }
}
