// Generated from battle_data.proto
package Next.pojo;

import io.github.kedaya0209.roco.sniffer.codec.Pojos;
import io.github.kedaya0209.roco.sniffer.codec.ProtoParser.ProtoField;
import io.github.kedaya0209.roco.sniffer.codec.ProtoParser;
import java.util.List;

@SuppressWarnings("unused")
public record PetSkillRoundData(
    int id,
    int state,
    int type,
    int castCnt,
    int costHp,
    boolean displayHp,
    float hpPerEnergy,
    int lastCastRound,
    int costEnergy,
    int costEnergyBuff,
    int costEnergyBuffFactor,
    int costEnergyBuffMul,
    int costEnergyBuffSet,
    int spEnergySkill,
    int carryonSlotIdx,
    int consumeEnergy,
    int consumeHp,
    int exDamageParam,
    boolean costAllEnergy,
    boolean feverState,
    int ruleEnergy,
    int ruleDamageParam,
    int effectDamageParam,
    int buffDamageParam,
    int pos,
    List<DamageParam> damageParams,
    List<RestraintType> restraintTypes,
    int cdRound,
    int flag,
    int rawDamage,
    int usedCnt,
    int usedCntForEvolute,
    List<ExtraDamTypeInfo> extraDamageType,
    boolean disableConfDamType,
    List<SkillCDInfo> cdInfo,
    List<SkillEnhanceInfo> enhanceInfo,
    int changeTimes,
    int crResetRound,
    int crResetReason,
    int skillId,
    List<CRDamageParam> crDamageParams,
    int changeSrcSkill,
    int stateTips,
    boolean mustCostHp,
    SkillBuffInfo skillBuff,
    int lastPos,
    TransInfo transInfo,
    int consumeChangeEffeciency,
    int isChangeEffeciency,
    int originalPos,
    int rawCostEnergy,
    int castRounds,
    boolean enableOnCharging,
    int roundStartPos,
    int lastRoundPos,
    int swapFromPet,
    boolean priorityDisplay,
    List<SetCostInfo> setCostInfo,
    int performFlag,
    int removeRound,
    int originalSkillId,
    int damageType,
    int costEnergyBuffMul10000,
    List<Integer> costEnergyBuffFactorList,
    int cdOutfieldRound
) {
    public static PetSkillRoundData parseFrom(byte[] data) {
        java.util.List<ProtoField> fields = ProtoParser.parse(data);
        return new PetSkillRoundData(
            Pojos.readInt(fields, 1),
            Pojos.readInt(fields, 2, 0),
            Pojos.readInt(fields, 3),
            Pojos.readInt(fields, 4),
            Pojos.readInt(fields, 5),
            Pojos.readBool(fields, 6),
            Pojos.readFloat(fields, 7),
            Pojos.readInt(fields, 8),
            Pojos.readInt(fields, 9),
            Pojos.readInt(fields, 10),
            Pojos.readInt(fields, 11),
            Pojos.readInt(fields, 12),
            Pojos.readInt(fields, 13),
            Pojos.readInt(fields, 14),
            Pojos.readInt(fields, 15),
            Pojos.readInt(fields, 16),
            Pojos.readInt(fields, 17),
            Pojos.readInt(fields, 18),
            Pojos.readBool(fields, 19),
            Pojos.readBool(fields, 20),
            Pojos.readInt(fields, 21),
            Pojos.readInt(fields, 22),
            Pojos.readInt(fields, 23),
            Pojos.readInt(fields, 24),
            Pojos.readInt(fields, 25),
            Pojos.readMessageList(fields, 26).stream().map(Next.pojo.DamageParam::parseFrom).toList(),
            Pojos.readMessageList(fields, 27).stream().map(Next.pojo.RestraintType::parseFrom).toList(),
            Pojos.readInt(fields, 28),
            Pojos.readInt(fields, 29),
            Pojos.readInt(fields, 30),
            Pojos.readInt(fields, 31),
            Pojos.readInt(fields, 40),
            Pojos.readMessageList(fields, 32).stream().map(Next.pojo.ExtraDamTypeInfo::parseFrom).toList(),
            Pojos.readBool(fields, 33),
            Pojos.readMessageList(fields, 34).stream().map(Next.pojo.SkillCDInfo::parseFrom).toList(),
            Pojos.readMessageList(fields, 35).stream().map(Next.pojo.SkillEnhanceInfo::parseFrom).toList(),
            Pojos.readInt(fields, 36),
            Pojos.readInt(fields, 37),
            Pojos.readInt(fields, 38),
            Pojos.readInt(fields, 39),
            Pojos.readMessageList(fields, 41).stream().map(Next.pojo.CRDamageParam::parseFrom).toList(),
            Pojos.readInt(fields, 42),
            Pojos.readInt(fields, 43),
            Pojos.readBool(fields, 44),
            Pojos.readMessage(fields, 45) != null ? Next.pojo.SkillBuffInfo.parseFrom(Pojos.readMessage(fields, 45)) : null,
            Pojos.readInt(fields, 47),
            Pojos.readMessage(fields, 48) != null ? Next.pojo.TransInfo.parseFrom(Pojos.readMessage(fields, 48)) : null,
            Pojos.readInt(fields, 49),
            Pojos.readInt(fields, 50),
            Pojos.readInt(fields, 51),
            Pojos.readInt(fields, 52),
            Pojos.readInt(fields, 53),
            Pojos.readBool(fields, 54),
            Pojos.readInt(fields, 55),
            Pojos.readInt(fields, 56),
            Pojos.readInt(fields, 57),
            Pojos.readBool(fields, 58),
            Pojos.readMessageList(fields, 59).stream().map(Next.pojo.SetCostInfo::parseFrom).toList(),
            Pojos.readInt(fields, 60),
            Pojos.readInt(fields, 61),
            Pojos.readInt(fields, 62),
            Pojos.readInt(fields, 63),
            Pojos.readInt(fields, 64),
            Pojos.readIntList(fields, 65),
            Pojos.readInt(fields, 66)
        );
    }
    public static PetSkillRoundData parseFrom(java.util.List<ProtoField> fields) {
        return new PetSkillRoundData(
            Pojos.readInt(fields, 1),
            Pojos.readInt(fields, 2, 0),
            Pojos.readInt(fields, 3),
            Pojos.readInt(fields, 4),
            Pojos.readInt(fields, 5),
            Pojos.readBool(fields, 6),
            Pojos.readFloat(fields, 7),
            Pojos.readInt(fields, 8),
            Pojos.readInt(fields, 9),
            Pojos.readInt(fields, 10),
            Pojos.readInt(fields, 11),
            Pojos.readInt(fields, 12),
            Pojos.readInt(fields, 13),
            Pojos.readInt(fields, 14),
            Pojos.readInt(fields, 15),
            Pojos.readInt(fields, 16),
            Pojos.readInt(fields, 17),
            Pojos.readInt(fields, 18),
            Pojos.readBool(fields, 19),
            Pojos.readBool(fields, 20),
            Pojos.readInt(fields, 21),
            Pojos.readInt(fields, 22),
            Pojos.readInt(fields, 23),
            Pojos.readInt(fields, 24),
            Pojos.readInt(fields, 25),
            Pojos.readMessageList(fields, 26).stream().map(Next.pojo.DamageParam::parseFrom).toList(),
            Pojos.readMessageList(fields, 27).stream().map(Next.pojo.RestraintType::parseFrom).toList(),
            Pojos.readInt(fields, 28),
            Pojos.readInt(fields, 29),
            Pojos.readInt(fields, 30),
            Pojos.readInt(fields, 31),
            Pojos.readInt(fields, 40),
            Pojos.readMessageList(fields, 32).stream().map(Next.pojo.ExtraDamTypeInfo::parseFrom).toList(),
            Pojos.readBool(fields, 33),
            Pojos.readMessageList(fields, 34).stream().map(Next.pojo.SkillCDInfo::parseFrom).toList(),
            Pojos.readMessageList(fields, 35).stream().map(Next.pojo.SkillEnhanceInfo::parseFrom).toList(),
            Pojos.readInt(fields, 36),
            Pojos.readInt(fields, 37),
            Pojos.readInt(fields, 38),
            Pojos.readInt(fields, 39),
            Pojos.readMessageList(fields, 41).stream().map(Next.pojo.CRDamageParam::parseFrom).toList(),
            Pojos.readInt(fields, 42),
            Pojos.readInt(fields, 43),
            Pojos.readBool(fields, 44),
            Pojos.readMessage(fields, 45) != null ? Next.pojo.SkillBuffInfo.parseFrom(Pojos.readMessage(fields, 45)) : null,
            Pojos.readInt(fields, 47),
            Pojos.readMessage(fields, 48) != null ? Next.pojo.TransInfo.parseFrom(Pojos.readMessage(fields, 48)) : null,
            Pojos.readInt(fields, 49),
            Pojos.readInt(fields, 50),
            Pojos.readInt(fields, 51),
            Pojos.readInt(fields, 52),
            Pojos.readInt(fields, 53),
            Pojos.readBool(fields, 54),
            Pojos.readInt(fields, 55),
            Pojos.readInt(fields, 56),
            Pojos.readInt(fields, 57),
            Pojos.readBool(fields, 58),
            Pojos.readMessageList(fields, 59).stream().map(Next.pojo.SetCostInfo::parseFrom).toList(),
            Pojos.readInt(fields, 60),
            Pojos.readInt(fields, 61),
            Pojos.readInt(fields, 62),
            Pojos.readInt(fields, 63),
            Pojos.readInt(fields, 64),
            Pojos.readIntList(fields, 65),
            Pojos.readInt(fields, 66)
        );
    }
}
