// Generated from com_battle.proto
package Next.pojo;

import com.roco.sniffer.codec.Pojos;
import com.roco.sniffer.codec.ProtoParser.ProtoField;
import com.roco.sniffer.codec.ProtoParser;
import java.util.List;

@SuppressWarnings("unused")
public record PlayerPkInfo(
    int selfState,
    PlayerBriefInfo enemy,
    int enemyState,
    int startTime,
    int endTime,
    int firstPetGid,
    List<PkPetData> pets,
    int selfHp,
    int enemyHp,
    boolean selfCancel,
    boolean enemyCancel,
    BattleFashionInfo enemyFashion,
    int flag,
    int pvpId,
    List<MatchSuccInfo> matchInfos,
    int pkagainCnt,
    PvpNpcInfo npcEnemy,
    int npcConfirmUt,
    long seqNum,
    int enemyPvpRankStar,
    int enemyPvpRankOrder,
    List<PetData> welfareTeam,
    int pveBattleConfId,
    int battleCfgId,
    PlayerSceneInfo battleCenter,
    PlayerSceneInfo backupScene,
    boolean online,
    List<PlayerPkInfo_EnemyPetInfo> enemyPets,
    boolean showEnemyPet,
    int teleportBackCnt,
    int roleMagicGid,
    int welfareTeamRoleMagicId,
    boolean isMirror,
    boolean mirrorMagicId,
    long bfid,
    int rotate
) {
    public static PlayerPkInfo parseFrom(byte[] data) {
        java.util.List<ProtoField> fields = ProtoParser.parse(data);
        return new PlayerPkInfo(
            Pojos.readInt(fields, 1, 0),
            Pojos.readMessage(fields, 2) != null ? Next.pojo.PlayerBriefInfo.parseFrom(Pojos.readMessage(fields, 2)) : null,
            Pojos.readInt(fields, 3, 0),
            Pojos.readInt(fields, 4),
            Pojos.readInt(fields, 5),
            Pojos.readInt(fields, 6),
            Pojos.readMessageList(fields, 7).stream().map(Next.pojo.PkPetData::parseFrom).toList(),
            Pojos.readInt(fields, 8),
            Pojos.readInt(fields, 9),
            Pojos.readBool(fields, 10),
            Pojos.readBool(fields, 11),
            Pojos.readMessage(fields, 12) != null ? Next.pojo.BattleFashionInfo.parseFrom(Pojos.readMessage(fields, 12)) : null,
            Pojos.readInt(fields, 14),
            Pojos.readInt(fields, 15),
            Pojos.readMessageList(fields, 16).stream().map(Next.pojo.MatchSuccInfo::parseFrom).toList(),
            Pojos.readInt(fields, 17),
            Pojos.readMessage(fields, 18) != null ? Next.pojo.PvpNpcInfo.parseFrom(Pojos.readMessage(fields, 18)) : null,
            Pojos.readInt(fields, 19),
            Pojos.readLong(fields, 20),
            Pojos.readInt(fields, 21),
            Pojos.readInt(fields, 28),
            Pojos.readMessageList(fields, 22).stream().map(Next.pojo.PetData::parseFrom).toList(),
            Pojos.readInt(fields, 27),
            Pojos.readInt(fields, 23),
            Pojos.readMessage(fields, 24) != null ? Next.pojo.PlayerSceneInfo.parseFrom(Pojos.readMessage(fields, 24)) : null,
            Pojos.readMessage(fields, 25) != null ? Next.pojo.PlayerSceneInfo.parseFrom(Pojos.readMessage(fields, 25)) : null,
            Pojos.readBool(fields, 26),
            Pojos.readMessageList(fields, 29).stream().map(Next.pojo.PlayerPkInfo_EnemyPetInfo::parseFrom).toList(),
            Pojos.readBool(fields, 30),
            Pojos.readInt(fields, 31),
            Pojos.readInt(fields, 32),
            Pojos.readInt(fields, 33),
            Pojos.readBool(fields, 34),
            Pojos.readBool(fields, 35),
            Pojos.readLong(fields, 36),
            Pojos.readInt(fields, 37)
        );
    }
    public static PlayerPkInfo parseFrom(java.util.List<ProtoField> fields) {
        return new PlayerPkInfo(
            Pojos.readInt(fields, 1, 0),
            Pojos.readMessage(fields, 2) != null ? Next.pojo.PlayerBriefInfo.parseFrom(Pojos.readMessage(fields, 2)) : null,
            Pojos.readInt(fields, 3, 0),
            Pojos.readInt(fields, 4),
            Pojos.readInt(fields, 5),
            Pojos.readInt(fields, 6),
            Pojos.readMessageList(fields, 7).stream().map(Next.pojo.PkPetData::parseFrom).toList(),
            Pojos.readInt(fields, 8),
            Pojos.readInt(fields, 9),
            Pojos.readBool(fields, 10),
            Pojos.readBool(fields, 11),
            Pojos.readMessage(fields, 12) != null ? Next.pojo.BattleFashionInfo.parseFrom(Pojos.readMessage(fields, 12)) : null,
            Pojos.readInt(fields, 14),
            Pojos.readInt(fields, 15),
            Pojos.readMessageList(fields, 16).stream().map(Next.pojo.MatchSuccInfo::parseFrom).toList(),
            Pojos.readInt(fields, 17),
            Pojos.readMessage(fields, 18) != null ? Next.pojo.PvpNpcInfo.parseFrom(Pojos.readMessage(fields, 18)) : null,
            Pojos.readInt(fields, 19),
            Pojos.readLong(fields, 20),
            Pojos.readInt(fields, 21),
            Pojos.readInt(fields, 28),
            Pojos.readMessageList(fields, 22).stream().map(Next.pojo.PetData::parseFrom).toList(),
            Pojos.readInt(fields, 27),
            Pojos.readInt(fields, 23),
            Pojos.readMessage(fields, 24) != null ? Next.pojo.PlayerSceneInfo.parseFrom(Pojos.readMessage(fields, 24)) : null,
            Pojos.readMessage(fields, 25) != null ? Next.pojo.PlayerSceneInfo.parseFrom(Pojos.readMessage(fields, 25)) : null,
            Pojos.readBool(fields, 26),
            Pojos.readMessageList(fields, 29).stream().map(Next.pojo.PlayerPkInfo_EnemyPetInfo::parseFrom).toList(),
            Pojos.readBool(fields, 30),
            Pojos.readInt(fields, 31),
            Pojos.readInt(fields, 32),
            Pojos.readInt(fields, 33),
            Pojos.readBool(fields, 34),
            Pojos.readBool(fields, 35),
            Pojos.readLong(fields, 36),
            Pojos.readInt(fields, 37)
        );
    }
}
