// Generated from com_activity.proto
package Next.pojo;

import com.roco.sniffer.codec.Pojos;
import com.roco.sniffer.codec.ProtoParser.ProtoField;
import com.roco.sniffer.codec.ProtoParser;
import java.util.List;

@SuppressWarnings("unused")
public record PlayerActivityInfo_ActivityData(
    int activityId,
    int activityType,
    boolean expired,
    boolean shouldDisppeared,
    boolean firstOpen,
    int activityFinishTime,
    boolean trackRedPointAddFlag,
    boolean activityUnlockAdvance,
    int lotteryResult,
    ActivityScoreRewardCompData scoreRewardCompData,
    int loginAccelerateDays,
    long lastRefreshContentTimestamp,
    int activityOpenTime,
    PlayerActivityInfo_ActivityStageData stageData,
    List<PlayerActivityInfo_ActivityPartData> partData,
    PlayerActivityInfo_ActivityPartData legendaryBattleData,
    PlayerActivityInfo_ActivityPetCatchData petCatchData,
    PlayerLimitedFlowerSeedInfo limitedFlowerSeedInfo,
    PlayerActivityInfo_ActivityShinyPetDayData shinyPetDayData,
    PlayerActivityInfo_ActivityNpcChallengeData npcChallengeData,
    PlayerActivityInfo_ActivityBossChallengeData bossChallengeData,
    PlayerActivityInfo_ActivityTreasureHuntData treasureHuntData,
    PlayerActivityInfo_ActivityUpData upData,
    PlayerActivityInfo_ActivityFlowerAppearData flowerAppearData,
    PlayerActivityInfo_ActivityWeeklyChallengeData weeklyChallengeData,
    PlayerActivityInfo_ActivityPetCollectionData petCollectionData,
    PlayerActivityInfo_ActivitySeasonCheckinData seasonCheckinData,
    PlayerActivityInfo_ActivityDrop dropData,
    PlayerActivityInfo_ActivityInheritPetData inheritPetData,
    PlayerActivityInfo_ActivityCoCreation coCreationData,
    PlayerActivityInfo_ActivityMixData mixData,
    PlayerActivityInfo_ActivityConditionGroupData condGroupData,
    PlayerActivityInfo_ActivityPartnerData petPartnerData,
    PlayerActivityInfo_ActivitySpringFestivalData springFestivalData,
    PlayerActivityInfo_ActivitySeasonPreHeatData seasonPreheatData,
    PlayerActivityInfo_ActivityInviteRegisterData inviteRegisterData,
    PlayerActivityInfo_ActivityTerritoryTrialData territoryTrialData,
    PlayerActivityInfo_ActivityPetPhotoData petPhotoData,
    PlayerActivityInfo_ActivityPetCertificationData petCertificationData
) {
    public static PlayerActivityInfo_ActivityData parseFrom(byte[] data) {
        java.util.List<ProtoField> fields = ProtoParser.parse(data);
        return new PlayerActivityInfo_ActivityData(
            Pojos.readInt(fields, 1),
            Pojos.readInt(fields, 9, 0),
            Pojos.readBool(fields, 10),
            Pojos.readBool(fields, 13),
            Pojos.readBool(fields, 15),
            Pojos.readInt(fields, 20),
            Pojos.readBool(fields, 27),
            Pojos.readBool(fields, 28),
            Pojos.readInt(fields, 29),
            Pojos.readMessage(fields, 30) != null ? Next.pojo.ActivityScoreRewardCompData.parseFrom(Pojos.readMessage(fields, 30)) : null,
            Pojos.readInt(fields, 32),
            Pojos.readLong(fields, 37),
            Pojos.readInt(fields, 49),
            Pojos.readMessage(fields, 2) != null ? Next.pojo.PlayerActivityInfo_ActivityStageData.parseFrom(Pojos.readMessage(fields, 2)) : null,
            Pojos.readMessageList(fields, 3).stream().map(Next.pojo.PlayerActivityInfo_ActivityPartData::parseFrom).toList(),
            Pojos.readMessage(fields, 4) != null ? Next.pojo.PlayerActivityInfo_ActivityPartData.parseFrom(Pojos.readMessage(fields, 4)) : null,
            Pojos.readMessage(fields, 5) != null ? Next.pojo.PlayerActivityInfo_ActivityPetCatchData.parseFrom(Pojos.readMessage(fields, 5)) : null,
            Pojos.readMessage(fields, 6) != null ? Next.pojo.PlayerLimitedFlowerSeedInfo.parseFrom(Pojos.readMessage(fields, 6)) : null,
            Pojos.readMessage(fields, 7) != null ? Next.pojo.PlayerActivityInfo_ActivityShinyPetDayData.parseFrom(Pojos.readMessage(fields, 7)) : null,
            Pojos.readMessage(fields, 11) != null ? Next.pojo.PlayerActivityInfo_ActivityNpcChallengeData.parseFrom(Pojos.readMessage(fields, 11)) : null,
            Pojos.readMessage(fields, 12) != null ? Next.pojo.PlayerActivityInfo_ActivityBossChallengeData.parseFrom(Pojos.readMessage(fields, 12)) : null,
            Pojos.readMessage(fields, 14) != null ? Next.pojo.PlayerActivityInfo_ActivityTreasureHuntData.parseFrom(Pojos.readMessage(fields, 14)) : null,
            Pojos.readMessage(fields, 16) != null ? Next.pojo.PlayerActivityInfo_ActivityUpData.parseFrom(Pojos.readMessage(fields, 16)) : null,
            Pojos.readMessage(fields, 17) != null ? Next.pojo.PlayerActivityInfo_ActivityFlowerAppearData.parseFrom(Pojos.readMessage(fields, 17)) : null,
            Pojos.readMessage(fields, 18) != null ? Next.pojo.PlayerActivityInfo_ActivityWeeklyChallengeData.parseFrom(Pojos.readMessage(fields, 18)) : null,
            Pojos.readMessage(fields, 19) != null ? Next.pojo.PlayerActivityInfo_ActivityPetCollectionData.parseFrom(Pojos.readMessage(fields, 19)) : null,
            Pojos.readMessage(fields, 21) != null ? Next.pojo.PlayerActivityInfo_ActivitySeasonCheckinData.parseFrom(Pojos.readMessage(fields, 21)) : null,
            Pojos.readMessage(fields, 22) != null ? Next.pojo.PlayerActivityInfo_ActivityDrop.parseFrom(Pojos.readMessage(fields, 22)) : null,
            Pojos.readMessage(fields, 23) != null ? Next.pojo.PlayerActivityInfo_ActivityInheritPetData.parseFrom(Pojos.readMessage(fields, 23)) : null,
            Pojos.readMessage(fields, 24) != null ? Next.pojo.PlayerActivityInfo_ActivityCoCreation.parseFrom(Pojos.readMessage(fields, 24)) : null,
            Pojos.readMessage(fields, 25) != null ? Next.pojo.PlayerActivityInfo_ActivityMixData.parseFrom(Pojos.readMessage(fields, 25)) : null,
            Pojos.readMessage(fields, 26) != null ? Next.pojo.PlayerActivityInfo_ActivityConditionGroupData.parseFrom(Pojos.readMessage(fields, 26)) : null,
            Pojos.readMessage(fields, 31) != null ? Next.pojo.PlayerActivityInfo_ActivityPartnerData.parseFrom(Pojos.readMessage(fields, 31)) : null,
            Pojos.readMessage(fields, 33) != null ? Next.pojo.PlayerActivityInfo_ActivitySpringFestivalData.parseFrom(Pojos.readMessage(fields, 33)) : null,
            Pojos.readMessage(fields, 34) != null ? Next.pojo.PlayerActivityInfo_ActivitySeasonPreHeatData.parseFrom(Pojos.readMessage(fields, 34)) : null,
            Pojos.readMessage(fields, 35) != null ? Next.pojo.PlayerActivityInfo_ActivityInviteRegisterData.parseFrom(Pojos.readMessage(fields, 35)) : null,
            Pojos.readMessage(fields, 36) != null ? Next.pojo.PlayerActivityInfo_ActivityTerritoryTrialData.parseFrom(Pojos.readMessage(fields, 36)) : null,
            Pojos.readMessage(fields, 38) != null ? Next.pojo.PlayerActivityInfo_ActivityPetPhotoData.parseFrom(Pojos.readMessage(fields, 38)) : null,
            Pojos.readMessage(fields, 39) != null ? Next.pojo.PlayerActivityInfo_ActivityPetCertificationData.parseFrom(Pojos.readMessage(fields, 39)) : null
        );
    }
    public static PlayerActivityInfo_ActivityData parseFrom(java.util.List<ProtoField> fields) {
        return new PlayerActivityInfo_ActivityData(
            Pojos.readInt(fields, 1),
            Pojos.readInt(fields, 9, 0),
            Pojos.readBool(fields, 10),
            Pojos.readBool(fields, 13),
            Pojos.readBool(fields, 15),
            Pojos.readInt(fields, 20),
            Pojos.readBool(fields, 27),
            Pojos.readBool(fields, 28),
            Pojos.readInt(fields, 29),
            Pojos.readMessage(fields, 30) != null ? Next.pojo.ActivityScoreRewardCompData.parseFrom(Pojos.readMessage(fields, 30)) : null,
            Pojos.readInt(fields, 32),
            Pojos.readLong(fields, 37),
            Pojos.readInt(fields, 49),
            Pojos.readMessage(fields, 2) != null ? Next.pojo.PlayerActivityInfo_ActivityStageData.parseFrom(Pojos.readMessage(fields, 2)) : null,
            Pojos.readMessageList(fields, 3).stream().map(Next.pojo.PlayerActivityInfo_ActivityPartData::parseFrom).toList(),
            Pojos.readMessage(fields, 4) != null ? Next.pojo.PlayerActivityInfo_ActivityPartData.parseFrom(Pojos.readMessage(fields, 4)) : null,
            Pojos.readMessage(fields, 5) != null ? Next.pojo.PlayerActivityInfo_ActivityPetCatchData.parseFrom(Pojos.readMessage(fields, 5)) : null,
            Pojos.readMessage(fields, 6) != null ? Next.pojo.PlayerLimitedFlowerSeedInfo.parseFrom(Pojos.readMessage(fields, 6)) : null,
            Pojos.readMessage(fields, 7) != null ? Next.pojo.PlayerActivityInfo_ActivityShinyPetDayData.parseFrom(Pojos.readMessage(fields, 7)) : null,
            Pojos.readMessage(fields, 11) != null ? Next.pojo.PlayerActivityInfo_ActivityNpcChallengeData.parseFrom(Pojos.readMessage(fields, 11)) : null,
            Pojos.readMessage(fields, 12) != null ? Next.pojo.PlayerActivityInfo_ActivityBossChallengeData.parseFrom(Pojos.readMessage(fields, 12)) : null,
            Pojos.readMessage(fields, 14) != null ? Next.pojo.PlayerActivityInfo_ActivityTreasureHuntData.parseFrom(Pojos.readMessage(fields, 14)) : null,
            Pojos.readMessage(fields, 16) != null ? Next.pojo.PlayerActivityInfo_ActivityUpData.parseFrom(Pojos.readMessage(fields, 16)) : null,
            Pojos.readMessage(fields, 17) != null ? Next.pojo.PlayerActivityInfo_ActivityFlowerAppearData.parseFrom(Pojos.readMessage(fields, 17)) : null,
            Pojos.readMessage(fields, 18) != null ? Next.pojo.PlayerActivityInfo_ActivityWeeklyChallengeData.parseFrom(Pojos.readMessage(fields, 18)) : null,
            Pojos.readMessage(fields, 19) != null ? Next.pojo.PlayerActivityInfo_ActivityPetCollectionData.parseFrom(Pojos.readMessage(fields, 19)) : null,
            Pojos.readMessage(fields, 21) != null ? Next.pojo.PlayerActivityInfo_ActivitySeasonCheckinData.parseFrom(Pojos.readMessage(fields, 21)) : null,
            Pojos.readMessage(fields, 22) != null ? Next.pojo.PlayerActivityInfo_ActivityDrop.parseFrom(Pojos.readMessage(fields, 22)) : null,
            Pojos.readMessage(fields, 23) != null ? Next.pojo.PlayerActivityInfo_ActivityInheritPetData.parseFrom(Pojos.readMessage(fields, 23)) : null,
            Pojos.readMessage(fields, 24) != null ? Next.pojo.PlayerActivityInfo_ActivityCoCreation.parseFrom(Pojos.readMessage(fields, 24)) : null,
            Pojos.readMessage(fields, 25) != null ? Next.pojo.PlayerActivityInfo_ActivityMixData.parseFrom(Pojos.readMessage(fields, 25)) : null,
            Pojos.readMessage(fields, 26) != null ? Next.pojo.PlayerActivityInfo_ActivityConditionGroupData.parseFrom(Pojos.readMessage(fields, 26)) : null,
            Pojos.readMessage(fields, 31) != null ? Next.pojo.PlayerActivityInfo_ActivityPartnerData.parseFrom(Pojos.readMessage(fields, 31)) : null,
            Pojos.readMessage(fields, 33) != null ? Next.pojo.PlayerActivityInfo_ActivitySpringFestivalData.parseFrom(Pojos.readMessage(fields, 33)) : null,
            Pojos.readMessage(fields, 34) != null ? Next.pojo.PlayerActivityInfo_ActivitySeasonPreHeatData.parseFrom(Pojos.readMessage(fields, 34)) : null,
            Pojos.readMessage(fields, 35) != null ? Next.pojo.PlayerActivityInfo_ActivityInviteRegisterData.parseFrom(Pojos.readMessage(fields, 35)) : null,
            Pojos.readMessage(fields, 36) != null ? Next.pojo.PlayerActivityInfo_ActivityTerritoryTrialData.parseFrom(Pojos.readMessage(fields, 36)) : null,
            Pojos.readMessage(fields, 38) != null ? Next.pojo.PlayerActivityInfo_ActivityPetPhotoData.parseFrom(Pojos.readMessage(fields, 38)) : null,
            Pojos.readMessage(fields, 39) != null ? Next.pojo.PlayerActivityInfo_ActivityPetCertificationData.parseFrom(Pojos.readMessage(fields, 39)) : null
        );
    }
}
