// Generated from com_player.proto
package Next.pojo;

import com.roco.sniffer.codec.Pojos;
import com.roco.sniffer.codec.ProtoParser.ProtoField;
import com.roco.sniffer.codec.ProtoParser;
import java.util.List;

@SuppressWarnings("unused")
public record PlayerSvrDataInfo(
    int timeOffset,
    int lastDailyTickTime,
    PlayerDungeonInfo dungeonInfo,
    PlayerHopeData hopeData,
    PlayerBattlePassInfo battlePassInfo,
    PlayerCardInfo cardInfo,
    PlayerSubTaskInfo subTaskInfo,
    PlayerAppearanceInfo appearanceInfo,
    PlayerShareFormInfo shareFormInfo,
    PlayerBattleData battleData,
    List<Integer> receivedMailList,
    List<Integer> receiveFailedMailList,
    List<Long> attachmentReceiveFailMailList,
    long nextMailExpireTime,
    List<MailRecvBrief> sendFailMailBrief,
    PlayerAdventureData adventureData,
    PlayerVisitData visitData,
    PlayerInvestTaskData investTask,
    List<PlayerTeleportData> teleports,
    List<PlayerTeachInfo> teachInfos,
    PlayerActivityInfo activityInfo,
    PlayerCopyData copyData,
    PlayerExchangeInfo exchangeInfo,
    PlayerInteractInfo playerInteractInfo,
    PlayerMageBookInfo mageBookInfo,
    TaskSummaryList taskSummaryData,
    MidasMoneyInfo moneyInfo,
    PlayerShinyPetDayInfo shinyPetDayInfo,
    MidasDistriBillList distributeBillnos,
    int lastPetStatReportTime,
    int lastPetWorldStatUpdateTime,
    List<SpecFlowerSeed> specFlowerSeeds,
    List<PlayerAreaCheckInfo> areaCheckInfos,
    int lastPetBattleStatUpdateTime,
    PlayerCropFruitList cropFruits,
    SceneIdipActionNpcList npcIdipAction,
    PlayerGiftLimitList giftLimitInfo,
    BadgeChallengeData badgeChallengeData,
    long mailVersion,
    SeasonInfo seasonInfo,
    PlayerGiftInfo giftInfo,
    PlayerTypeGiftLimitList giftsLimitInfo,
    List<DailyGetItemLimitlist> itemsLimitInfo,
    PlayerPetMedalInfo petMedalInfo,
    PlayerShareInfo shareInfo,
    PlayerPetEggData petEggData,
    GoodsModifyTransAllInfo goodsTrans,
    PetTeamShareData petTeamShareData,
    DBShop shop,
    long lastCheckExchangeGoodsTime,
    PlayerMailFailInfo mailFailInfo,
    DailySendMailList liabilitiesMailSendInfo,
    PlayerSeasonAdventureData seasonAdventure,
    PlayerTeachingTabInfo teachingTabInfo,
    PlayerMailDataInfo mailInfo
) {
    public static PlayerSvrDataInfo parseFrom(byte[] data) {
        java.util.List<ProtoField> fields = ProtoParser.parse(data);
        return new PlayerSvrDataInfo(
            Pojos.readInt(fields, 6),
            Pojos.readInt(fields, 7),
            Pojos.readMessage(fields, 11) != null ? Next.pojo.PlayerDungeonInfo.parseFrom(Pojos.readMessage(fields, 11)) : null,
            Pojos.readMessage(fields, 12) != null ? Next.pojo.PlayerHopeData.parseFrom(Pojos.readMessage(fields, 12)) : null,
            Pojos.readMessage(fields, 13) != null ? Next.pojo.PlayerBattlePassInfo.parseFrom(Pojos.readMessage(fields, 13)) : null,
            Pojos.readMessage(fields, 14) != null ? Next.pojo.PlayerCardInfo.parseFrom(Pojos.readMessage(fields, 14)) : null,
            Pojos.readMessage(fields, 15) != null ? Next.pojo.PlayerSubTaskInfo.parseFrom(Pojos.readMessage(fields, 15)) : null,
            Pojos.readMessage(fields, 16) != null ? Next.pojo.PlayerAppearanceInfo.parseFrom(Pojos.readMessage(fields, 16)) : null,
            Pojos.readMessage(fields, 17) != null ? Next.pojo.PlayerShareFormInfo.parseFrom(Pojos.readMessage(fields, 17)) : null,
            Pojos.readMessage(fields, 21) != null ? Next.pojo.PlayerBattleData.parseFrom(Pojos.readMessage(fields, 21)) : null,
            Pojos.readIntList(fields, 24),
            Pojos.readIntList(fields, 25),
            Pojos.readLongList(fields, 26),
            Pojos.readLong(fields, 27),
            Pojos.readMessageList(fields, 28).stream().map(Next.pojo.MailRecvBrief::parseFrom).toList(),
            Pojos.readMessage(fields, 51) != null ? Next.pojo.PlayerAdventureData.parseFrom(Pojos.readMessage(fields, 51)) : null,
            Pojos.readMessage(fields, 52) != null ? Next.pojo.PlayerVisitData.parseFrom(Pojos.readMessage(fields, 52)) : null,
            Pojos.readMessage(fields, 56) != null ? Next.pojo.PlayerInvestTaskData.parseFrom(Pojos.readMessage(fields, 56)) : null,
            Pojos.readMessageList(fields, 57).stream().map(Next.pojo.PlayerTeleportData::parseFrom).toList(),
            Pojos.readMessageList(fields, 59).stream().map(Next.pojo.PlayerTeachInfo::parseFrom).toList(),
            Pojos.readMessage(fields, 60) != null ? Next.pojo.PlayerActivityInfo.parseFrom(Pojos.readMessage(fields, 60)) : null,
            Pojos.readMessage(fields, 61) != null ? Next.pojo.PlayerCopyData.parseFrom(Pojos.readMessage(fields, 61)) : null,
            Pojos.readMessage(fields, 62) != null ? Next.pojo.PlayerExchangeInfo.parseFrom(Pojos.readMessage(fields, 62)) : null,
            Pojos.readMessage(fields, 63) != null ? Next.pojo.PlayerInteractInfo.parseFrom(Pojos.readMessage(fields, 63)) : null,
            Pojos.readMessage(fields, 64) != null ? Next.pojo.PlayerMageBookInfo.parseFrom(Pojos.readMessage(fields, 64)) : null,
            Pojos.readMessage(fields, 66) != null ? Next.pojo.TaskSummaryList.parseFrom(Pojos.readMessage(fields, 66)) : null,
            Pojos.readMessage(fields, 67) != null ? Next.pojo.MidasMoneyInfo.parseFrom(Pojos.readMessage(fields, 67)) : null,
            Pojos.readMessage(fields, 68) != null ? Next.pojo.PlayerShinyPetDayInfo.parseFrom(Pojos.readMessage(fields, 68)) : null,
            Pojos.readMessage(fields, 69) != null ? Next.pojo.MidasDistriBillList.parseFrom(Pojos.readMessage(fields, 69)) : null,
            Pojos.readInt(fields, 70),
            Pojos.readInt(fields, 71),
            Pojos.readMessageList(fields, 72).stream().map(Next.pojo.SpecFlowerSeed::parseFrom).toList(),
            Pojos.readMessageList(fields, 73).stream().map(Next.pojo.PlayerAreaCheckInfo::parseFrom).toList(),
            Pojos.readInt(fields, 74),
            Pojos.readMessage(fields, 75) != null ? Next.pojo.PlayerCropFruitList.parseFrom(Pojos.readMessage(fields, 75)) : null,
            Pojos.readMessage(fields, 76) != null ? Next.pojo.SceneIdipActionNpcList.parseFrom(Pojos.readMessage(fields, 76)) : null,
            Pojos.readMessage(fields, 77) != null ? Next.pojo.PlayerGiftLimitList.parseFrom(Pojos.readMessage(fields, 77)) : null,
            Pojos.readMessage(fields, 78) != null ? Next.pojo.BadgeChallengeData.parseFrom(Pojos.readMessage(fields, 78)) : null,
            Pojos.readLong(fields, 79),
            Pojos.readMessage(fields, 80) != null ? Next.pojo.SeasonInfo.parseFrom(Pojos.readMessage(fields, 80)) : null,
            Pojos.readMessage(fields, 81) != null ? Next.pojo.PlayerGiftInfo.parseFrom(Pojos.readMessage(fields, 81)) : null,
            Pojos.readMessage(fields, 82) != null ? Next.pojo.PlayerTypeGiftLimitList.parseFrom(Pojos.readMessage(fields, 82)) : null,
            Pojos.readMessageList(fields, 84).stream().map(Next.pojo.DailyGetItemLimitlist::parseFrom).toList(),
            Pojos.readMessage(fields, 85) != null ? Next.pojo.PlayerPetMedalInfo.parseFrom(Pojos.readMessage(fields, 85)) : null,
            Pojos.readMessage(fields, 86) != null ? Next.pojo.PlayerShareInfo.parseFrom(Pojos.readMessage(fields, 86)) : null,
            Pojos.readMessage(fields, 87) != null ? Next.pojo.PlayerPetEggData.parseFrom(Pojos.readMessage(fields, 87)) : null,
            Pojos.readMessage(fields, 88) != null ? Next.pojo.GoodsModifyTransAllInfo.parseFrom(Pojos.readMessage(fields, 88)) : null,
            Pojos.readMessage(fields, 89) != null ? Next.pojo.PetTeamShareData.parseFrom(Pojos.readMessage(fields, 89)) : null,
            Pojos.readMessage(fields, 90) != null ? Next.pojo.DBShop.parseFrom(Pojos.readMessage(fields, 90)) : null,
            Pojos.readLong(fields, 91),
            Pojos.readMessage(fields, 92) != null ? Next.pojo.PlayerMailFailInfo.parseFrom(Pojos.readMessage(fields, 92)) : null,
            Pojos.readMessage(fields, 93) != null ? Next.pojo.DailySendMailList.parseFrom(Pojos.readMessage(fields, 93)) : null,
            Pojos.readMessage(fields, 94) != null ? Next.pojo.PlayerSeasonAdventureData.parseFrom(Pojos.readMessage(fields, 94)) : null,
            Pojos.readMessage(fields, 95) != null ? Next.pojo.PlayerTeachingTabInfo.parseFrom(Pojos.readMessage(fields, 95)) : null,
            Pojos.readMessage(fields, 96) != null ? Next.pojo.PlayerMailDataInfo.parseFrom(Pojos.readMessage(fields, 96)) : null
        );
    }
    public static PlayerSvrDataInfo parseFrom(java.util.List<ProtoField> fields) {
        return new PlayerSvrDataInfo(
            Pojos.readInt(fields, 6),
            Pojos.readInt(fields, 7),
            Pojos.readMessage(fields, 11) != null ? Next.pojo.PlayerDungeonInfo.parseFrom(Pojos.readMessage(fields, 11)) : null,
            Pojos.readMessage(fields, 12) != null ? Next.pojo.PlayerHopeData.parseFrom(Pojos.readMessage(fields, 12)) : null,
            Pojos.readMessage(fields, 13) != null ? Next.pojo.PlayerBattlePassInfo.parseFrom(Pojos.readMessage(fields, 13)) : null,
            Pojos.readMessage(fields, 14) != null ? Next.pojo.PlayerCardInfo.parseFrom(Pojos.readMessage(fields, 14)) : null,
            Pojos.readMessage(fields, 15) != null ? Next.pojo.PlayerSubTaskInfo.parseFrom(Pojos.readMessage(fields, 15)) : null,
            Pojos.readMessage(fields, 16) != null ? Next.pojo.PlayerAppearanceInfo.parseFrom(Pojos.readMessage(fields, 16)) : null,
            Pojos.readMessage(fields, 17) != null ? Next.pojo.PlayerShareFormInfo.parseFrom(Pojos.readMessage(fields, 17)) : null,
            Pojos.readMessage(fields, 21) != null ? Next.pojo.PlayerBattleData.parseFrom(Pojos.readMessage(fields, 21)) : null,
            Pojos.readIntList(fields, 24),
            Pojos.readIntList(fields, 25),
            Pojos.readLongList(fields, 26),
            Pojos.readLong(fields, 27),
            Pojos.readMessageList(fields, 28).stream().map(Next.pojo.MailRecvBrief::parseFrom).toList(),
            Pojos.readMessage(fields, 51) != null ? Next.pojo.PlayerAdventureData.parseFrom(Pojos.readMessage(fields, 51)) : null,
            Pojos.readMessage(fields, 52) != null ? Next.pojo.PlayerVisitData.parseFrom(Pojos.readMessage(fields, 52)) : null,
            Pojos.readMessage(fields, 56) != null ? Next.pojo.PlayerInvestTaskData.parseFrom(Pojos.readMessage(fields, 56)) : null,
            Pojos.readMessageList(fields, 57).stream().map(Next.pojo.PlayerTeleportData::parseFrom).toList(),
            Pojos.readMessageList(fields, 59).stream().map(Next.pojo.PlayerTeachInfo::parseFrom).toList(),
            Pojos.readMessage(fields, 60) != null ? Next.pojo.PlayerActivityInfo.parseFrom(Pojos.readMessage(fields, 60)) : null,
            Pojos.readMessage(fields, 61) != null ? Next.pojo.PlayerCopyData.parseFrom(Pojos.readMessage(fields, 61)) : null,
            Pojos.readMessage(fields, 62) != null ? Next.pojo.PlayerExchangeInfo.parseFrom(Pojos.readMessage(fields, 62)) : null,
            Pojos.readMessage(fields, 63) != null ? Next.pojo.PlayerInteractInfo.parseFrom(Pojos.readMessage(fields, 63)) : null,
            Pojos.readMessage(fields, 64) != null ? Next.pojo.PlayerMageBookInfo.parseFrom(Pojos.readMessage(fields, 64)) : null,
            Pojos.readMessage(fields, 66) != null ? Next.pojo.TaskSummaryList.parseFrom(Pojos.readMessage(fields, 66)) : null,
            Pojos.readMessage(fields, 67) != null ? Next.pojo.MidasMoneyInfo.parseFrom(Pojos.readMessage(fields, 67)) : null,
            Pojos.readMessage(fields, 68) != null ? Next.pojo.PlayerShinyPetDayInfo.parseFrom(Pojos.readMessage(fields, 68)) : null,
            Pojos.readMessage(fields, 69) != null ? Next.pojo.MidasDistriBillList.parseFrom(Pojos.readMessage(fields, 69)) : null,
            Pojos.readInt(fields, 70),
            Pojos.readInt(fields, 71),
            Pojos.readMessageList(fields, 72).stream().map(Next.pojo.SpecFlowerSeed::parseFrom).toList(),
            Pojos.readMessageList(fields, 73).stream().map(Next.pojo.PlayerAreaCheckInfo::parseFrom).toList(),
            Pojos.readInt(fields, 74),
            Pojos.readMessage(fields, 75) != null ? Next.pojo.PlayerCropFruitList.parseFrom(Pojos.readMessage(fields, 75)) : null,
            Pojos.readMessage(fields, 76) != null ? Next.pojo.SceneIdipActionNpcList.parseFrom(Pojos.readMessage(fields, 76)) : null,
            Pojos.readMessage(fields, 77) != null ? Next.pojo.PlayerGiftLimitList.parseFrom(Pojos.readMessage(fields, 77)) : null,
            Pojos.readMessage(fields, 78) != null ? Next.pojo.BadgeChallengeData.parseFrom(Pojos.readMessage(fields, 78)) : null,
            Pojos.readLong(fields, 79),
            Pojos.readMessage(fields, 80) != null ? Next.pojo.SeasonInfo.parseFrom(Pojos.readMessage(fields, 80)) : null,
            Pojos.readMessage(fields, 81) != null ? Next.pojo.PlayerGiftInfo.parseFrom(Pojos.readMessage(fields, 81)) : null,
            Pojos.readMessage(fields, 82) != null ? Next.pojo.PlayerTypeGiftLimitList.parseFrom(Pojos.readMessage(fields, 82)) : null,
            Pojos.readMessageList(fields, 84).stream().map(Next.pojo.DailyGetItemLimitlist::parseFrom).toList(),
            Pojos.readMessage(fields, 85) != null ? Next.pojo.PlayerPetMedalInfo.parseFrom(Pojos.readMessage(fields, 85)) : null,
            Pojos.readMessage(fields, 86) != null ? Next.pojo.PlayerShareInfo.parseFrom(Pojos.readMessage(fields, 86)) : null,
            Pojos.readMessage(fields, 87) != null ? Next.pojo.PlayerPetEggData.parseFrom(Pojos.readMessage(fields, 87)) : null,
            Pojos.readMessage(fields, 88) != null ? Next.pojo.GoodsModifyTransAllInfo.parseFrom(Pojos.readMessage(fields, 88)) : null,
            Pojos.readMessage(fields, 89) != null ? Next.pojo.PetTeamShareData.parseFrom(Pojos.readMessage(fields, 89)) : null,
            Pojos.readMessage(fields, 90) != null ? Next.pojo.DBShop.parseFrom(Pojos.readMessage(fields, 90)) : null,
            Pojos.readLong(fields, 91),
            Pojos.readMessage(fields, 92) != null ? Next.pojo.PlayerMailFailInfo.parseFrom(Pojos.readMessage(fields, 92)) : null,
            Pojos.readMessage(fields, 93) != null ? Next.pojo.DailySendMailList.parseFrom(Pojos.readMessage(fields, 93)) : null,
            Pojos.readMessage(fields, 94) != null ? Next.pojo.PlayerSeasonAdventureData.parseFrom(Pojos.readMessage(fields, 94)) : null,
            Pojos.readMessage(fields, 95) != null ? Next.pojo.PlayerTeachingTabInfo.parseFrom(Pojos.readMessage(fields, 95)) : null,
            Pojos.readMessage(fields, 96) != null ? Next.pojo.PlayerMailDataInfo.parseFrom(Pojos.readMessage(fields, 96)) : null
        );
    }
}
