// Generated from com_battle.proto
package Next.pojo;

import com.roco.sniffer.codec.Pojos;
import com.roco.sniffer.codec.ProtoParser.ProtoField;
import com.roco.sniffer.codec.ProtoParser;
import java.util.List;

@SuppressWarnings("unused")
public record PvpRecord(
    int pvpId,
    int teamType,
    int k,
    double r,
    int rd,
    double vol,
    int pvpScore,
    int nextRefreshTime,
    int battleCount,
    int winCount,
    int loseCount,
    int drawCount,
    int freqBaseId,
    int killPetNum,
    int winStreak,
    int loseStreak,
    List<PvpFightHis> fightHis,
    int weekWinCount,
    int weekRefreshUt,
    List<Integer> receivedSeasonAwards,
    List<Integer> receivedWeekAwards,
    int rankSeasonId,
    PvpRecord_RedPointHistory rdHistory,
    TrialPet trialPet,
    List<Integer> matchedUins,
    List<Integer> hisRts,
    int seasonMaxRankStar,
    int lastWarmPvpTime,
    int profScore,
    int lastFinishGameTime,
    List<MagicUsedInfo> magicUsed,
    int seasonBattleCount,
    int seasonWinCount,
    int seasonMaxWinStreak,
    int prevSeasonStar,
    int pvpWinOrLoseStreak
) {
    public static PvpRecord parseFrom(byte[] data) {
        java.util.List<ProtoField> fields = ProtoParser.parse(data);
        return new PvpRecord(
            Pojos.readInt(fields, 1),
            Pojos.readInt(fields, 6),
            Pojos.readInt(fields, 2),
            Pojos.readDouble(fields, 103),
            Pojos.readInt(fields, 4),
            Pojos.readDouble(fields, 5),
            Pojos.readInt(fields, 10),
            Pojos.readInt(fields, 12),
            Pojos.readInt(fields, 20),
            Pojos.readInt(fields, 21),
            Pojos.readInt(fields, 22),
            Pojos.readInt(fields, 23),
            Pojos.readInt(fields, 24),
            Pojos.readInt(fields, 25),
            Pojos.readInt(fields, 32),
            Pojos.readInt(fields, 33),
            Pojos.readMessageList(fields, 34).stream().map(Next.pojo.PvpFightHis::parseFrom).toList(),
            Pojos.readInt(fields, 35),
            Pojos.readInt(fields, 36),
            Pojos.readIntList(fields, 37),
            Pojos.readIntList(fields, 38),
            Pojos.readInt(fields, 39),
            Pojos.readMessage(fields, 40) != null ? Next.pojo.PvpRecord_RedPointHistory.parseFrom(Pojos.readMessage(fields, 40)) : null,
            Pojos.readMessage(fields, 41) != null ? Next.pojo.TrialPet.parseFrom(Pojos.readMessage(fields, 41)) : null,
            Pojos.readIntList(fields, 42),
            Pojos.readIntList(fields, 43),
            Pojos.readInt(fields, 44),
            Pojos.readInt(fields, 45),
            Pojos.readInt(fields, 46),
            Pojos.readInt(fields, 47),
            Pojos.readMessageList(fields, 48).stream().map(Next.pojo.MagicUsedInfo::parseFrom).toList(),
            Pojos.readInt(fields, 49),
            Pojos.readInt(fields, 50),
            Pojos.readInt(fields, 51),
            Pojos.readInt(fields, 52),
            Pojos.readInt(fields, 53)
        );
    }
    public static PvpRecord parseFrom(java.util.List<ProtoField> fields) {
        return new PvpRecord(
            Pojos.readInt(fields, 1),
            Pojos.readInt(fields, 6),
            Pojos.readInt(fields, 2),
            Pojos.readDouble(fields, 103),
            Pojos.readInt(fields, 4),
            Pojos.readDouble(fields, 5),
            Pojos.readInt(fields, 10),
            Pojos.readInt(fields, 12),
            Pojos.readInt(fields, 20),
            Pojos.readInt(fields, 21),
            Pojos.readInt(fields, 22),
            Pojos.readInt(fields, 23),
            Pojos.readInt(fields, 24),
            Pojos.readInt(fields, 25),
            Pojos.readInt(fields, 32),
            Pojos.readInt(fields, 33),
            Pojos.readMessageList(fields, 34).stream().map(Next.pojo.PvpFightHis::parseFrom).toList(),
            Pojos.readInt(fields, 35),
            Pojos.readInt(fields, 36),
            Pojos.readIntList(fields, 37),
            Pojos.readIntList(fields, 38),
            Pojos.readInt(fields, 39),
            Pojos.readMessage(fields, 40) != null ? Next.pojo.PvpRecord_RedPointHistory.parseFrom(Pojos.readMessage(fields, 40)) : null,
            Pojos.readMessage(fields, 41) != null ? Next.pojo.TrialPet.parseFrom(Pojos.readMessage(fields, 41)) : null,
            Pojos.readIntList(fields, 42),
            Pojos.readIntList(fields, 43),
            Pojos.readInt(fields, 44),
            Pojos.readInt(fields, 45),
            Pojos.readInt(fields, 46),
            Pojos.readInt(fields, 47),
            Pojos.readMessageList(fields, 48).stream().map(Next.pojo.MagicUsedInfo::parseFrom).toList(),
            Pojos.readInt(fields, 49),
            Pojos.readInt(fields, 50),
            Pojos.readInt(fields, 51),
            Pojos.readInt(fields, 52),
            Pojos.readInt(fields, 53)
        );
    }
}
