// Generated from space_data.proto
package Next.pojo;

import com.roco.sniffer.codec.Pojos;
import com.roco.sniffer.codec.ProtoParser.ProtoField;
import com.roco.sniffer.codec.ProtoParser;
import java.util.List;

@SuppressWarnings("unused")
public record SceneRequiredPlayerInfo(
    String name,
    int lv,
    int gender,
    int ingameTime,
    int lastUpdateIngame,
    int hpMax,
    int worldLv,
    byte[] openid,
    byte[] clientVersion,
    boolean isReconnect,
    String clientIp,
    String clientIpv6,
    int quality,
    PlatInfo platInfo,
    ClientInfo clientInfo,
    PlayerStoryFlagInfo playerStoryFlagInfo,
    int visitOwnerUin,
    long visitOwnerObjId,
    boolean loginLeaveVisiting,
    int cardLabelFirstSelected,
    int cardLabelLastSelected,
    int cardSkinSelected,
    int cardIconSelected,
    int cardMusicId,
    List<HandbookRecord> handbookRecords,
    List<Integer> fashionItemWearData,
    List<SalonItemWearData> salonItemWearData,
    List<Integer> fashionBondData,
    List<PlayerAppearanceInfo_FashionInfo_WardrobeItem> wearingItem,
    List<SpecFlowerSeed> specFlowerSeeds,
    SnsAuthInfo snsAuthInfo,
    SceneSeasonInfo seasonInfo,
    PlayerNpcRefreshBanInfo npcRefreshBanInfo,
    List<PlayerFuncBanItem> funcBanItems,
    List<Integer> petGids,
    int currentSelectPetGid,
    List<SceneBasePetData> bigWorldPetData,
    List<Integer> mainTeamGids
) {
    public static SceneRequiredPlayerInfo parseFrom(byte[] data) {
        java.util.List<ProtoField> fields = ProtoParser.parse(data);
        return new SceneRequiredPlayerInfo(
            Pojos.readString(fields, 1),
            Pojos.readInt(fields, 2),
            Pojos.readInt(fields, 3),
            Pojos.readInt(fields, 4),
            Pojos.readInt(fields, 5),
            Pojos.readInt(fields, 6),
            Pojos.readInt(fields, 7),
            Pojos.readBytes(fields, 20),
            Pojos.readBytes(fields, 21),
            Pojos.readBool(fields, 22),
            Pojos.readString(fields, 25),
            Pojos.readString(fields, 26),
            Pojos.readInt(fields, 29),
            Pojos.readMessage(fields, 31) != null ? Next.pojo.PlatInfo.parseFrom(Pojos.readMessage(fields, 31)) : null,
            Pojos.readMessage(fields, 33) != null ? Next.pojo.ClientInfo.parseFrom(Pojos.readMessage(fields, 33)) : null,
            Pojos.readMessage(fields, 11) != null ? Next.pojo.PlayerStoryFlagInfo.parseFrom(Pojos.readMessage(fields, 11)) : null,
            Pojos.readInt(fields, 13),
            Pojos.readLong(fields, 14),
            Pojos.readBool(fields, 15),
            Pojos.readInt(fields, 16),
            Pojos.readInt(fields, 17),
            Pojos.readInt(fields, 18),
            Pojos.readInt(fields, 19),
            Pojos.readInt(fields, 24),
            Pojos.readMessageList(fields, 23).stream().map(Next.pojo.HandbookRecord::parseFrom).toList(),
            Pojos.readIntList(fields, 27),
            Pojos.readMessageList(fields, 28).stream().map(Next.pojo.SalonItemWearData::parseFrom).toList(),
            Pojos.readIntList(fields, 35),
            Pojos.readMessageList(fields, 37).stream().map(Next.pojo.PlayerAppearanceInfo_FashionInfo_WardrobeItem::parseFrom).toList(),
            Pojos.readMessageList(fields, 32).stream().map(Next.pojo.SpecFlowerSeed::parseFrom).toList(),
            Pojos.readMessage(fields, 34) != null ? Next.pojo.SnsAuthInfo.parseFrom(Pojos.readMessage(fields, 34)) : null,
            Pojos.readMessage(fields, 36) != null ? Next.pojo.SceneSeasonInfo.parseFrom(Pojos.readMessage(fields, 36)) : null,
            Pojos.readMessage(fields, 38) != null ? Next.pojo.PlayerNpcRefreshBanInfo.parseFrom(Pojos.readMessage(fields, 38)) : null,
            Pojos.readMessageList(fields, 39).stream().map(Next.pojo.PlayerFuncBanItem::parseFrom).toList(),
            Pojos.readIntList(fields, 40),
            Pojos.readInt(fields, 41),
            Pojos.readMessageList(fields, 42).stream().map(Next.pojo.SceneBasePetData::parseFrom).toList(),
            Pojos.readIntList(fields, 43)
        );
    }
    public static SceneRequiredPlayerInfo parseFrom(java.util.List<ProtoField> fields) {
        return new SceneRequiredPlayerInfo(
            Pojos.readString(fields, 1),
            Pojos.readInt(fields, 2),
            Pojos.readInt(fields, 3),
            Pojos.readInt(fields, 4),
            Pojos.readInt(fields, 5),
            Pojos.readInt(fields, 6),
            Pojos.readInt(fields, 7),
            Pojos.readBytes(fields, 20),
            Pojos.readBytes(fields, 21),
            Pojos.readBool(fields, 22),
            Pojos.readString(fields, 25),
            Pojos.readString(fields, 26),
            Pojos.readInt(fields, 29),
            Pojos.readMessage(fields, 31) != null ? Next.pojo.PlatInfo.parseFrom(Pojos.readMessage(fields, 31)) : null,
            Pojos.readMessage(fields, 33) != null ? Next.pojo.ClientInfo.parseFrom(Pojos.readMessage(fields, 33)) : null,
            Pojos.readMessage(fields, 11) != null ? Next.pojo.PlayerStoryFlagInfo.parseFrom(Pojos.readMessage(fields, 11)) : null,
            Pojos.readInt(fields, 13),
            Pojos.readLong(fields, 14),
            Pojos.readBool(fields, 15),
            Pojos.readInt(fields, 16),
            Pojos.readInt(fields, 17),
            Pojos.readInt(fields, 18),
            Pojos.readInt(fields, 19),
            Pojos.readInt(fields, 24),
            Pojos.readMessageList(fields, 23).stream().map(Next.pojo.HandbookRecord::parseFrom).toList(),
            Pojos.readIntList(fields, 27),
            Pojos.readMessageList(fields, 28).stream().map(Next.pojo.SalonItemWearData::parseFrom).toList(),
            Pojos.readIntList(fields, 35),
            Pojos.readMessageList(fields, 37).stream().map(Next.pojo.PlayerAppearanceInfo_FashionInfo_WardrobeItem::parseFrom).toList(),
            Pojos.readMessageList(fields, 32).stream().map(Next.pojo.SpecFlowerSeed::parseFrom).toList(),
            Pojos.readMessage(fields, 34) != null ? Next.pojo.SnsAuthInfo.parseFrom(Pojos.readMessage(fields, 34)) : null,
            Pojos.readMessage(fields, 36) != null ? Next.pojo.SceneSeasonInfo.parseFrom(Pojos.readMessage(fields, 36)) : null,
            Pojos.readMessage(fields, 38) != null ? Next.pojo.PlayerNpcRefreshBanInfo.parseFrom(Pojos.readMessage(fields, 38)) : null,
            Pojos.readMessageList(fields, 39).stream().map(Next.pojo.PlayerFuncBanItem::parseFrom).toList(),
            Pojos.readIntList(fields, 40),
            Pojos.readInt(fields, 41),
            Pojos.readMessageList(fields, 42).stream().map(Next.pojo.SceneBasePetData::parseFrom).toList(),
            Pojos.readIntList(fields, 43)
        );
    }
}
