// Generated from space_action.proto
package Next.pojo;

import io.github.kedaya0209.roco.sniffer.codec.Pojos;
import io.github.kedaya0209.roco.sniffer.codec.ProtoParser.ProtoField;
import io.github.kedaya0209.roco.sniffer.codec.ProtoParser;

@SuppressWarnings("unused")
public record SpaceActionCollection(
    SpaceAct_ActorEnter actorEnter,
    SpaceAct_ActorLeave actorLeave,
    SpaceAct_ActorNum actorNum,
    SpaceAct_ClientMove clientMove,
    SpaceAct_ServerMove serverMove,
    SpaceAct_InterruptServerMove interruptServerMove,
    SpaceAct_LookAt lookAt,
    SpaceAct_TurnTo turnTo,
    SpaceAct_CancelTurnTo cancelTurnTo,
    SpaceAct_ServerFly serverFly,
    SpaceAct_ServerAttach serverAttach,
    SpaceAct_CancelServerAttach cancelServerAttach,
    SpaceAct_AddStoryFlags addStoryFlags,
    SpaceAct_RemoveStoryFlags removeStoryFlags,
    SpaceAct_NpcOptionInfoChange npcOptionInfoChange,
    SpaceAct_NpcOptionAddSelects npcOptionAddSelects,
    SpaceAct_NpcOptionRemoveSelects npcOptionRemoveSelects,
    SpaceAct_NpcDialogSelectInfoChange npcDialogSelectInfoChange,
    SpaceAct_AddNpcOption addNpcOption,
    SpaceAct_RemoveNpcOption removeNpcOption,
    SpaceAct_BeginActResultParamsNty beginActResultParamsNty,
    SpaceAct_NpcCanbeTeleportNty npcCanBeTeleportNty,
    SpaceAct_UpdateActorLogicStatus updateActorLogicStatus,
    SpaceAct_CombineLockStateChange combineLockStateChange,
    SpaceAct_TrackingNpc trackingNpcs,
    SpaceAct_VisibleZone visiblePlayers,
    SpaceAct_SyncPlayerStatus syncPlayerStatus,
    SpaceAct_PotentialEnergyChange potentialEnergyChange,
    SpaceAct_EnvMask envMask,
    SpaceAct_PropertyTypeChange propertyTypeChange,
    SpaceAct_ActorBornEnd actorBornEnd,
    SpaceAct_ActorDieBegin actorDieBegin,
    SpaceAct_BeginDropItem beginDropItem,
    SpaceAct_EndDropItem endDropItem,
    SpaceAct_AttrChange attrChange,
    SpaceAct_EnteredCatcher entertedCatcher,
    SpaceAct_LeftCatcher leftCatcher,
    SpaceAct_PlayAnimation playAnimation,
    SpaceAct_StopAnimation stopAnimation,
    SpaceAct_AnimPauseOrResume animPauseOrResume,
    SpaceAct_PlaySkill playSkill,
    SpaceAct_StopSkill stopSkill,
    SpaceAct_WorldHidden worldHidden,
    SpaceAct_WorldUnHidden worldUnhidden,
    SpaceAct_PlayZoomAnimation playZoomAnimation,
    SpaceAct_PlayAnimBeforeRemove playAnimBeforeRemove,
    SpaceAct_ShowPetFaceState showPetFaceState,
    SpaceAct_ModelDisplay modelShowOrHide,
    SpaceAct_PlayPerceptionEffect playPerceptionEffect,
    SpaceAct_PlayPerceptionHud playPerceptionHud,
    SpaceAct_NpcTrace npcTrace,
    SpaceAct_NpcPerceivePlayer npcPerceivePlayer,
    SpaceAct_BattleOnOff battleOnOrOff,
    SpaceAct_WorldAttack worldAttack,
    SpaceAct_StopWorldAttack stopWorldAttack,
    SpaceAct_MfbtDebug mfbtDebug,
    SpaceAct_BattleAIStatusChanged battleAiStatusChanged,
    SpaceAct_SceneAiControlFlagsChanged sceneAiControlFlagsChanged,
    SpaceAct_ServerAIJump serverAiJump,
    SpaceAct_CancelServerAIJump cancelServerAiJump,
    SpaceAct_StickTo stickTo,
    SpaceAct_FinishStickTo finishStickTo,
    SpaceAct_AITryInteractNpc aiTryInteractNpc,
    SpaceAct_SwitchBossAINty switchBossAiNty,
    SpaceAct_AIMoveMode moveMode,
    SpaceAct_InformClientSwitchAINty informClientSwitchAi,
    SpaceAct_ClientSwitchToServerAINty clientSwitchToServerAi,
    SpaceAct_CastSceneSkill castSceneSkill,
    SpaceAct_FriendRide friendRide,
    SpaceAct_CollisionCancelRecover collisionCancelOrRecover,
    SpaceAct_ChangeSceneNotify changeSceneNotify,
    SpaceAct_AuraInfoChange auraInfoChange,
    SpaceAct_BodyTempNotify bodyTempNotify,
    SpaceAct_ThrowedPetInfoChange throwedPetInfo,
    SpaceAct_DelThrowingMagic delThrowingMagic,
    SpaceAct_DeleteThrowNotify throwCatchNotify,
    SpaceAct_AirWallChange airWallChange,
    SpaceAct_WeatherChange weatherChange,
    SpaceAct_GameTimeChange gameTimeChange,
    SpaceAct_MinigameNotify minigame,
    SpaceAct_GuideTask guideNpcs,
    SpaceAct_ClientEventResume clientEventResume,
    SpaceAct_NpcPendantInfoChange npcPendantInfoChange,
    SpaceAct_UnlockSleepingOwl unlockSleepingOwl,
    SpaceAct_OwlRefugeInfoChange owlRefugeInfoChange,
    SpaceAct_NpcDistribution npcDistribution,
    SpaceAct_HeadLookAt headLookAt,
    SpaceAct_FashionChange fashionChange,
    SpaceAct_SalonChange salonChange,
    SpaceAct_ClientOperation clientOperation,
    SpaceAct_BondFind bondFind,
    SpaceAct_ScenePetInfoChange petInfoChange,
    SpaceAct_SceneDotsComponentSync dotsComponentSync,
    SpaceAct_GameTimeSync gameTimeSync,
    SpaceAct_PetInteractResNty petInteractResNty,
    SpaceAct_CombineInteractInfoChange combineInteractInfoChange,
    SpaceAct_BuffInfoChange buffInfoChange,
    SpaceAct_NameChange nameChange,
    SpaceAct_RelatedNpcInfosChanged relateNpcInfosChange,
    SpaceAct_WorldMapInfoChanged worldMapInfosChange,
    SpaceAct_SetNpcPos setNpcPos,
    SpaceAct_PlayVoice playVoice,
    SpaceAct_StopVoice stopVoice,
    SpaceAct_NpcGuideChange npcGuideChange,
    SpaceAct_ChangeLoopAction loopAction,
    SpaceAct_CatchGuaranteeChange catchGuaranteeChange,
    SpaceAct_PlayerMatch playerMatch,
    SpaceAct_NpcVisualInfoChange npcVisualInfo,
    SpaceAct_BattleBuffInfoChanged battleBuffInfoChange,
    SpaceAct_CardLabelChange cardLabelChange,
    SpaceAct_CardSkinChange cardSkinChange,
    SpaceAct_SameCellTeleport sameCellTeleport,
    SpaceAct_FollowInfoChangedNty followInfoChangedNty,
    SpaceAct_CollectHandbookRecordsChange collectHandbookRecordsChange,
    SpaceAct_PositionInvalid positionInvalid,
    SpaceAct_TaskStateChangeNty taskStateChangeNty,
    SpaceAct_PlayRealtimeDialog playRealTimeDialog,
    SpaceAct_StopRealtimeDialog stopRealTimeDialog,
    SpaceAct_CardMusicChange cardMusicChange,
    SpaceAct_MagicCreateNpcChange magicCreateNpcChange,
    SpaceAct_VelocityOrientedRotation velocityOrientedRotation,
    SpaceAct_WorldLaunchPlayer worldLaunchPlayer,
    SpaceAct_AIPerformGroupIdChanged aiPerformGroupIdChanged,
    SpaceAct_OptActionNtf optActionNtf,
    SpaceAct_CardIconChange cardIconChange,
    SpaceAct_VideoRecord videoRecord,
    SpaceAct_Stun stun,
    SpaceAct_CatchRecordInfoChange catchRecordInfoChange,
    SpaceAct_HabitatNeighborInfoChange habitatNeighborInfoChange,
    SpaceAct_AllHabitatNeighborInfo allHabitatNeighborInfo,
    SpaceAct_WorldCombatEnter worldCombatEnter,
    SpaceAct_WorldCombatExit worldCombatExit,
    SpaceAct_WorldCombatTextPrompts worldCombatTextPrompts,
    SpaceAct_WorldCombatPhaseUpdate worldCombatPhaseUpdate,
    SpaceAct_WorldCombatBegin worldCombatBegin,
    SpaceAct_WorldCombatFinish worldCombatFinish,
    SpaceAct_WorldCombatDotsSkillCast worldCombatDotsSkillCast,
    SpaceAct_WorldCombatDotsSkillEnd worldCombatDotsSkillEnd,
    SpaceAct_WorldCombatDotsSkillCrush worldCombatDotsSkillCrush,
    SpaceAct_WorldCombatDotsSkillHit worldCombatDotsSkillHit,
    SpaceAct_WorldCombatDotsSkillRotate worldCombatDotsSkillRotate,
    SpaceAct_WorldCombatDotsSkillLookAt worldCombatDotsSkillLookat,
    SpaceAct_WorldCombatDotsSkillCrushEnd worldCombatDotsSkillCrushEnd,
    SpaceAct_WorldCombatDotsSkillMissileLaunch worldCombatDotsSkillMissileLaunch,
    SpaceAct_WorldCombatDotsSkillMissileDestroy worldCombatDotsSkillMissileDestroy,
    SpaceAct_WorldCombatDotsSkillMissileStopTrace worldCombatDotsSkillMissileStopTrace,
    SpaceAct_WorldCombatDotsSkillJump worldCombatDotsSkillJump,
    SpaceAct_WorldCombatDotsSkillJumpCancel worldCombatDotsSkillJumpCancel,
    SpaceAct_WorldCombatDotsSkillRcd worldCombatDotsSkillRcd,
    SpaceAct_WorldCombatExtraRewardUpdate worldCombatExtraRewardUpdate,
    SpaceAct_WorldCombatDotsSkillSelectPos worldCombatDotsSkillSelectPos,
    SpaceAct_OwlSanctuaryDetected owlSanctuaryDetected,
    SpaceAct_WorldCombatDotsSkillJumpEnd worldCombatDotsSkillJumpEnd,
    SpaceAct_WorldCombatDotsSkillRcdEnd worldCombatDotsSkillRcdEnd,
    SpaceAct_WorldCombatDotsSkillHidden worldCombatDotsSkillHidden,
    SpaceAct_WorldCombatDotsSkillHiddenEnd worldCombatDotsSkillHiddenEnd,
    SpaceAct_OwlSanctuaryFruitInfoUpdate owlSanctuaryFruitInfoUpdate,
    SpaceAct_SceneSvrErrEcho scenesvrErrEcho,
    SpaceAct_WorldCombatDotsSkillShowHideChange worldCombatDotsSkillShowHide,
    SpaceAct_WorldCombatDotsSkillPosLerpSync worldCombatDotsSkillPosLerpSync,
    SpaceAct_WorldCombatDotsSkillAnimCancel worldCombatDotsSkillAnimCancel,
    SpaceAct_HomeBasicInfoChangeNotify homeBasicInfoChangeNotify,
    SpaceAct_HomePetInfoChangeNotify homePetInfoChangeNotify,
    SpaceAct_HomePlantChangeNotify homePlantChangeNotify,
    SpaceAct_HomePlantPlantCrop homePlantPlantCrop,
    SpaceAct_HomePlantRoleWater homePlantRoleWater,
    SpaceAct_HomePlantPetWater homePlantPetWater,
    SpaceAct_HomePlantRoleManure homePlantRoleManure,
    SpaceAct_HomePlantPetManure homePlantPetManure,
    SpaceAct_HomePlantOwnerPick homePlantOwnerPick,
    SpaceAct_HomePlantVisitorPick homePlantVisitorPick,
    SpaceAct_HomeBasicVisitorEnterHome homeBasicVisitorEnterHome,
    SpaceAct_HomeBasicVisitorLeavingHome homeBasicVisitorLeavingHome,
    SpaceAct_ActorPlantDataUpdate actorPlantDataUpdate,
    SpaceAct_TravelTogetherSync travelTogetherSync,
    SpaceAct_InnerBattle innerBattle,
    SpaceAct_InnerBattleShieldBroken innerBattleShieldBroken,
    SpaceAct_InnerBattleChangePet innerBattleChangePet,
    SpaceAct_ActorKeepModel actorKeepModel,
    SpaceAct_HomeInteractNotify homeInteractNotify,
    SpaceAct_PetClosenessLvUpgrade petClosenessLvUpgrade,
    SpaceAct_CameraFlash cameraFlash,
    SpaceAct_IdleSkill idleSkill,
    SpaceAct_PetVoice petVoice,
    SpaceAct_VisibleCircle visibleCircle,
    SpaceAct_AvatarStoryFlags storyFlags,
    SpaceAct_AISeqIdNotify aiSeqIdNotify
) {
    public static SpaceActionCollection parseFrom(byte[] data) {
        java.util.List<ProtoField> fields = ProtoParser.parse(data);
        return new SpaceActionCollection(
            Pojos.readMessage(fields, 1) != null ? Next.pojo.SpaceAct_ActorEnter.parseFrom(Pojos.readMessage(fields, 1)) : null,
            Pojos.readMessage(fields, 2) != null ? Next.pojo.SpaceAct_ActorLeave.parseFrom(Pojos.readMessage(fields, 2)) : null,
            Pojos.readMessage(fields, 3) != null ? Next.pojo.SpaceAct_ActorNum.parseFrom(Pojos.readMessage(fields, 3)) : null,
            Pojos.readMessage(fields, 11) != null ? Next.pojo.SpaceAct_ClientMove.parseFrom(Pojos.readMessage(fields, 11)) : null,
            Pojos.readMessage(fields, 12) != null ? Next.pojo.SpaceAct_ServerMove.parseFrom(Pojos.readMessage(fields, 12)) : null,
            Pojos.readMessage(fields, 13) != null ? Next.pojo.SpaceAct_InterruptServerMove.parseFrom(Pojos.readMessage(fields, 13)) : null,
            Pojos.readMessage(fields, 15) != null ? Next.pojo.SpaceAct_LookAt.parseFrom(Pojos.readMessage(fields, 15)) : null,
            Pojos.readMessage(fields, 16) != null ? Next.pojo.SpaceAct_TurnTo.parseFrom(Pojos.readMessage(fields, 16)) : null,
            Pojos.readMessage(fields, 17) != null ? Next.pojo.SpaceAct_CancelTurnTo.parseFrom(Pojos.readMessage(fields, 17)) : null,
            Pojos.readMessage(fields, 18) != null ? Next.pojo.SpaceAct_ServerFly.parseFrom(Pojos.readMessage(fields, 18)) : null,
            Pojos.readMessage(fields, 19) != null ? Next.pojo.SpaceAct_ServerAttach.parseFrom(Pojos.readMessage(fields, 19)) : null,
            Pojos.readMessage(fields, 20) != null ? Next.pojo.SpaceAct_CancelServerAttach.parseFrom(Pojos.readMessage(fields, 20)) : null,
            Pojos.readMessage(fields, 21) != null ? Next.pojo.SpaceAct_AddStoryFlags.parseFrom(Pojos.readMessage(fields, 21)) : null,
            Pojos.readMessage(fields, 22) != null ? Next.pojo.SpaceAct_RemoveStoryFlags.parseFrom(Pojos.readMessage(fields, 22)) : null,
            Pojos.readMessage(fields, 23) != null ? Next.pojo.SpaceAct_NpcOptionInfoChange.parseFrom(Pojos.readMessage(fields, 23)) : null,
            Pojos.readMessage(fields, 24) != null ? Next.pojo.SpaceAct_NpcOptionAddSelects.parseFrom(Pojos.readMessage(fields, 24)) : null,
            Pojos.readMessage(fields, 25) != null ? Next.pojo.SpaceAct_NpcOptionRemoveSelects.parseFrom(Pojos.readMessage(fields, 25)) : null,
            Pojos.readMessage(fields, 26) != null ? Next.pojo.SpaceAct_NpcDialogSelectInfoChange.parseFrom(Pojos.readMessage(fields, 26)) : null,
            Pojos.readMessage(fields, 27) != null ? Next.pojo.SpaceAct_AddNpcOption.parseFrom(Pojos.readMessage(fields, 27)) : null,
            Pojos.readMessage(fields, 28) != null ? Next.pojo.SpaceAct_RemoveNpcOption.parseFrom(Pojos.readMessage(fields, 28)) : null,
            Pojos.readMessage(fields, 29) != null ? Next.pojo.SpaceAct_BeginActResultParamsNty.parseFrom(Pojos.readMessage(fields, 29)) : null,
            Pojos.readMessage(fields, 30) != null ? Next.pojo.SpaceAct_NpcCanbeTeleportNty.parseFrom(Pojos.readMessage(fields, 30)) : null,
            Pojos.readMessage(fields, 31) != null ? Next.pojo.SpaceAct_UpdateActorLogicStatus.parseFrom(Pojos.readMessage(fields, 31)) : null,
            Pojos.readMessage(fields, 32) != null ? Next.pojo.SpaceAct_CombineLockStateChange.parseFrom(Pojos.readMessage(fields, 32)) : null,
            Pojos.readMessage(fields, 33) != null ? Next.pojo.SpaceAct_TrackingNpc.parseFrom(Pojos.readMessage(fields, 33)) : null,
            Pojos.readMessage(fields, 34) != null ? Next.pojo.SpaceAct_VisibleZone.parseFrom(Pojos.readMessage(fields, 34)) : null,
            Pojos.readMessage(fields, 35) != null ? Next.pojo.SpaceAct_SyncPlayerStatus.parseFrom(Pojos.readMessage(fields, 35)) : null,
            Pojos.readMessage(fields, 36) != null ? Next.pojo.SpaceAct_PotentialEnergyChange.parseFrom(Pojos.readMessage(fields, 36)) : null,
            Pojos.readMessage(fields, 37) != null ? Next.pojo.SpaceAct_EnvMask.parseFrom(Pojos.readMessage(fields, 37)) : null,
            Pojos.readMessage(fields, 38) != null ? Next.pojo.SpaceAct_PropertyTypeChange.parseFrom(Pojos.readMessage(fields, 38)) : null,
            Pojos.readMessage(fields, 39) != null ? Next.pojo.SpaceAct_ActorBornEnd.parseFrom(Pojos.readMessage(fields, 39)) : null,
            Pojos.readMessage(fields, 40) != null ? Next.pojo.SpaceAct_ActorDieBegin.parseFrom(Pojos.readMessage(fields, 40)) : null,
            Pojos.readMessage(fields, 41) != null ? Next.pojo.SpaceAct_BeginDropItem.parseFrom(Pojos.readMessage(fields, 41)) : null,
            Pojos.readMessage(fields, 42) != null ? Next.pojo.SpaceAct_EndDropItem.parseFrom(Pojos.readMessage(fields, 42)) : null,
            Pojos.readMessage(fields, 51) != null ? Next.pojo.SpaceAct_AttrChange.parseFrom(Pojos.readMessage(fields, 51)) : null,
            Pojos.readMessage(fields, 61) != null ? Next.pojo.SpaceAct_EnteredCatcher.parseFrom(Pojos.readMessage(fields, 61)) : null,
            Pojos.readMessage(fields, 62) != null ? Next.pojo.SpaceAct_LeftCatcher.parseFrom(Pojos.readMessage(fields, 62)) : null,
            Pojos.readMessage(fields, 71) != null ? Next.pojo.SpaceAct_PlayAnimation.parseFrom(Pojos.readMessage(fields, 71)) : null,
            Pojos.readMessage(fields, 72) != null ? Next.pojo.SpaceAct_StopAnimation.parseFrom(Pojos.readMessage(fields, 72)) : null,
            Pojos.readMessage(fields, 73) != null ? Next.pojo.SpaceAct_AnimPauseOrResume.parseFrom(Pojos.readMessage(fields, 73)) : null,
            Pojos.readMessage(fields, 74) != null ? Next.pojo.SpaceAct_PlaySkill.parseFrom(Pojos.readMessage(fields, 74)) : null,
            Pojos.readMessage(fields, 75) != null ? Next.pojo.SpaceAct_StopSkill.parseFrom(Pojos.readMessage(fields, 75)) : null,
            Pojos.readMessage(fields, 76) != null ? Next.pojo.SpaceAct_WorldHidden.parseFrom(Pojos.readMessage(fields, 76)) : null,
            Pojos.readMessage(fields, 77) != null ? Next.pojo.SpaceAct_WorldUnHidden.parseFrom(Pojos.readMessage(fields, 77)) : null,
            Pojos.readMessage(fields, 78) != null ? Next.pojo.SpaceAct_PlayZoomAnimation.parseFrom(Pojos.readMessage(fields, 78)) : null,
            Pojos.readMessage(fields, 80) != null ? Next.pojo.SpaceAct_PlayAnimBeforeRemove.parseFrom(Pojos.readMessage(fields, 80)) : null,
            Pojos.readMessage(fields, 81) != null ? Next.pojo.SpaceAct_ShowPetFaceState.parseFrom(Pojos.readMessage(fields, 81)) : null,
            Pojos.readMessage(fields, 82) != null ? Next.pojo.SpaceAct_ModelDisplay.parseFrom(Pojos.readMessage(fields, 82)) : null,
            Pojos.readMessage(fields, 83) != null ? Next.pojo.SpaceAct_PlayPerceptionEffect.parseFrom(Pojos.readMessage(fields, 83)) : null,
            Pojos.readMessage(fields, 84) != null ? Next.pojo.SpaceAct_PlayPerceptionHud.parseFrom(Pojos.readMessage(fields, 84)) : null,
            Pojos.readMessage(fields, 85) != null ? Next.pojo.SpaceAct_NpcTrace.parseFrom(Pojos.readMessage(fields, 85)) : null,
            Pojos.readMessage(fields, 86) != null ? Next.pojo.SpaceAct_NpcPerceivePlayer.parseFrom(Pojos.readMessage(fields, 86)) : null,
            Pojos.readMessage(fields, 91) != null ? Next.pojo.SpaceAct_BattleOnOff.parseFrom(Pojos.readMessage(fields, 91)) : null,
            Pojos.readMessage(fields, 92) != null ? Next.pojo.SpaceAct_WorldAttack.parseFrom(Pojos.readMessage(fields, 92)) : null,
            Pojos.readMessage(fields, 93) != null ? Next.pojo.SpaceAct_StopWorldAttack.parseFrom(Pojos.readMessage(fields, 93)) : null,
            Pojos.readMessage(fields, 101) != null ? Next.pojo.SpaceAct_MfbtDebug.parseFrom(Pojos.readMessage(fields, 101)) : null,
            Pojos.readMessage(fields, 102) != null ? Next.pojo.SpaceAct_BattleAIStatusChanged.parseFrom(Pojos.readMessage(fields, 102)) : null,
            Pojos.readMessage(fields, 103) != null ? Next.pojo.SpaceAct_SceneAiControlFlagsChanged.parseFrom(Pojos.readMessage(fields, 103)) : null,
            Pojos.readMessage(fields, 104) != null ? Next.pojo.SpaceAct_ServerAIJump.parseFrom(Pojos.readMessage(fields, 104)) : null,
            Pojos.readMessage(fields, 105) != null ? Next.pojo.SpaceAct_CancelServerAIJump.parseFrom(Pojos.readMessage(fields, 105)) : null,
            Pojos.readMessage(fields, 106) != null ? Next.pojo.SpaceAct_StickTo.parseFrom(Pojos.readMessage(fields, 106)) : null,
            Pojos.readMessage(fields, 107) != null ? Next.pojo.SpaceAct_FinishStickTo.parseFrom(Pojos.readMessage(fields, 107)) : null,
            Pojos.readMessage(fields, 108) != null ? Next.pojo.SpaceAct_AITryInteractNpc.parseFrom(Pojos.readMessage(fields, 108)) : null,
            Pojos.readMessage(fields, 109) != null ? Next.pojo.SpaceAct_SwitchBossAINty.parseFrom(Pojos.readMessage(fields, 109)) : null,
            Pojos.readMessage(fields, 110) != null ? Next.pojo.SpaceAct_AIMoveMode.parseFrom(Pojos.readMessage(fields, 110)) : null,
            Pojos.readMessage(fields, 112) != null ? Next.pojo.SpaceAct_InformClientSwitchAINty.parseFrom(Pojos.readMessage(fields, 112)) : null,
            Pojos.readMessage(fields, 113) != null ? Next.pojo.SpaceAct_ClientSwitchToServerAINty.parseFrom(Pojos.readMessage(fields, 113)) : null,
            Pojos.readMessage(fields, 111) != null ? Next.pojo.SpaceAct_CastSceneSkill.parseFrom(Pojos.readMessage(fields, 111)) : null,
            Pojos.readMessage(fields, 121) != null ? Next.pojo.SpaceAct_FriendRide.parseFrom(Pojos.readMessage(fields, 121)) : null,
            Pojos.readMessage(fields, 131) != null ? Next.pojo.SpaceAct_CollisionCancelRecover.parseFrom(Pojos.readMessage(fields, 131)) : null,
            Pojos.readMessage(fields, 141) != null ? Next.pojo.SpaceAct_ChangeSceneNotify.parseFrom(Pojos.readMessage(fields, 141)) : null,
            Pojos.readMessage(fields, 151) != null ? Next.pojo.SpaceAct_AuraInfoChange.parseFrom(Pojos.readMessage(fields, 151)) : null,
            Pojos.readMessage(fields, 161) != null ? Next.pojo.SpaceAct_BodyTempNotify.parseFrom(Pojos.readMessage(fields, 161)) : null,
            Pojos.readMessage(fields, 171) != null ? Next.pojo.SpaceAct_ThrowedPetInfoChange.parseFrom(Pojos.readMessage(fields, 171)) : null,
            Pojos.readMessage(fields, 172) != null ? Next.pojo.SpaceAct_DelThrowingMagic.parseFrom(Pojos.readMessage(fields, 172)) : null,
            Pojos.readMessage(fields, 173) != null ? Next.pojo.SpaceAct_DeleteThrowNotify.parseFrom(Pojos.readMessage(fields, 173)) : null,
            Pojos.readMessage(fields, 182) != null ? Next.pojo.SpaceAct_AirWallChange.parseFrom(Pojos.readMessage(fields, 182)) : null,
            Pojos.readMessage(fields, 191) != null ? Next.pojo.SpaceAct_WeatherChange.parseFrom(Pojos.readMessage(fields, 191)) : null,
            Pojos.readMessage(fields, 200) != null ? Next.pojo.SpaceAct_GameTimeChange.parseFrom(Pojos.readMessage(fields, 200)) : null,
            Pojos.readMessage(fields, 201) != null ? Next.pojo.SpaceAct_MinigameNotify.parseFrom(Pojos.readMessage(fields, 201)) : null,
            Pojos.readMessage(fields, 202) != null ? Next.pojo.SpaceAct_GuideTask.parseFrom(Pojos.readMessage(fields, 202)) : null,
            Pojos.readMessage(fields, 203) != null ? Next.pojo.SpaceAct_ClientEventResume.parseFrom(Pojos.readMessage(fields, 203)) : null,
            Pojos.readMessage(fields, 204) != null ? Next.pojo.SpaceAct_NpcPendantInfoChange.parseFrom(Pojos.readMessage(fields, 204)) : null,
            Pojos.readMessage(fields, 205) != null ? Next.pojo.SpaceAct_UnlockSleepingOwl.parseFrom(Pojos.readMessage(fields, 205)) : null,
            Pojos.readMessage(fields, 206) != null ? Next.pojo.SpaceAct_OwlRefugeInfoChange.parseFrom(Pojos.readMessage(fields, 206)) : null,
            Pojos.readMessage(fields, 207) != null ? Next.pojo.SpaceAct_NpcDistribution.parseFrom(Pojos.readMessage(fields, 207)) : null,
            Pojos.readMessage(fields, 208) != null ? Next.pojo.SpaceAct_HeadLookAt.parseFrom(Pojos.readMessage(fields, 208)) : null,
            Pojos.readMessage(fields, 209) != null ? Next.pojo.SpaceAct_FashionChange.parseFrom(Pojos.readMessage(fields, 209)) : null,
            Pojos.readMessage(fields, 210) != null ? Next.pojo.SpaceAct_SalonChange.parseFrom(Pojos.readMessage(fields, 210)) : null,
            Pojos.readMessage(fields, 211) != null ? Next.pojo.SpaceAct_ClientOperation.parseFrom(Pojos.readMessage(fields, 211)) : null,
            Pojos.readMessage(fields, 212) != null ? Next.pojo.SpaceAct_BondFind.parseFrom(Pojos.readMessage(fields, 212)) : null,
            Pojos.readMessage(fields, 213) != null ? Next.pojo.SpaceAct_ScenePetInfoChange.parseFrom(Pojos.readMessage(fields, 213)) : null,
            Pojos.readMessage(fields, 214) != null ? Next.pojo.SpaceAct_SceneDotsComponentSync.parseFrom(Pojos.readMessage(fields, 214)) : null,
            Pojos.readMessage(fields, 215) != null ? Next.pojo.SpaceAct_GameTimeSync.parseFrom(Pojos.readMessage(fields, 215)) : null,
            Pojos.readMessage(fields, 216) != null ? Next.pojo.SpaceAct_PetInteractResNty.parseFrom(Pojos.readMessage(fields, 216)) : null,
            Pojos.readMessage(fields, 217) != null ? Next.pojo.SpaceAct_CombineInteractInfoChange.parseFrom(Pojos.readMessage(fields, 217)) : null,
            Pojos.readMessage(fields, 218) != null ? Next.pojo.SpaceAct_BuffInfoChange.parseFrom(Pojos.readMessage(fields, 218)) : null,
            Pojos.readMessage(fields, 219) != null ? Next.pojo.SpaceAct_NameChange.parseFrom(Pojos.readMessage(fields, 219)) : null,
            Pojos.readMessage(fields, 220) != null ? Next.pojo.SpaceAct_RelatedNpcInfosChanged.parseFrom(Pojos.readMessage(fields, 220)) : null,
            Pojos.readMessage(fields, 221) != null ? Next.pojo.SpaceAct_WorldMapInfoChanged.parseFrom(Pojos.readMessage(fields, 221)) : null,
            Pojos.readMessage(fields, 222) != null ? Next.pojo.SpaceAct_SetNpcPos.parseFrom(Pojos.readMessage(fields, 222)) : null,
            Pojos.readMessage(fields, 223) != null ? Next.pojo.SpaceAct_PlayVoice.parseFrom(Pojos.readMessage(fields, 223)) : null,
            Pojos.readMessage(fields, 224) != null ? Next.pojo.SpaceAct_StopVoice.parseFrom(Pojos.readMessage(fields, 224)) : null,
            Pojos.readMessage(fields, 225) != null ? Next.pojo.SpaceAct_NpcGuideChange.parseFrom(Pojos.readMessage(fields, 225)) : null,
            Pojos.readMessage(fields, 226) != null ? Next.pojo.SpaceAct_ChangeLoopAction.parseFrom(Pojos.readMessage(fields, 226)) : null,
            Pojos.readMessage(fields, 227) != null ? Next.pojo.SpaceAct_CatchGuaranteeChange.parseFrom(Pojos.readMessage(fields, 227)) : null,
            Pojos.readMessage(fields, 228) != null ? Next.pojo.SpaceAct_PlayerMatch.parseFrom(Pojos.readMessage(fields, 228)) : null,
            Pojos.readMessage(fields, 229) != null ? Next.pojo.SpaceAct_NpcVisualInfoChange.parseFrom(Pojos.readMessage(fields, 229)) : null,
            Pojos.readMessage(fields, 230) != null ? Next.pojo.SpaceAct_BattleBuffInfoChanged.parseFrom(Pojos.readMessage(fields, 230)) : null,
            Pojos.readMessage(fields, 231) != null ? Next.pojo.SpaceAct_CardLabelChange.parseFrom(Pojos.readMessage(fields, 231)) : null,
            Pojos.readMessage(fields, 232) != null ? Next.pojo.SpaceAct_CardSkinChange.parseFrom(Pojos.readMessage(fields, 232)) : null,
            Pojos.readMessage(fields, 233) != null ? Next.pojo.SpaceAct_SameCellTeleport.parseFrom(Pojos.readMessage(fields, 233)) : null,
            Pojos.readMessage(fields, 234) != null ? Next.pojo.SpaceAct_FollowInfoChangedNty.parseFrom(Pojos.readMessage(fields, 234)) : null,
            Pojos.readMessage(fields, 235) != null ? Next.pojo.SpaceAct_CollectHandbookRecordsChange.parseFrom(Pojos.readMessage(fields, 235)) : null,
            Pojos.readMessage(fields, 236) != null ? Next.pojo.SpaceAct_PositionInvalid.parseFrom(Pojos.readMessage(fields, 236)) : null,
            Pojos.readMessage(fields, 237) != null ? Next.pojo.SpaceAct_TaskStateChangeNty.parseFrom(Pojos.readMessage(fields, 237)) : null,
            Pojos.readMessage(fields, 238) != null ? Next.pojo.SpaceAct_PlayRealtimeDialog.parseFrom(Pojos.readMessage(fields, 238)) : null,
            Pojos.readMessage(fields, 239) != null ? Next.pojo.SpaceAct_StopRealtimeDialog.parseFrom(Pojos.readMessage(fields, 239)) : null,
            Pojos.readMessage(fields, 240) != null ? Next.pojo.SpaceAct_CardMusicChange.parseFrom(Pojos.readMessage(fields, 240)) : null,
            Pojos.readMessage(fields, 241) != null ? Next.pojo.SpaceAct_MagicCreateNpcChange.parseFrom(Pojos.readMessage(fields, 241)) : null,
            Pojos.readMessage(fields, 242) != null ? Next.pojo.SpaceAct_VelocityOrientedRotation.parseFrom(Pojos.readMessage(fields, 242)) : null,
            Pojos.readMessage(fields, 243) != null ? Next.pojo.SpaceAct_WorldLaunchPlayer.parseFrom(Pojos.readMessage(fields, 243)) : null,
            Pojos.readMessage(fields, 244) != null ? Next.pojo.SpaceAct_AIPerformGroupIdChanged.parseFrom(Pojos.readMessage(fields, 244)) : null,
            Pojos.readMessage(fields, 245) != null ? Next.pojo.SpaceAct_OptActionNtf.parseFrom(Pojos.readMessage(fields, 245)) : null,
            Pojos.readMessage(fields, 246) != null ? Next.pojo.SpaceAct_CardIconChange.parseFrom(Pojos.readMessage(fields, 246)) : null,
            Pojos.readMessage(fields, 247) != null ? Next.pojo.SpaceAct_VideoRecord.parseFrom(Pojos.readMessage(fields, 247)) : null,
            Pojos.readMessage(fields, 260) != null ? Next.pojo.SpaceAct_Stun.parseFrom(Pojos.readMessage(fields, 260)) : null,
            Pojos.readMessage(fields, 263) != null ? Next.pojo.SpaceAct_CatchRecordInfoChange.parseFrom(Pojos.readMessage(fields, 263)) : null,
            Pojos.readMessage(fields, 264) != null ? Next.pojo.SpaceAct_HabitatNeighborInfoChange.parseFrom(Pojos.readMessage(fields, 264)) : null,
            Pojos.readMessage(fields, 265) != null ? Next.pojo.SpaceAct_AllHabitatNeighborInfo.parseFrom(Pojos.readMessage(fields, 265)) : null,
            Pojos.readMessage(fields, 300) != null ? Next.pojo.SpaceAct_WorldCombatEnter.parseFrom(Pojos.readMessage(fields, 300)) : null,
            Pojos.readMessage(fields, 301) != null ? Next.pojo.SpaceAct_WorldCombatExit.parseFrom(Pojos.readMessage(fields, 301)) : null,
            Pojos.readMessage(fields, 309) != null ? Next.pojo.SpaceAct_WorldCombatTextPrompts.parseFrom(Pojos.readMessage(fields, 309)) : null,
            Pojos.readMessage(fields, 310) != null ? Next.pojo.SpaceAct_WorldCombatPhaseUpdate.parseFrom(Pojos.readMessage(fields, 310)) : null,
            Pojos.readMessage(fields, 311) != null ? Next.pojo.SpaceAct_WorldCombatBegin.parseFrom(Pojos.readMessage(fields, 311)) : null,
            Pojos.readMessage(fields, 312) != null ? Next.pojo.SpaceAct_WorldCombatFinish.parseFrom(Pojos.readMessage(fields, 312)) : null,
            Pojos.readMessage(fields, 320) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillCast.parseFrom(Pojos.readMessage(fields, 320)) : null,
            Pojos.readMessage(fields, 321) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillEnd.parseFrom(Pojos.readMessage(fields, 321)) : null,
            Pojos.readMessage(fields, 322) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillCrush.parseFrom(Pojos.readMessage(fields, 322)) : null,
            Pojos.readMessage(fields, 323) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillHit.parseFrom(Pojos.readMessage(fields, 323)) : null,
            Pojos.readMessage(fields, 324) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillRotate.parseFrom(Pojos.readMessage(fields, 324)) : null,
            Pojos.readMessage(fields, 325) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillLookAt.parseFrom(Pojos.readMessage(fields, 325)) : null,
            Pojos.readMessage(fields, 326) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillCrushEnd.parseFrom(Pojos.readMessage(fields, 326)) : null,
            Pojos.readMessage(fields, 327) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillMissileLaunch.parseFrom(Pojos.readMessage(fields, 327)) : null,
            Pojos.readMessage(fields, 328) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillMissileDestroy.parseFrom(Pojos.readMessage(fields, 328)) : null,
            Pojos.readMessage(fields, 329) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillMissileStopTrace.parseFrom(Pojos.readMessage(fields, 329)) : null,
            Pojos.readMessage(fields, 330) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillJump.parseFrom(Pojos.readMessage(fields, 330)) : null,
            Pojos.readMessage(fields, 331) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillJumpCancel.parseFrom(Pojos.readMessage(fields, 331)) : null,
            Pojos.readMessage(fields, 332) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillRcd.parseFrom(Pojos.readMessage(fields, 332)) : null,
            Pojos.readMessage(fields, 333) != null ? Next.pojo.SpaceAct_WorldCombatExtraRewardUpdate.parseFrom(Pojos.readMessage(fields, 333)) : null,
            Pojos.readMessage(fields, 334) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillSelectPos.parseFrom(Pojos.readMessage(fields, 334)) : null,
            Pojos.readMessage(fields, 335) != null ? Next.pojo.SpaceAct_OwlSanctuaryDetected.parseFrom(Pojos.readMessage(fields, 335)) : null,
            Pojos.readMessage(fields, 336) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillJumpEnd.parseFrom(Pojos.readMessage(fields, 336)) : null,
            Pojos.readMessage(fields, 337) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillRcdEnd.parseFrom(Pojos.readMessage(fields, 337)) : null,
            Pojos.readMessage(fields, 338) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillHidden.parseFrom(Pojos.readMessage(fields, 338)) : null,
            Pojos.readMessage(fields, 339) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillHiddenEnd.parseFrom(Pojos.readMessage(fields, 339)) : null,
            Pojos.readMessage(fields, 340) != null ? Next.pojo.SpaceAct_OwlSanctuaryFruitInfoUpdate.parseFrom(Pojos.readMessage(fields, 340)) : null,
            Pojos.readMessage(fields, 350) != null ? Next.pojo.SpaceAct_SceneSvrErrEcho.parseFrom(Pojos.readMessage(fields, 350)) : null,
            Pojos.readMessage(fields, 351) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillShowHideChange.parseFrom(Pojos.readMessage(fields, 351)) : null,
            Pojos.readMessage(fields, 352) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillPosLerpSync.parseFrom(Pojos.readMessage(fields, 352)) : null,
            Pojos.readMessage(fields, 353) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillAnimCancel.parseFrom(Pojos.readMessage(fields, 353)) : null,
            Pojos.readMessage(fields, 354) != null ? Next.pojo.SpaceAct_HomeBasicInfoChangeNotify.parseFrom(Pojos.readMessage(fields, 354)) : null,
            Pojos.readMessage(fields, 355) != null ? Next.pojo.SpaceAct_HomePetInfoChangeNotify.parseFrom(Pojos.readMessage(fields, 355)) : null,
            Pojos.readMessage(fields, 356) != null ? Next.pojo.SpaceAct_HomePlantChangeNotify.parseFrom(Pojos.readMessage(fields, 356)) : null,
            Pojos.readMessage(fields, 357) != null ? Next.pojo.SpaceAct_HomePlantPlantCrop.parseFrom(Pojos.readMessage(fields, 357)) : null,
            Pojos.readMessage(fields, 358) != null ? Next.pojo.SpaceAct_HomePlantRoleWater.parseFrom(Pojos.readMessage(fields, 358)) : null,
            Pojos.readMessage(fields, 359) != null ? Next.pojo.SpaceAct_HomePlantPetWater.parseFrom(Pojos.readMessage(fields, 359)) : null,
            Pojos.readMessage(fields, 360) != null ? Next.pojo.SpaceAct_HomePlantRoleManure.parseFrom(Pojos.readMessage(fields, 360)) : null,
            Pojos.readMessage(fields, 361) != null ? Next.pojo.SpaceAct_HomePlantPetManure.parseFrom(Pojos.readMessage(fields, 361)) : null,
            Pojos.readMessage(fields, 362) != null ? Next.pojo.SpaceAct_HomePlantOwnerPick.parseFrom(Pojos.readMessage(fields, 362)) : null,
            Pojos.readMessage(fields, 363) != null ? Next.pojo.SpaceAct_HomePlantVisitorPick.parseFrom(Pojos.readMessage(fields, 363)) : null,
            Pojos.readMessage(fields, 370) != null ? Next.pojo.SpaceAct_HomeBasicVisitorEnterHome.parseFrom(Pojos.readMessage(fields, 370)) : null,
            Pojos.readMessage(fields, 371) != null ? Next.pojo.SpaceAct_HomeBasicVisitorLeavingHome.parseFrom(Pojos.readMessage(fields, 371)) : null,
            Pojos.readMessage(fields, 372) != null ? Next.pojo.SpaceAct_ActorPlantDataUpdate.parseFrom(Pojos.readMessage(fields, 372)) : null,
            Pojos.readMessage(fields, 373) != null ? Next.pojo.SpaceAct_TravelTogetherSync.parseFrom(Pojos.readMessage(fields, 373)) : null,
            Pojos.readMessage(fields, 390) != null ? Next.pojo.SpaceAct_InnerBattle.parseFrom(Pojos.readMessage(fields, 390)) : null,
            Pojos.readMessage(fields, 391) != null ? Next.pojo.SpaceAct_InnerBattleShieldBroken.parseFrom(Pojos.readMessage(fields, 391)) : null,
            Pojos.readMessage(fields, 392) != null ? Next.pojo.SpaceAct_InnerBattleChangePet.parseFrom(Pojos.readMessage(fields, 392)) : null,
            Pojos.readMessage(fields, 402) != null ? Next.pojo.SpaceAct_ActorKeepModel.parseFrom(Pojos.readMessage(fields, 402)) : null,
            Pojos.readMessage(fields, 403) != null ? Next.pojo.SpaceAct_HomeInteractNotify.parseFrom(Pojos.readMessage(fields, 403)) : null,
            Pojos.readMessage(fields, 404) != null ? Next.pojo.SpaceAct_PetClosenessLvUpgrade.parseFrom(Pojos.readMessage(fields, 404)) : null,
            Pojos.readMessage(fields, 425) != null ? Next.pojo.SpaceAct_CameraFlash.parseFrom(Pojos.readMessage(fields, 425)) : null,
            Pojos.readMessage(fields, 426) != null ? Next.pojo.SpaceAct_IdleSkill.parseFrom(Pojos.readMessage(fields, 426)) : null,
            Pojos.readMessage(fields, 427) != null ? Next.pojo.SpaceAct_PetVoice.parseFrom(Pojos.readMessage(fields, 427)) : null,
            Pojos.readMessage(fields, 428) != null ? Next.pojo.SpaceAct_VisibleCircle.parseFrom(Pojos.readMessage(fields, 428)) : null,
            Pojos.readMessage(fields, 429) != null ? Next.pojo.SpaceAct_AvatarStoryFlags.parseFrom(Pojos.readMessage(fields, 429)) : null,
            Pojos.readMessage(fields, 450) != null ? Next.pojo.SpaceAct_AISeqIdNotify.parseFrom(Pojos.readMessage(fields, 450)) : null
        );
    }
    public static SpaceActionCollection parseFrom(java.util.List<ProtoField> fields) {
        return new SpaceActionCollection(
            Pojos.readMessage(fields, 1) != null ? Next.pojo.SpaceAct_ActorEnter.parseFrom(Pojos.readMessage(fields, 1)) : null,
            Pojos.readMessage(fields, 2) != null ? Next.pojo.SpaceAct_ActorLeave.parseFrom(Pojos.readMessage(fields, 2)) : null,
            Pojos.readMessage(fields, 3) != null ? Next.pojo.SpaceAct_ActorNum.parseFrom(Pojos.readMessage(fields, 3)) : null,
            Pojos.readMessage(fields, 11) != null ? Next.pojo.SpaceAct_ClientMove.parseFrom(Pojos.readMessage(fields, 11)) : null,
            Pojos.readMessage(fields, 12) != null ? Next.pojo.SpaceAct_ServerMove.parseFrom(Pojos.readMessage(fields, 12)) : null,
            Pojos.readMessage(fields, 13) != null ? Next.pojo.SpaceAct_InterruptServerMove.parseFrom(Pojos.readMessage(fields, 13)) : null,
            Pojos.readMessage(fields, 15) != null ? Next.pojo.SpaceAct_LookAt.parseFrom(Pojos.readMessage(fields, 15)) : null,
            Pojos.readMessage(fields, 16) != null ? Next.pojo.SpaceAct_TurnTo.parseFrom(Pojos.readMessage(fields, 16)) : null,
            Pojos.readMessage(fields, 17) != null ? Next.pojo.SpaceAct_CancelTurnTo.parseFrom(Pojos.readMessage(fields, 17)) : null,
            Pojos.readMessage(fields, 18) != null ? Next.pojo.SpaceAct_ServerFly.parseFrom(Pojos.readMessage(fields, 18)) : null,
            Pojos.readMessage(fields, 19) != null ? Next.pojo.SpaceAct_ServerAttach.parseFrom(Pojos.readMessage(fields, 19)) : null,
            Pojos.readMessage(fields, 20) != null ? Next.pojo.SpaceAct_CancelServerAttach.parseFrom(Pojos.readMessage(fields, 20)) : null,
            Pojos.readMessage(fields, 21) != null ? Next.pojo.SpaceAct_AddStoryFlags.parseFrom(Pojos.readMessage(fields, 21)) : null,
            Pojos.readMessage(fields, 22) != null ? Next.pojo.SpaceAct_RemoveStoryFlags.parseFrom(Pojos.readMessage(fields, 22)) : null,
            Pojos.readMessage(fields, 23) != null ? Next.pojo.SpaceAct_NpcOptionInfoChange.parseFrom(Pojos.readMessage(fields, 23)) : null,
            Pojos.readMessage(fields, 24) != null ? Next.pojo.SpaceAct_NpcOptionAddSelects.parseFrom(Pojos.readMessage(fields, 24)) : null,
            Pojos.readMessage(fields, 25) != null ? Next.pojo.SpaceAct_NpcOptionRemoveSelects.parseFrom(Pojos.readMessage(fields, 25)) : null,
            Pojos.readMessage(fields, 26) != null ? Next.pojo.SpaceAct_NpcDialogSelectInfoChange.parseFrom(Pojos.readMessage(fields, 26)) : null,
            Pojos.readMessage(fields, 27) != null ? Next.pojo.SpaceAct_AddNpcOption.parseFrom(Pojos.readMessage(fields, 27)) : null,
            Pojos.readMessage(fields, 28) != null ? Next.pojo.SpaceAct_RemoveNpcOption.parseFrom(Pojos.readMessage(fields, 28)) : null,
            Pojos.readMessage(fields, 29) != null ? Next.pojo.SpaceAct_BeginActResultParamsNty.parseFrom(Pojos.readMessage(fields, 29)) : null,
            Pojos.readMessage(fields, 30) != null ? Next.pojo.SpaceAct_NpcCanbeTeleportNty.parseFrom(Pojos.readMessage(fields, 30)) : null,
            Pojos.readMessage(fields, 31) != null ? Next.pojo.SpaceAct_UpdateActorLogicStatus.parseFrom(Pojos.readMessage(fields, 31)) : null,
            Pojos.readMessage(fields, 32) != null ? Next.pojo.SpaceAct_CombineLockStateChange.parseFrom(Pojos.readMessage(fields, 32)) : null,
            Pojos.readMessage(fields, 33) != null ? Next.pojo.SpaceAct_TrackingNpc.parseFrom(Pojos.readMessage(fields, 33)) : null,
            Pojos.readMessage(fields, 34) != null ? Next.pojo.SpaceAct_VisibleZone.parseFrom(Pojos.readMessage(fields, 34)) : null,
            Pojos.readMessage(fields, 35) != null ? Next.pojo.SpaceAct_SyncPlayerStatus.parseFrom(Pojos.readMessage(fields, 35)) : null,
            Pojos.readMessage(fields, 36) != null ? Next.pojo.SpaceAct_PotentialEnergyChange.parseFrom(Pojos.readMessage(fields, 36)) : null,
            Pojos.readMessage(fields, 37) != null ? Next.pojo.SpaceAct_EnvMask.parseFrom(Pojos.readMessage(fields, 37)) : null,
            Pojos.readMessage(fields, 38) != null ? Next.pojo.SpaceAct_PropertyTypeChange.parseFrom(Pojos.readMessage(fields, 38)) : null,
            Pojos.readMessage(fields, 39) != null ? Next.pojo.SpaceAct_ActorBornEnd.parseFrom(Pojos.readMessage(fields, 39)) : null,
            Pojos.readMessage(fields, 40) != null ? Next.pojo.SpaceAct_ActorDieBegin.parseFrom(Pojos.readMessage(fields, 40)) : null,
            Pojos.readMessage(fields, 41) != null ? Next.pojo.SpaceAct_BeginDropItem.parseFrom(Pojos.readMessage(fields, 41)) : null,
            Pojos.readMessage(fields, 42) != null ? Next.pojo.SpaceAct_EndDropItem.parseFrom(Pojos.readMessage(fields, 42)) : null,
            Pojos.readMessage(fields, 51) != null ? Next.pojo.SpaceAct_AttrChange.parseFrom(Pojos.readMessage(fields, 51)) : null,
            Pojos.readMessage(fields, 61) != null ? Next.pojo.SpaceAct_EnteredCatcher.parseFrom(Pojos.readMessage(fields, 61)) : null,
            Pojos.readMessage(fields, 62) != null ? Next.pojo.SpaceAct_LeftCatcher.parseFrom(Pojos.readMessage(fields, 62)) : null,
            Pojos.readMessage(fields, 71) != null ? Next.pojo.SpaceAct_PlayAnimation.parseFrom(Pojos.readMessage(fields, 71)) : null,
            Pojos.readMessage(fields, 72) != null ? Next.pojo.SpaceAct_StopAnimation.parseFrom(Pojos.readMessage(fields, 72)) : null,
            Pojos.readMessage(fields, 73) != null ? Next.pojo.SpaceAct_AnimPauseOrResume.parseFrom(Pojos.readMessage(fields, 73)) : null,
            Pojos.readMessage(fields, 74) != null ? Next.pojo.SpaceAct_PlaySkill.parseFrom(Pojos.readMessage(fields, 74)) : null,
            Pojos.readMessage(fields, 75) != null ? Next.pojo.SpaceAct_StopSkill.parseFrom(Pojos.readMessage(fields, 75)) : null,
            Pojos.readMessage(fields, 76) != null ? Next.pojo.SpaceAct_WorldHidden.parseFrom(Pojos.readMessage(fields, 76)) : null,
            Pojos.readMessage(fields, 77) != null ? Next.pojo.SpaceAct_WorldUnHidden.parseFrom(Pojos.readMessage(fields, 77)) : null,
            Pojos.readMessage(fields, 78) != null ? Next.pojo.SpaceAct_PlayZoomAnimation.parseFrom(Pojos.readMessage(fields, 78)) : null,
            Pojos.readMessage(fields, 80) != null ? Next.pojo.SpaceAct_PlayAnimBeforeRemove.parseFrom(Pojos.readMessage(fields, 80)) : null,
            Pojos.readMessage(fields, 81) != null ? Next.pojo.SpaceAct_ShowPetFaceState.parseFrom(Pojos.readMessage(fields, 81)) : null,
            Pojos.readMessage(fields, 82) != null ? Next.pojo.SpaceAct_ModelDisplay.parseFrom(Pojos.readMessage(fields, 82)) : null,
            Pojos.readMessage(fields, 83) != null ? Next.pojo.SpaceAct_PlayPerceptionEffect.parseFrom(Pojos.readMessage(fields, 83)) : null,
            Pojos.readMessage(fields, 84) != null ? Next.pojo.SpaceAct_PlayPerceptionHud.parseFrom(Pojos.readMessage(fields, 84)) : null,
            Pojos.readMessage(fields, 85) != null ? Next.pojo.SpaceAct_NpcTrace.parseFrom(Pojos.readMessage(fields, 85)) : null,
            Pojos.readMessage(fields, 86) != null ? Next.pojo.SpaceAct_NpcPerceivePlayer.parseFrom(Pojos.readMessage(fields, 86)) : null,
            Pojos.readMessage(fields, 91) != null ? Next.pojo.SpaceAct_BattleOnOff.parseFrom(Pojos.readMessage(fields, 91)) : null,
            Pojos.readMessage(fields, 92) != null ? Next.pojo.SpaceAct_WorldAttack.parseFrom(Pojos.readMessage(fields, 92)) : null,
            Pojos.readMessage(fields, 93) != null ? Next.pojo.SpaceAct_StopWorldAttack.parseFrom(Pojos.readMessage(fields, 93)) : null,
            Pojos.readMessage(fields, 101) != null ? Next.pojo.SpaceAct_MfbtDebug.parseFrom(Pojos.readMessage(fields, 101)) : null,
            Pojos.readMessage(fields, 102) != null ? Next.pojo.SpaceAct_BattleAIStatusChanged.parseFrom(Pojos.readMessage(fields, 102)) : null,
            Pojos.readMessage(fields, 103) != null ? Next.pojo.SpaceAct_SceneAiControlFlagsChanged.parseFrom(Pojos.readMessage(fields, 103)) : null,
            Pojos.readMessage(fields, 104) != null ? Next.pojo.SpaceAct_ServerAIJump.parseFrom(Pojos.readMessage(fields, 104)) : null,
            Pojos.readMessage(fields, 105) != null ? Next.pojo.SpaceAct_CancelServerAIJump.parseFrom(Pojos.readMessage(fields, 105)) : null,
            Pojos.readMessage(fields, 106) != null ? Next.pojo.SpaceAct_StickTo.parseFrom(Pojos.readMessage(fields, 106)) : null,
            Pojos.readMessage(fields, 107) != null ? Next.pojo.SpaceAct_FinishStickTo.parseFrom(Pojos.readMessage(fields, 107)) : null,
            Pojos.readMessage(fields, 108) != null ? Next.pojo.SpaceAct_AITryInteractNpc.parseFrom(Pojos.readMessage(fields, 108)) : null,
            Pojos.readMessage(fields, 109) != null ? Next.pojo.SpaceAct_SwitchBossAINty.parseFrom(Pojos.readMessage(fields, 109)) : null,
            Pojos.readMessage(fields, 110) != null ? Next.pojo.SpaceAct_AIMoveMode.parseFrom(Pojos.readMessage(fields, 110)) : null,
            Pojos.readMessage(fields, 112) != null ? Next.pojo.SpaceAct_InformClientSwitchAINty.parseFrom(Pojos.readMessage(fields, 112)) : null,
            Pojos.readMessage(fields, 113) != null ? Next.pojo.SpaceAct_ClientSwitchToServerAINty.parseFrom(Pojos.readMessage(fields, 113)) : null,
            Pojos.readMessage(fields, 111) != null ? Next.pojo.SpaceAct_CastSceneSkill.parseFrom(Pojos.readMessage(fields, 111)) : null,
            Pojos.readMessage(fields, 121) != null ? Next.pojo.SpaceAct_FriendRide.parseFrom(Pojos.readMessage(fields, 121)) : null,
            Pojos.readMessage(fields, 131) != null ? Next.pojo.SpaceAct_CollisionCancelRecover.parseFrom(Pojos.readMessage(fields, 131)) : null,
            Pojos.readMessage(fields, 141) != null ? Next.pojo.SpaceAct_ChangeSceneNotify.parseFrom(Pojos.readMessage(fields, 141)) : null,
            Pojos.readMessage(fields, 151) != null ? Next.pojo.SpaceAct_AuraInfoChange.parseFrom(Pojos.readMessage(fields, 151)) : null,
            Pojos.readMessage(fields, 161) != null ? Next.pojo.SpaceAct_BodyTempNotify.parseFrom(Pojos.readMessage(fields, 161)) : null,
            Pojos.readMessage(fields, 171) != null ? Next.pojo.SpaceAct_ThrowedPetInfoChange.parseFrom(Pojos.readMessage(fields, 171)) : null,
            Pojos.readMessage(fields, 172) != null ? Next.pojo.SpaceAct_DelThrowingMagic.parseFrom(Pojos.readMessage(fields, 172)) : null,
            Pojos.readMessage(fields, 173) != null ? Next.pojo.SpaceAct_DeleteThrowNotify.parseFrom(Pojos.readMessage(fields, 173)) : null,
            Pojos.readMessage(fields, 182) != null ? Next.pojo.SpaceAct_AirWallChange.parseFrom(Pojos.readMessage(fields, 182)) : null,
            Pojos.readMessage(fields, 191) != null ? Next.pojo.SpaceAct_WeatherChange.parseFrom(Pojos.readMessage(fields, 191)) : null,
            Pojos.readMessage(fields, 200) != null ? Next.pojo.SpaceAct_GameTimeChange.parseFrom(Pojos.readMessage(fields, 200)) : null,
            Pojos.readMessage(fields, 201) != null ? Next.pojo.SpaceAct_MinigameNotify.parseFrom(Pojos.readMessage(fields, 201)) : null,
            Pojos.readMessage(fields, 202) != null ? Next.pojo.SpaceAct_GuideTask.parseFrom(Pojos.readMessage(fields, 202)) : null,
            Pojos.readMessage(fields, 203) != null ? Next.pojo.SpaceAct_ClientEventResume.parseFrom(Pojos.readMessage(fields, 203)) : null,
            Pojos.readMessage(fields, 204) != null ? Next.pojo.SpaceAct_NpcPendantInfoChange.parseFrom(Pojos.readMessage(fields, 204)) : null,
            Pojos.readMessage(fields, 205) != null ? Next.pojo.SpaceAct_UnlockSleepingOwl.parseFrom(Pojos.readMessage(fields, 205)) : null,
            Pojos.readMessage(fields, 206) != null ? Next.pojo.SpaceAct_OwlRefugeInfoChange.parseFrom(Pojos.readMessage(fields, 206)) : null,
            Pojos.readMessage(fields, 207) != null ? Next.pojo.SpaceAct_NpcDistribution.parseFrom(Pojos.readMessage(fields, 207)) : null,
            Pojos.readMessage(fields, 208) != null ? Next.pojo.SpaceAct_HeadLookAt.parseFrom(Pojos.readMessage(fields, 208)) : null,
            Pojos.readMessage(fields, 209) != null ? Next.pojo.SpaceAct_FashionChange.parseFrom(Pojos.readMessage(fields, 209)) : null,
            Pojos.readMessage(fields, 210) != null ? Next.pojo.SpaceAct_SalonChange.parseFrom(Pojos.readMessage(fields, 210)) : null,
            Pojos.readMessage(fields, 211) != null ? Next.pojo.SpaceAct_ClientOperation.parseFrom(Pojos.readMessage(fields, 211)) : null,
            Pojos.readMessage(fields, 212) != null ? Next.pojo.SpaceAct_BondFind.parseFrom(Pojos.readMessage(fields, 212)) : null,
            Pojos.readMessage(fields, 213) != null ? Next.pojo.SpaceAct_ScenePetInfoChange.parseFrom(Pojos.readMessage(fields, 213)) : null,
            Pojos.readMessage(fields, 214) != null ? Next.pojo.SpaceAct_SceneDotsComponentSync.parseFrom(Pojos.readMessage(fields, 214)) : null,
            Pojos.readMessage(fields, 215) != null ? Next.pojo.SpaceAct_GameTimeSync.parseFrom(Pojos.readMessage(fields, 215)) : null,
            Pojos.readMessage(fields, 216) != null ? Next.pojo.SpaceAct_PetInteractResNty.parseFrom(Pojos.readMessage(fields, 216)) : null,
            Pojos.readMessage(fields, 217) != null ? Next.pojo.SpaceAct_CombineInteractInfoChange.parseFrom(Pojos.readMessage(fields, 217)) : null,
            Pojos.readMessage(fields, 218) != null ? Next.pojo.SpaceAct_BuffInfoChange.parseFrom(Pojos.readMessage(fields, 218)) : null,
            Pojos.readMessage(fields, 219) != null ? Next.pojo.SpaceAct_NameChange.parseFrom(Pojos.readMessage(fields, 219)) : null,
            Pojos.readMessage(fields, 220) != null ? Next.pojo.SpaceAct_RelatedNpcInfosChanged.parseFrom(Pojos.readMessage(fields, 220)) : null,
            Pojos.readMessage(fields, 221) != null ? Next.pojo.SpaceAct_WorldMapInfoChanged.parseFrom(Pojos.readMessage(fields, 221)) : null,
            Pojos.readMessage(fields, 222) != null ? Next.pojo.SpaceAct_SetNpcPos.parseFrom(Pojos.readMessage(fields, 222)) : null,
            Pojos.readMessage(fields, 223) != null ? Next.pojo.SpaceAct_PlayVoice.parseFrom(Pojos.readMessage(fields, 223)) : null,
            Pojos.readMessage(fields, 224) != null ? Next.pojo.SpaceAct_StopVoice.parseFrom(Pojos.readMessage(fields, 224)) : null,
            Pojos.readMessage(fields, 225) != null ? Next.pojo.SpaceAct_NpcGuideChange.parseFrom(Pojos.readMessage(fields, 225)) : null,
            Pojos.readMessage(fields, 226) != null ? Next.pojo.SpaceAct_ChangeLoopAction.parseFrom(Pojos.readMessage(fields, 226)) : null,
            Pojos.readMessage(fields, 227) != null ? Next.pojo.SpaceAct_CatchGuaranteeChange.parseFrom(Pojos.readMessage(fields, 227)) : null,
            Pojos.readMessage(fields, 228) != null ? Next.pojo.SpaceAct_PlayerMatch.parseFrom(Pojos.readMessage(fields, 228)) : null,
            Pojos.readMessage(fields, 229) != null ? Next.pojo.SpaceAct_NpcVisualInfoChange.parseFrom(Pojos.readMessage(fields, 229)) : null,
            Pojos.readMessage(fields, 230) != null ? Next.pojo.SpaceAct_BattleBuffInfoChanged.parseFrom(Pojos.readMessage(fields, 230)) : null,
            Pojos.readMessage(fields, 231) != null ? Next.pojo.SpaceAct_CardLabelChange.parseFrom(Pojos.readMessage(fields, 231)) : null,
            Pojos.readMessage(fields, 232) != null ? Next.pojo.SpaceAct_CardSkinChange.parseFrom(Pojos.readMessage(fields, 232)) : null,
            Pojos.readMessage(fields, 233) != null ? Next.pojo.SpaceAct_SameCellTeleport.parseFrom(Pojos.readMessage(fields, 233)) : null,
            Pojos.readMessage(fields, 234) != null ? Next.pojo.SpaceAct_FollowInfoChangedNty.parseFrom(Pojos.readMessage(fields, 234)) : null,
            Pojos.readMessage(fields, 235) != null ? Next.pojo.SpaceAct_CollectHandbookRecordsChange.parseFrom(Pojos.readMessage(fields, 235)) : null,
            Pojos.readMessage(fields, 236) != null ? Next.pojo.SpaceAct_PositionInvalid.parseFrom(Pojos.readMessage(fields, 236)) : null,
            Pojos.readMessage(fields, 237) != null ? Next.pojo.SpaceAct_TaskStateChangeNty.parseFrom(Pojos.readMessage(fields, 237)) : null,
            Pojos.readMessage(fields, 238) != null ? Next.pojo.SpaceAct_PlayRealtimeDialog.parseFrom(Pojos.readMessage(fields, 238)) : null,
            Pojos.readMessage(fields, 239) != null ? Next.pojo.SpaceAct_StopRealtimeDialog.parseFrom(Pojos.readMessage(fields, 239)) : null,
            Pojos.readMessage(fields, 240) != null ? Next.pojo.SpaceAct_CardMusicChange.parseFrom(Pojos.readMessage(fields, 240)) : null,
            Pojos.readMessage(fields, 241) != null ? Next.pojo.SpaceAct_MagicCreateNpcChange.parseFrom(Pojos.readMessage(fields, 241)) : null,
            Pojos.readMessage(fields, 242) != null ? Next.pojo.SpaceAct_VelocityOrientedRotation.parseFrom(Pojos.readMessage(fields, 242)) : null,
            Pojos.readMessage(fields, 243) != null ? Next.pojo.SpaceAct_WorldLaunchPlayer.parseFrom(Pojos.readMessage(fields, 243)) : null,
            Pojos.readMessage(fields, 244) != null ? Next.pojo.SpaceAct_AIPerformGroupIdChanged.parseFrom(Pojos.readMessage(fields, 244)) : null,
            Pojos.readMessage(fields, 245) != null ? Next.pojo.SpaceAct_OptActionNtf.parseFrom(Pojos.readMessage(fields, 245)) : null,
            Pojos.readMessage(fields, 246) != null ? Next.pojo.SpaceAct_CardIconChange.parseFrom(Pojos.readMessage(fields, 246)) : null,
            Pojos.readMessage(fields, 247) != null ? Next.pojo.SpaceAct_VideoRecord.parseFrom(Pojos.readMessage(fields, 247)) : null,
            Pojos.readMessage(fields, 260) != null ? Next.pojo.SpaceAct_Stun.parseFrom(Pojos.readMessage(fields, 260)) : null,
            Pojos.readMessage(fields, 263) != null ? Next.pojo.SpaceAct_CatchRecordInfoChange.parseFrom(Pojos.readMessage(fields, 263)) : null,
            Pojos.readMessage(fields, 264) != null ? Next.pojo.SpaceAct_HabitatNeighborInfoChange.parseFrom(Pojos.readMessage(fields, 264)) : null,
            Pojos.readMessage(fields, 265) != null ? Next.pojo.SpaceAct_AllHabitatNeighborInfo.parseFrom(Pojos.readMessage(fields, 265)) : null,
            Pojos.readMessage(fields, 300) != null ? Next.pojo.SpaceAct_WorldCombatEnter.parseFrom(Pojos.readMessage(fields, 300)) : null,
            Pojos.readMessage(fields, 301) != null ? Next.pojo.SpaceAct_WorldCombatExit.parseFrom(Pojos.readMessage(fields, 301)) : null,
            Pojos.readMessage(fields, 309) != null ? Next.pojo.SpaceAct_WorldCombatTextPrompts.parseFrom(Pojos.readMessage(fields, 309)) : null,
            Pojos.readMessage(fields, 310) != null ? Next.pojo.SpaceAct_WorldCombatPhaseUpdate.parseFrom(Pojos.readMessage(fields, 310)) : null,
            Pojos.readMessage(fields, 311) != null ? Next.pojo.SpaceAct_WorldCombatBegin.parseFrom(Pojos.readMessage(fields, 311)) : null,
            Pojos.readMessage(fields, 312) != null ? Next.pojo.SpaceAct_WorldCombatFinish.parseFrom(Pojos.readMessage(fields, 312)) : null,
            Pojos.readMessage(fields, 320) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillCast.parseFrom(Pojos.readMessage(fields, 320)) : null,
            Pojos.readMessage(fields, 321) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillEnd.parseFrom(Pojos.readMessage(fields, 321)) : null,
            Pojos.readMessage(fields, 322) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillCrush.parseFrom(Pojos.readMessage(fields, 322)) : null,
            Pojos.readMessage(fields, 323) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillHit.parseFrom(Pojos.readMessage(fields, 323)) : null,
            Pojos.readMessage(fields, 324) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillRotate.parseFrom(Pojos.readMessage(fields, 324)) : null,
            Pojos.readMessage(fields, 325) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillLookAt.parseFrom(Pojos.readMessage(fields, 325)) : null,
            Pojos.readMessage(fields, 326) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillCrushEnd.parseFrom(Pojos.readMessage(fields, 326)) : null,
            Pojos.readMessage(fields, 327) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillMissileLaunch.parseFrom(Pojos.readMessage(fields, 327)) : null,
            Pojos.readMessage(fields, 328) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillMissileDestroy.parseFrom(Pojos.readMessage(fields, 328)) : null,
            Pojos.readMessage(fields, 329) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillMissileStopTrace.parseFrom(Pojos.readMessage(fields, 329)) : null,
            Pojos.readMessage(fields, 330) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillJump.parseFrom(Pojos.readMessage(fields, 330)) : null,
            Pojos.readMessage(fields, 331) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillJumpCancel.parseFrom(Pojos.readMessage(fields, 331)) : null,
            Pojos.readMessage(fields, 332) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillRcd.parseFrom(Pojos.readMessage(fields, 332)) : null,
            Pojos.readMessage(fields, 333) != null ? Next.pojo.SpaceAct_WorldCombatExtraRewardUpdate.parseFrom(Pojos.readMessage(fields, 333)) : null,
            Pojos.readMessage(fields, 334) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillSelectPos.parseFrom(Pojos.readMessage(fields, 334)) : null,
            Pojos.readMessage(fields, 335) != null ? Next.pojo.SpaceAct_OwlSanctuaryDetected.parseFrom(Pojos.readMessage(fields, 335)) : null,
            Pojos.readMessage(fields, 336) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillJumpEnd.parseFrom(Pojos.readMessage(fields, 336)) : null,
            Pojos.readMessage(fields, 337) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillRcdEnd.parseFrom(Pojos.readMessage(fields, 337)) : null,
            Pojos.readMessage(fields, 338) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillHidden.parseFrom(Pojos.readMessage(fields, 338)) : null,
            Pojos.readMessage(fields, 339) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillHiddenEnd.parseFrom(Pojos.readMessage(fields, 339)) : null,
            Pojos.readMessage(fields, 340) != null ? Next.pojo.SpaceAct_OwlSanctuaryFruitInfoUpdate.parseFrom(Pojos.readMessage(fields, 340)) : null,
            Pojos.readMessage(fields, 350) != null ? Next.pojo.SpaceAct_SceneSvrErrEcho.parseFrom(Pojos.readMessage(fields, 350)) : null,
            Pojos.readMessage(fields, 351) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillShowHideChange.parseFrom(Pojos.readMessage(fields, 351)) : null,
            Pojos.readMessage(fields, 352) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillPosLerpSync.parseFrom(Pojos.readMessage(fields, 352)) : null,
            Pojos.readMessage(fields, 353) != null ? Next.pojo.SpaceAct_WorldCombatDotsSkillAnimCancel.parseFrom(Pojos.readMessage(fields, 353)) : null,
            Pojos.readMessage(fields, 354) != null ? Next.pojo.SpaceAct_HomeBasicInfoChangeNotify.parseFrom(Pojos.readMessage(fields, 354)) : null,
            Pojos.readMessage(fields, 355) != null ? Next.pojo.SpaceAct_HomePetInfoChangeNotify.parseFrom(Pojos.readMessage(fields, 355)) : null,
            Pojos.readMessage(fields, 356) != null ? Next.pojo.SpaceAct_HomePlantChangeNotify.parseFrom(Pojos.readMessage(fields, 356)) : null,
            Pojos.readMessage(fields, 357) != null ? Next.pojo.SpaceAct_HomePlantPlantCrop.parseFrom(Pojos.readMessage(fields, 357)) : null,
            Pojos.readMessage(fields, 358) != null ? Next.pojo.SpaceAct_HomePlantRoleWater.parseFrom(Pojos.readMessage(fields, 358)) : null,
            Pojos.readMessage(fields, 359) != null ? Next.pojo.SpaceAct_HomePlantPetWater.parseFrom(Pojos.readMessage(fields, 359)) : null,
            Pojos.readMessage(fields, 360) != null ? Next.pojo.SpaceAct_HomePlantRoleManure.parseFrom(Pojos.readMessage(fields, 360)) : null,
            Pojos.readMessage(fields, 361) != null ? Next.pojo.SpaceAct_HomePlantPetManure.parseFrom(Pojos.readMessage(fields, 361)) : null,
            Pojos.readMessage(fields, 362) != null ? Next.pojo.SpaceAct_HomePlantOwnerPick.parseFrom(Pojos.readMessage(fields, 362)) : null,
            Pojos.readMessage(fields, 363) != null ? Next.pojo.SpaceAct_HomePlantVisitorPick.parseFrom(Pojos.readMessage(fields, 363)) : null,
            Pojos.readMessage(fields, 370) != null ? Next.pojo.SpaceAct_HomeBasicVisitorEnterHome.parseFrom(Pojos.readMessage(fields, 370)) : null,
            Pojos.readMessage(fields, 371) != null ? Next.pojo.SpaceAct_HomeBasicVisitorLeavingHome.parseFrom(Pojos.readMessage(fields, 371)) : null,
            Pojos.readMessage(fields, 372) != null ? Next.pojo.SpaceAct_ActorPlantDataUpdate.parseFrom(Pojos.readMessage(fields, 372)) : null,
            Pojos.readMessage(fields, 373) != null ? Next.pojo.SpaceAct_TravelTogetherSync.parseFrom(Pojos.readMessage(fields, 373)) : null,
            Pojos.readMessage(fields, 390) != null ? Next.pojo.SpaceAct_InnerBattle.parseFrom(Pojos.readMessage(fields, 390)) : null,
            Pojos.readMessage(fields, 391) != null ? Next.pojo.SpaceAct_InnerBattleShieldBroken.parseFrom(Pojos.readMessage(fields, 391)) : null,
            Pojos.readMessage(fields, 392) != null ? Next.pojo.SpaceAct_InnerBattleChangePet.parseFrom(Pojos.readMessage(fields, 392)) : null,
            Pojos.readMessage(fields, 402) != null ? Next.pojo.SpaceAct_ActorKeepModel.parseFrom(Pojos.readMessage(fields, 402)) : null,
            Pojos.readMessage(fields, 403) != null ? Next.pojo.SpaceAct_HomeInteractNotify.parseFrom(Pojos.readMessage(fields, 403)) : null,
            Pojos.readMessage(fields, 404) != null ? Next.pojo.SpaceAct_PetClosenessLvUpgrade.parseFrom(Pojos.readMessage(fields, 404)) : null,
            Pojos.readMessage(fields, 425) != null ? Next.pojo.SpaceAct_CameraFlash.parseFrom(Pojos.readMessage(fields, 425)) : null,
            Pojos.readMessage(fields, 426) != null ? Next.pojo.SpaceAct_IdleSkill.parseFrom(Pojos.readMessage(fields, 426)) : null,
            Pojos.readMessage(fields, 427) != null ? Next.pojo.SpaceAct_PetVoice.parseFrom(Pojos.readMessage(fields, 427)) : null,
            Pojos.readMessage(fields, 428) != null ? Next.pojo.SpaceAct_VisibleCircle.parseFrom(Pojos.readMessage(fields, 428)) : null,
            Pojos.readMessage(fields, 429) != null ? Next.pojo.SpaceAct_AvatarStoryFlags.parseFrom(Pojos.readMessage(fields, 429)) : null,
            Pojos.readMessage(fields, 450) != null ? Next.pojo.SpaceAct_AISeqIdNotify.parseFrom(Pojos.readMessage(fields, 450)) : null
        );
    }
}
