// Generated from com_team_battle.proto
package Next.pojo;

import io.github.kedaya0209.roco.sniffer.codec.Pojos;
import io.github.kedaya0209.roco.sniffer.codec.ProtoParser.ProtoField;
import io.github.kedaya0209.roco.sniffer.codec.ProtoParser;
import java.util.List;

@SuppressWarnings("unused")
public record TeamBattleInfo(
    int teamBattleType,
    long npcLogicId,
    long npcObjId,
    int startBattleTime,
    int endTimestamp,
    int npcCfgId,
    int star,
    int blood,
    int battlePetbaseId,
    boolean randedBattleNpcGlass,
    boolean battleNpcGlass,
    GlassInfo battleNpcGlassInfo,
    boolean battleNpcShiny,
    int campCfgId,
    int battleNpcLv,
    int battleNpcHpTalent,
    int battleNpcAttackTalent,
    int battleNpcSpecialAttackTalent,
    int battleNpcDefenseTalent,
    int battleNpcSpecialDefenseTalent,
    int battleNpcSpeedTalent,
    int battleNpcGender,
    int battleNpcNature,
    int battleCfgId,
    int selectStar,
    int catchVitemQuantity,
    int specFlowerSeedId,
    int activityId,
    List<InnerBattleTask> battleTasks,
    int bindPetGid,
    int bindPetbaseId,
    int bindEvolutionId,
    int medalId,
    List<NpcBattleAssist> npcAssists,
    List<FlowerSeedBossData> visitFlowerSeedBossDatas,
    int selectFlowerOwnerId
) {
    public static TeamBattleInfo parseFrom(byte[] data) {
        java.util.List<ProtoField> fields = ProtoParser.parse(data);
        return new TeamBattleInfo(
            Pojos.readInt(fields, 11),
            Pojos.readLong(fields, 6),
            Pojos.readLong(fields, 7),
            Pojos.readInt(fields, 12),
            Pojos.readInt(fields, 27),
            Pojos.readInt(fields, 1),
            Pojos.readInt(fields, 2),
            Pojos.readInt(fields, 3),
            Pojos.readInt(fields, 5),
            Pojos.readBool(fields, 4),
            Pojos.readBool(fields, 8),
            Pojos.readMessage(fields, 32) != null ? Next.pojo.GlassInfo.parseFrom(Pojos.readMessage(fields, 32)) : null,
            Pojos.readBool(fields, 28),
            Pojos.readInt(fields, 9),
            Pojos.readInt(fields, 10),
            Pojos.readInt(fields, 13),
            Pojos.readInt(fields, 14),
            Pojos.readInt(fields, 15),
            Pojos.readInt(fields, 16),
            Pojos.readInt(fields, 17),
            Pojos.readInt(fields, 18),
            Pojos.readInt(fields, 19),
            Pojos.readInt(fields, 20),
            Pojos.readInt(fields, 21),
            Pojos.readInt(fields, 23),
            Pojos.readInt(fields, 24),
            Pojos.readInt(fields, 25),
            Pojos.readInt(fields, 26),
            Pojos.readMessageList(fields, 29).stream().map(Next.pojo.InnerBattleTask::parseFrom).toList(),
            Pojos.readInt(fields, 30),
            Pojos.readInt(fields, 33),
            Pojos.readInt(fields, 34),
            Pojos.readInt(fields, 37),
            Pojos.readMessageList(fields, 31).stream().map(Next.pojo.NpcBattleAssist::parseFrom).toList(),
            Pojos.readMessageList(fields, 35).stream().map(Next.pojo.FlowerSeedBossData::parseFrom).toList(),
            Pojos.readInt(fields, 36)
        );
    }
    public static TeamBattleInfo parseFrom(java.util.List<ProtoField> fields) {
        return new TeamBattleInfo(
            Pojos.readInt(fields, 11),
            Pojos.readLong(fields, 6),
            Pojos.readLong(fields, 7),
            Pojos.readInt(fields, 12),
            Pojos.readInt(fields, 27),
            Pojos.readInt(fields, 1),
            Pojos.readInt(fields, 2),
            Pojos.readInt(fields, 3),
            Pojos.readInt(fields, 5),
            Pojos.readBool(fields, 4),
            Pojos.readBool(fields, 8),
            Pojos.readMessage(fields, 32) != null ? Next.pojo.GlassInfo.parseFrom(Pojos.readMessage(fields, 32)) : null,
            Pojos.readBool(fields, 28),
            Pojos.readInt(fields, 9),
            Pojos.readInt(fields, 10),
            Pojos.readInt(fields, 13),
            Pojos.readInt(fields, 14),
            Pojos.readInt(fields, 15),
            Pojos.readInt(fields, 16),
            Pojos.readInt(fields, 17),
            Pojos.readInt(fields, 18),
            Pojos.readInt(fields, 19),
            Pojos.readInt(fields, 20),
            Pojos.readInt(fields, 21),
            Pojos.readInt(fields, 23),
            Pojos.readInt(fields, 24),
            Pojos.readInt(fields, 25),
            Pojos.readInt(fields, 26),
            Pojos.readMessageList(fields, 29).stream().map(Next.pojo.InnerBattleTask::parseFrom).toList(),
            Pojos.readInt(fields, 30),
            Pojos.readInt(fields, 33),
            Pojos.readInt(fields, 34),
            Pojos.readInt(fields, 37),
            Pojos.readMessageList(fields, 31).stream().map(Next.pojo.NpcBattleAssist::parseFrom).toList(),
            Pojos.readMessageList(fields, 35).stream().map(Next.pojo.FlowerSeedBossData::parseFrom).toList(),
            Pojos.readInt(fields, 36)
        );
    }
}
